# Importing Dataset #

In [1]:
import pandas as pd

In [2]:
# Prep data for attribute extraction
dataset_normalized_attributes = pd.read_excel('../Data/Normalized_product_attribute_name.xlsx', sheet_name = 'Normalized Product Attributes')
dataset_normalized_attributes

,BedType,OTA TYPE = BED,Unnamed: 2,RoomType,OTA TYPE = GRI,Unnamed: 5,Rateplan Incl/Value-adds,OTA TYPE = HAC,Unnamed: 8,Room Amenities,OTA TYPE = RMA,Unnamed: 11,Mealplan,OTA TYPE = MPT,Unnamed: 14,RoomView,OTA TYPE = RVT,Unnamed: 17,Taxes & Fees,OTA TYPE = FTT
0,Double/Full Bed,1.0,NaN,Accessible Room,1.0,NaN,Piano,0,NaN,Adjoining rooms,1.0,NaN,All Inclusive,1.0,NaN,Airport view,1.0,NaN,Bed tax,1.0
1,Futon Bed,2.0,NaN,Suite,3.0,NaN,24-hour front desk,1,NaN,Air conditioning,2.0,NaN,Full Board or American,2.0,NaN,Bay view,2.0,NaN,City hotel fee,2.0
2,King Bed,3.0,NaN,Executive/Club Suite,6.0,NaN,24-hour room service,2,NaN,Alarm clock,3.0,NaN,Buffet Breakfast,4.0,NaN,City view,3.0,NaN,PropertyFee,2.0
3,Murphy Bed,4.0,NaN,Double Room,10.0,NaN,24-hour security,3,NaN,All news channel,4.0,NaN,Continental Breakfast,6.0,NaN,Courtyard view,4.0,NaN,City tax,3.0
4,Queen Bed,5.0,NaN,King Bedroom,11.0,NaN,adjoining rooms,4,NaN,radio,5.0,NaN,Family Plan,9.0,NaN,Golf View,5.0,NaN,Municipal Tax,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,NaN,NaN,NaN,NaN,NaN,NaN,Train station shuttle services,2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,NaN,NaN,NaN,NaN,NaN,NaN,Electric car charging stations,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,Golf clubs (equipments),2032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,NaN,NaN,NaN,NaN,NaN,NaN,Beach club,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,NaN,NaN,NaN,NaN,NaN,NaN,Theme park shuttle,2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:

room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()

In [4]:
# %%
# Preparing the Normalized Product Attribute data to be used for the prompt
bed_types = dataset_normalized_attributes['BedType'].dropna().unique()
bed_types_list = bed_types.tolist()
bed_types_str = ", ".join(bed_types_list)
bed_types_str

# %%
room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()
room_types_str = ", ".join(room_types_list)
room_types_str

# %%
rate_plan_inclusives_raw = dataset_normalized_attributes['Rateplan Incl/Value-adds'].dropna().unique()
rate_plan_inclusives = rate_plan_inclusives_raw.tolist()
rate_plan_inclusives_str = ", ".join(rate_plan_inclusives)
rate_plan_inclusives_str

# %%
room_amenities_raw = dataset_normalized_attributes['Room Amenities'].dropna().unique()
room_amenities_list = room_amenities_raw.tolist()
room_amenities_str = ", ".join(room_amenities_list)
room_amenities_str

# %%
meal_plan_raw = dataset_normalized_attributes['Mealplan'].dropna().unique()
meal_plan_list = meal_plan_raw.tolist()
meal_plan_str = ", ".join(meal_plan_list)
meal_plan_str

# %%
room_view_raw = dataset_normalized_attributes['RoomView'].dropna().unique()
room_view_list = room_view_raw.tolist()
room_view_str = ", ".join(room_view_list)
room_view_str

# %%
taxes_fees_raw = dataset_normalized_attributes['Taxes & Fees'].dropna().unique()
taxes_fees_list = taxes_fees_raw.tolist()
taxes_fees_str = ", ".join(taxes_fees_list)
taxes_fees_str

'Bed tax, City hotel fee, PropertyFee, City tax, Municipal Tax, County tax, Energy tax, Federal tax, Food & beverage tax, Lodging tax, Maintenance fee, Occupancy tax, HotelOccupancyTax, Package fee, Resort fee, ResortFee, Sales tax, Taxes, SalesTax, Service charge, ServiceFee, State tax, Province Tax, Surcharge, Total tax, Tourism tax, VAT/GST tax, Surplus Lines Tax, Insurance Premium Tax, Application Fee, Express Handling Fee, Exempt, Standard, Zero-rated, Miscellaneous, MandatoryTax, Room Tax, Tax, Early checkout fee, Country tax, Extra person charge, ExtraPersonFee, Banquet service fee, Room service fee, Local fee, Goods and services tax (GST), Value Added Tax (VAT), Crib fee, Rollaway fee, Assessment/license tax, Pet sanitation fee, Not known, Child rollaway charge, Convention tax, Extra child charge, Standard food and beverage gratuity, National government tax, Adult rollaway fee, Beverage with alcohol, Beverage without alcohol, Tobacco, Food, Total surcharges, TaxAndServiceFee, State cost recovery fee, Miscellaneous fee, Mandatory Fee, MandatoryFee, Destination amenity fee, Refundable pet fee, Property Fee, Tax Recovery Charges and Service Fees, Tax Recovery Charges'

In [5]:
dataset = pd.read_csv('../Data/Product_Normalization_GRI_Expanded.csv')
dataset.head()

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...

# Prompt Engineering #

## Gemini ##

In [7]:
import vertexai
from vertexai.generative_models import GenerativeModel

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [8]:
from vertexai.generative_models import (
    GenerativeModel,
    HarmCategory,
    HarmBlockThreshold,
    SafetySetting,
)

In [9]:
# Safety Settings
safety_config = [
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=HarmBlockThreshold.BLOCK_NONE,
    ),
    SafetySetting(
        category=HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=HarmBlockThreshold.BLOCK_NONE,
    ),
]

In [10]:
# Fetching the model
project_id = 'fluent-vortex-449308-f6' # Needs to be updated
model_name = 'gemini-1.5-flash-002'

In [11]:
# Initialize the Vertex AI client
vertexai.init(project = project_id, location = 'us-central1')
model = GenerativeModel(model_name = model_name)

## All attributes ##

In [58]:
examples = [
    """Text: IN THE ART OF NEW YORK|MADISON KING RM. 450 SQFT. MADISON AVE VIEWS LRGE MARBLE BATH SEP SHOWER. COMP WIFI
    JSON: {"roomType": "King Bedroom", "bedType": "Unknown", "ratePlanInclusives": ["Private bath or shower", "Complimentary wireless internet"], "roomAmenities": ["Separate tub and shower", "Wireless internet connection"], "mealPlan": "Unknown", "roomView": "Avenue View", "taxesAndFees": "Unknown"}""",

    """Text: AAA MEMBER RATE|ECO-FICIENT QUEEN ROOM RUNWAY VIEW. COMPLEMENTARY WIFI, IN ROOM COFFEE, IRON BOARD
    JSON: {"roomType": "Queen Bedroom", "bedType": "Unknown", "ratePlanInclusives": ["Eco Friendly", "Complimentary in-room coffee or tea", "Ironing board"], "roomAmenities": ["Wireless internet connection", "Ironing board"], "mealPlan": "Unknown", "roomView": "Runway View", "taxesAndFees": "Unknown"}"""
]

output_format = """
    JSON: {"roomType": "string", "bedType": "string", "ratePlanInclusives": ["string"], "roomAmenities": ["string"], "mealPlan": "string", "roomView": "string", "taxesAndFees": "string"}
"""

output_format_example = """
    JSON: {"roomType": "Queen Bedroom", "bedType": "King Bed", "ratePlanInclusives": {"values": ["Unknown"], "confidence": 0.85}, "roomAmenities": {"values": ["Wireless internet connection", "Ironing board"], "confidence": 0.85}, "mealPlan": {"value": "Unknown", "confidence": 0.8}, "roomView": {"value": "Ocean view", "confidence": 0.95}, "taxesAndFees": {"value": "Unknown", "confidence": 0.95}}
"""

In [54]:
# Function to prompt the model with a single text
def process_single_text(model, text, examples, output_format, output_format_example):
    # Preparing the prompt
    prompt = f"""
    Extract the following attributes from the text below:
    - Room Type
    - Bed Type
    - Rate Plan Inclusives
    - Room Amenities
    - Meal Plan
    - Room View
    - Taxes and Fees

    Format your response as a JSON object with these exact keys: {output_format}
    
    Here are two examples of correct extractions: {examples}   

    Now extract from this text: {text} 

    Extract room attributes using ONLY the following normalized values:
    Room Types: {room_types_str}
    Bed Types: {bed_types_str}
    Rate Plan Inclusives: {rate_plan_inclusives_str}
    Room Amenities: {room_amenities_str}
    Meal Plans: {meal_plan_str}
    Room Views: {room_view_str}
    Taxes and Fees: {taxes_fees_str}

    If no clear match exists, return 'Unknown'.

    Rules for extraction:
    1. Each room must have exactly one room type
    2. Each room must have at least one bed type
    3. Rate Plan Inclusives should be a list
    4. Meal Plan is optional
    5. View is optional
    6. Amenities should be a list
    7. Do not infer attributes that aren't explicitly mentioned

    Special cases to handle:
    - If multiple bed types are mentioned, list all of them
    - If amenities are described but not in our standard list, choose the closest match
    - Unclear if ambiguous.
    - Ignore pricing and promotional information

    For each extracted attribute, provide a confidence score, like below example: {output_format_example}
    
    Follow these steps:
    1. First, identify all mentioned attributes in the text
    2. Then, match each attribute to the closest normalized value
    3. Validate against the allowed values list
    4. Format the final output as JSON without escaping
    5. Explain your reasoning for any uncertain matches

    Show your work:
    Identified attributes: ...
    Normalized matches: ...
    Final output: ...
    Reasoning: ...
    Return the final result similar to the example, with no extra text.

    """
    response = model.generate_content(prompt, safety_settings=safety_config)
    return response

In [14]:
raw_text = dataset['Room Description Expanded'].to_list()
raw_text

['FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'BEST AVAILABLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'STANDARD RATE ACCESSIBLE 1BR KING TUB|ACCESSIBLE ONE BEDROOM KING SUITE WITH/ ACCESSIBLE BATHTUB',
 'STAY PARK FLY ACCESSIBLE 1BR KING TUB|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'FLEXIBLE RATE|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'DREAM AWAY|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'PRE/POST CRUISE ACCESSIBLE 1BR KING T|RATE COVERS DOUBLE OCCUPANCY. TRANSFERS TO',
 'TRIPADVISOR PLUS|ACCESSIBLE ROOM - AC-SITTING AREA-FREE WI-FI-DESK LG ROLL-IN SHOWER - INC CONT BREAKFAST',
 'FLEXIBLE RATE|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 '2X POINTS PACKAGE|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'SEMI-FLEX|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'PARK AND STAY AARP|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'SEMI-FLEX|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'FLEXIBLE RATE|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'TRIP ADVISOR|2QUEEN BEDS MINI FRIDGE 43 TV 318 SQ FT 5 PPL ACCESSIBLE ROOMS AVAIL UPON REQUEST COMP BOTTLED H20 BREAKFAST IN OUR RESTAURANT',
 'STANDARD RATE ACCESSIBLE KING SHR NSB|ACCESSIBLE KING ROOM WITH ACCESSIBLE SHOWER',
 'CANCELLATION POLICY: DAY OF AR|SUPERIOR ACCESSIBLE ROOM KING BED-350 SQFT-LUXURY BATH AMENITIES-FREE WIFI-MAX 2 PPL CANCELLATION POLICY: DAY OF ARRIVAL AT 4 PM EXEMPT FROM FACILITY FEE REVERE CLUB ACCESSIBLE',
 'SEMI-FLEX|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'CANCELLATION POLICY: DAY OF AR|SUPERIOR ACCESSIBLE ROOM 2 QUEEN BED-350 SQFT-LIVING SPACE-ROLL IN SHOWER-FREE WIFI-MAX 4 PPL CANCELLATION POLICY: DAY OF ARRIVAL AT 4 PM EXEMPT FROM FACILITY FEE REVERE CLUB ACCESSIBLE',
 'FLEXIBLE RATE|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'FLEXIBLE RATE|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'TRIPADVISOR PLUS RATE|MOBILITY ACCESSIBLE TWO QUEEN GULF VIEW ROOM FURNISHED BALCONY 15PCT OFF 20USD CREDIT DAILY WELCOME GIFT',
 'FLEXIBLE RATE|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'TRIP ADVISOR PLUS RATE|ACCESSIBLE DELUXE KING-CITY VIEW-1 KING-374SQFT- WIFI-ROLL IN SHOWER-LUXURY LINENS',
 'FLEXIBLE RATE|KING BED URBAN ROOM MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/CONTEMP DESIGN/55 IN TV/FRIDGE',
 'TRIP ADVISOR PLUS RATE|ACCESSIBLE DELUXE 2 QUEENS-CITY VIEW-2 QUEENS-495SQFT- WIFI-ROLL IN SHOWER-LUXURY LINENS',
 'BEST AVAILABLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'FLEXIBLE RATE|URBAN 2 DOUBLE HEARING ACCESSIBLE 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 '2X POINTS PACKAGE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'WYNDHAM REWARDS DOUBLE POINTS|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'SEMI-FLEX|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'FLEXIBLE RATE|URBAN 1 KING MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'BEST AVAILABLE RATE|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 '2X POINTS PACKAGE|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SEMI-FLEX|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'SEMI-FLEX|URBAN 2 DOUBLE HEARING ACCESSIBLE 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'AAA HOT DEALS|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'BEST AVAILABLE RATE FLEXIBLE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'PARK STAY FLY ACCESSIBLE KING SHR NSB|FREE LONGTERM PARKING FOR UP TO 14 NIGHTS',
 'SNOOZE   CRUISE ACCESSIBLE KING SHR N|TRANSPORTATION FROM TAMPA AIRPORT TO HOTEL',
 'PAY NOW SAVE NON-CX|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'AAA RATE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'SEMI-FLEX|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 '2X POINTS PACKAGE|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 'FLEXIBLE RATE|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 '2X POINTS|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'BREAKFAST INCLUDED|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'FAMILY FUN PACKAGE.|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 'SEMI-FLEX|URBAN 1 KING MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE KING SUITE WITH FULL SOFA SLEEPER 500 SQ FT - ACCESSIBLE SHOWER - GROUND FLOOR',
 'SENIOR DISCOUNT|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'AARP RATE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'JEAN GEORGES BED AND BREAKFAST|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'BEST AVAILABLE RATE|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'TRIPADVISOR PLUS RATE|2 ACCESSIBLE ROOMS KING BED FULL KITCHEN 1 QUEEN SLEEPER DINING AREA 2 BATHROOMS 15PCT OFF 20USD CREDIT DAILY WELCOME GIFT',
 'FLEXIBLE RATE|ACCESSIBLE SUPERIOR TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'CWT FREE WIFI FOR IHG REWARDS|MEMBERS. 10 IHG PTS PER 1 USD SPENT DESTINATION KING IC MOBILITY ACCESSIBLE ROLL IN SHWR MOBILITY ACCESSIBLE.  EXPECT MODERN ELEGANCE WHILE STAYING TRUE TO',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE KING SHOWER ONLY 1 KING BED ',
 'STAY PARK FLY ACCESSIBLE 2BR 2D1K SHW|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'STANDARD RATE ACCESSIBLE KING TUB NO SB|ACCESSIBLE KING ROOM WITH ACCESSIBLE BATHTUB',
 'FLEXIBLE RATE|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 '2X POINTS|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 'DREAM AWAY|KING BED URBAN ROOM MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/CONTEMP DESIGN/55 IN TV/FRIDGE',
 'FLEXIBLE RATE|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 '2X POINTS|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'BREAKFAST INCLUDED|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SUPERIOR TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'FLEXIBLE RATE|RESORT ACCESSIBLE KING, 1 KING BED MOBILITY ACCESSIBLE THROUGHOUT ROOM',
 'TRIPADVISOR PLUS|SPANISH KING ACCESSIBLE ROOM BRK FOR 2 AND PRKING NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 'FLEXIBLE RATE|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'TRIPADVISOR PLUS|1 KING BED NON SMOKING ACCESSIBLE ACCESSIBLE WITH ROLL-IN SHOWER',
 '2X POINTS PACKAGE|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|RESORT ACCESSIBLE TWO QUEEN, 2 QUEEN BEDS MOBILITY ACCESSIBLE THROUGHOUT ROOM',
 'PARK AND GO|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ BATHTUB VIS DOORBELL ALRT AND VIS PHONE ALRT',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 '2X POINTS PACKAGE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 'TRIPADVISOR PLUS|KING ACCESSIBLE ROOM WITH ROLL IN SHOWER NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 '2X POINTS|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ BATHTUB VIS DOORBELL ALRT AND VIS PHONE ALRT',
 'DINE AND UNWIND|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'FAMILY FUN PACKAGE.|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 'TRIPADVISOR PLUS RATE|1 QUEEN MOBILITY ACCESSIBLE ROOM, GENESEE BUILDING NON SMOKING WITH FREE WIFI, BATHTUB GRAB BARS',
 'BREAKFAST INCLUDED|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 'FLEXIBLE RATE|ACCESSIBLE SUPERIOR KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'FLEXIBLE RATE|RESORT ACCESSIBLE ROOM, 1 KING BED 510 SQ FT, MULTIPLE VIEWS, SAFETY BARS',
 'FLEXIBLE RATE|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 '2X POINTS PACKAGE|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'PARK AND STAY AAA|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'JP MORGAN CHASE AND COMP|WIFI. 6 PM CXL. 10 IHG PTS PER 1USD SPENT. KING IC MOBILITY ACCESSIBLE ROLL IN SHWR MOBILITY ACCESSIBLE.  EXPECT MODERN ELEGANCE WHILE STAYING TRUE TO',
 'SEMI-FLEX|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|2 DOUBLE BEDS MOBILITY ACCESSIBLE WITH/ BATHTUB 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 'CWT SMALLBIZ -24HR CXL LATE CK|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'OUR BEST AVAILABLE RATE|ACCESSIBLE 2 QUEENS APPROX 395 SQ FT - JULIET BALCONY ACCESSIBLE ROOM - WHEELCHAIR ACCESSIBLE BATH',
 '2X POINTS|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 'FLEXIBLE RATE|PARK MGM KING - 1 KING BED ACCESSIBLE 406 SQ FT, BEDSIDE OUTLETS, SAFETY BAR',
 'FLEXIBLE RATE|PARK ACC KING ROLL IN SHOWER, 1 KING BED 406 SQ FT, ROLL IN SHOWER, SAFETY BAR',
 'DAILY PARKING PKG PACKAGE|INCLUDES ROOM ACCOMMODATIONS AND PARKING FOR 1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP TO TWO ADULTS SHARING A 1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BEST FLEXIBLE RATE|1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'DAILY PARKING PKG PACKAGE|INCLUDES ROOM ACCOMMODATIONS AND PARKING FOR 1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP TO TWO ADULTS SHARING A 1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BEST FLEXIBLE RATE|1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'JP MORGAN CHASE -PREFERRED RAT|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ ROLL IN SHW VIS FIREALRM/DOOR/PHN ALRT',
 'AARP RATE|KING BED-ACCESSIBLE-NON-SMOKING -EXCLUSIVE RATE FOR AARP MEMBERS',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ RI SHWR VISUAL FIREALARM/DOOR/PHONE ALERT',
 'ADVANCE SAVER|1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SUPERIOR KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'ADVANCE SAVER|1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST, WIFI  PARKING|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 '2X POINTS|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ ROLL IN SHW VIS FIREALRM/DOOR/PHN ALRT',
 'BEST AVAILABLE RATE|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 '2X POINTS PACKAGE|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILABLE RATE|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 '2X POINTS PACKAGE|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'HOLIDAY WEEKEND PKG|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILABLE RATE WITH DINNE|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'AAA FLEXIBLE OFFER|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'HOLIDAY WEEKEND PKG|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SHOPPING AT CABELAS|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SHOPPING AT CABELAS|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILBALE RATE WITH BREAK|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'FLEXIBLE RATE|ACCESSIBLE CATHEDRAL VIEW KING - 360 SF OR 33 SM - SPACIOUS ACCESSIBLE COMPLIANT ROOM',
 'BEST AVAILABLE RATE|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'BOOKS FOR KIDS|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'CWT BUSINESS RATES|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'PRE/POST CRUISE ACCESSIBLE ST KING SH|RATE COVERS DOUBLE OCCUPANCY. TRANSFERS TO',
 'AAA RATE-ID REQUIRED|PARK MGM KING - 1 KING BED ACCESSIBLE 406 SQ FT, BEDSIDE OUTLETS, SAFETY BAR',
 'STAY PARK FLY ACCESSIBLE ST KING SHWR|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY/HEARING ACCESSIBLE WITHBATHTUB VIS FIRE ALARM/ DOOR/PHONE ALERT',
 'SAVE 10 PCT OFF ACCESSIBLE KING TUB|ACCESSIBLE KING ROOM WITHACCESSIBLE SHOWER AND TUB: SOFABED:',
 'TRIPADVISOR PLUS|CASA SURF ACESSIBLE ROOM NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 'CWT BUSINESS RATES|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'AAA FLEXIBLE OFFER|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'OUR BEST AVAILABLE RATE|ACCESSIBLE KING APPROX 395 SQFT - PATIO.JULIET OPTIONS ACCESSIBLE ROOM - WHEELCHAIR ACCESSIBLE BATH',
 'TRIPADVISOR PLUS|ACCESSIBLE 1 QUEEN BED- 17 SQM- QUEEN BED- AC- FREE WIFI- SHOWER- WORK DESK- HAIRDYER-',
 'STANDARD RATE ACCESSIBLE KING TUB|ACCESSIBLE KING ROOM WITHACCESSIBLE SHOWER AND TUB: SOFABED:',
 'CWT PROGRAM -HONORS SEMI-FLEX|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|ACCESSIBLE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'BEST FLEXIBLE RATE|HUDSON SQUARE KING ACCESSIBLE ROOM - URBAN VIEW 1 KING BED  - 430 SQF - 40 SQM',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE CATHEDRAL VIEW KING - 360 SF OR 33 SM - SPACIOUS ACCESSIBLE COMPLIANT ROOM',
 'STANDARD RATE ACCESSIBLE DOUBLE TUB NOSB|ACCESSIBLE DOUBLE ROOM WITH ACCESSIBLE BATHTUB',
 'FLEXIBLE RATE|1KG MOBILITY/HEARING ACCESSIBLE 3X3SHW NO SMOK VIS FIREALRM/DOOR/PHN ALRT',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE DOUBLE - ROLL-IN SHOWER - CITY VIEW 350 SQ.FT. FLAT SCREEN TV',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE KING LOFT SUITE -1 KING BED - 550 SQ.FT. LIVING ROOM - FLAT SCREEN TV - COTTON ROBES',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE KING -1 KING BED -350 SQ.FT. FLAT SCREEN TV-MAISON MARGIELA BATH AMENITIES',
 'PREFERRED SUITES|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'CWT BUSINESS RATES|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'WORLD RAINBOW BAR RATE|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'NO-AMENITY FEE-UP TO 10PCT OFF|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'SENIOR-AARP DISCOUNT|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'BEST AVAILABLE RATE *|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'STANDARD RATE 1 KNG ACCESSIBLE SHOWER|ACCESSIBLE 1 KING BED: ROLL IN SHOWER:OUTSIDE/ATRIUM',
 '2X POINTS PACKAGE|QUEEN ACCESSIBLE ROOM HDTV/WORK AREA/SOFA BED',
 'PARK STAY FLY ACCESSIBLE DOUBLE TUB NOSB|FREE LONGTERM PARKING FOR UP TO 14 NIGHTS',
 'SNOOZE   CRUISE ACCESSIBLE DOUBLE TUB NO|TRANSPORTATION FROM TAMPA AIRPORT TO HOTEL',
 'FLEXIBLE RATE|1 KNG WHRPL ROOM MOBILITY ACCESSIBLE WITHRI SHWR FIREPLACE-COMP WIFI-BED WITH/ ADJUST FIRM DIAL',

In [15]:
# Random Sampling 10 texts
import random
sample_texts = random.sample(raw_text, 10)
sample_texts

['ADVANCE SAVER|2 DOUBLE BEDS STANDARD NON SMOKING IN THIS CONTEMPORARY TWO DOUBLE BEDS GUEST ROOM GUESTS WILL ENJOY A SPACIOUS WARDROBE',
 'TRIPADVISOR PLUS RATE|KING ROOM 400 SQ FT PRIVATE PATIO ON 1ST FLOOR POOL SIDE NON SMOKING AVAILABLE IN 2 QUEEN',
 'BEST FLEXIBLE RATE|KING EXECUTIVE NONSMOKE ENRICH YOUR STAY TO THIS 330-357SQ FT EXECUTIVE LEVEL ROOM WITH PREMIUM VIEWS AND UPGRADED',
 'HONORS PREPAY AND SAVE|TWIN EXECUTIVE 30SQM/323SQ.FT',
 'EXPERIENCE BUS. PACK.|STAYCATION, INCLUDES MEALS IN FOOD AND BEVERAGE, SEE RATE DETAILS, KING ROOM, GUEST ROOM, 1 KING',
 'PREF EXTRAS GBT ANDAZ CABANA S|1 KING BED:750 SQ FT:PRIVATE POOLSIDE CABANA:',
 'FLEXIBLE RATE WITH BREAKFAST|LUXURY SUITE - 130 SQM - LAKE VIEW - KING BED - AIR CONDITIONING - MARBEL BATH',
 'PARKING PACKAGE RATE|SELF PARKING, SEE RATE DETAILS, JUNIOR SUITE, 2 DOUBLE',
 'REGULAR RATE|FLEXIBLE RATE, JUNIOR SUITE, 1 KING, ALTERNATE BED: SOFA BED, SOFA BED',
 'CWT PROGRAM -HONORS DREAM AWAY|2 QUEEN BEDS STUDIO SUITE NONSMOKING HDTV/FREE WI-FI/ REFRIGERATOR/ MICROWAVE']

In [7]:
sample_texts = ['ADVANCE SAVER|2 DOUBLE BEDS STANDARD NON SMOKING IN THIS CONTEMPORARY TWO DOUBLE BEDS GUEST ROOM GUESTS WILL ENJOY A SPACIOUS WARDROBE',
 'TRIPADVISOR PLUS RATE|KING ROOM 400 SQ FT PRIVATE PATIO ON 1ST FLOOR POOL SIDE NON SMOKING AVAILABLE IN 2 QUEEN',
 'BEST FLEXIBLE RATE|KING EXECUTIVE NONSMOKE ENRICH YOUR STAY TO THIS 330-357SQ FT EXECUTIVE LEVEL ROOM WITH PREMIUM VIEWS AND UPGRADED',
 'HONORS PREPAY AND SAVE|TWIN EXECUTIVE 30SQM/323SQ.FT',
 'EXPERIENCE BUS. PACK.|STAYCATION, INCLUDES MEALS IN FOOD AND BEVERAGE, SEE RATE DETAILS, KING ROOM, GUEST ROOM, 1 KING',
 'PREF EXTRAS GBT ANDAZ CABANA S|1 KING BED:750 SQ FT:PRIVATE POOLSIDE CABANA:',
 'FLEXIBLE RATE WITH BREAKFAST|LUXURY SUITE - 130 SQM - LAKE VIEW - KING BED - AIR CONDITIONING - MARBEL BATH',
 'PARKING PACKAGE RATE|SELF PARKING, SEE RATE DETAILS, JUNIOR SUITE, 2 DOUBLE',
 'REGULAR RATE|FLEXIBLE RATE, JUNIOR SUITE, 1 KING, ALTERNATE BED: SOFA BED, SOFA BED',
 'CWT PROGRAM -HONORS DREAM AWAY|2 QUEEN BEDS STUDIO SUITE NONSMOKING HDTV/FREE WI-FI/ REFRIGERATOR/ MICROWAVE']

In [83]:
# Random Sampling 100 texts
sample_texts_100 = dataset.sample(n = 100,random_state = 42)
sample_texts_100

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
13134,13134,VIRTUOSO 1BRM OCN VW POOL|ONE BEDROOM VILLA W/...,Villa,VIRTUOSO 1BRM OCEAN VIEW POOL|ONE BEDROOM VILL...
7794,7794,BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...,Twin Room,BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...
25853,25853,SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...,Presidential Suite,SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...
23704,23704,"MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...",Luxury Room,"MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K..."
19681,19681,CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...,Premier Room,CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...
...,...,...,...,...
2918,2918,LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM W ADA FE...,Double Bed,LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM WITH ACC...
14902,14902,TRIPADVISOR PLUS RATE|EXC 431SF ACCESS ROLLN S...,Executive/Club Room,TRIPADVISOR PLUS RATE|EXC 431SF ACCESSIBLE ROL...
30600,30600,STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE T...,Luxury Suite,STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE T...
6888,6888,2X POINTS|STUDIO SUITE - ONE KING BED SEATING ...,Studio Suite,2X POINTS|STUDIO SUITE - ONE KING BED SEATING ...
2900,2900,FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM ...,Double Bed,FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM ...

# Using a sample of 10 #

In [16]:

# Running for multiple input texts
# Process texts with the model in a loop
results_few = []
for text in sample_texts:
    try:
        result = process_single_text(model, text, examples,  output_format, output_format_example)
        results_few.append(result)
    except Exception as e:
        print(f"Error processing text: {text[:50]}...")
        print(f"Error: {str(e)}")
        results_few.append(None)

In [17]:
results_few

[candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Guest Room\",\n  \"bedType\": [\"Double/Full Bed\"],\n  \"ratePlanInclusives\": [\n    \"Non-smoking\"\n  ],\n  \"roomAmenities\": [\n    \"Spatious wardrobe\"\n  ],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.149035275
     severity: HARM_SEVERITY_LOW
     severity_score: 0.230919942
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0488576852
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.141281515
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.109705783
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.1968261
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0838904828
     severity: HARM_SEVERITY_LOW
     severity_score: 0.212068826
   }
   avg_logprobs: -0.0376016892884907
 }
 usage_metadata {
   prompt_token_count: 4307
   candidates_token_count: 95
   total_token_count: 4402
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\"roomType\": \"King Bedroom\", \"bedType\": [\"King Bed\", \"Queen Bed\"], \"ratePlanInclusives\": [\"Non-smoking\"], \"roomAmenities\": [\"Private bath or shower\"], \"mealPlan\": \"Unknown\", \"roomView\": \"Pool view\", \"taxesAndFees\": \"Unknown\"}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0618759878
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.178955987
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0440186746
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.166675612
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0534033142
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.146087155
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0826974213
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.120025486
   }
   avg_logprobs: -0.01943512303488595
 }
 usage_metadata {
   prompt_token_count: 4308
   candidates_token_count: 70
   total_token_count: 4378
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Executive/Club Room\",\n  \"bedType\": \"King Bed\",\n  \"ratePlanInclusives\": [\n    \"Premium Views\"\n  ],\n  \"roomAmenities\": [],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0980794281
     severity: HARM_SEVERITY_LOW
     severity_score: 0.203074887
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.043365851
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.109705783
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0705596507
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.193147466
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0758582428
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.141281515
   }
   avg_logprobs: -0.011466698277564276
 }
 usage_metadata {
   prompt_token_count: 4311
   candidates_token_count: 84
   total_token_count: 4395
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Twin Room\",\n  \"bedType\": \"Twin/Single Bed\",\n  \"ratePlanInclusives\": [\n    \"Unknown\"\n  ],\n  \"roomAmenities\": [],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.086323753
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.193147466
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0373269245
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.109705783
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0646535307
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.162380099
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0980794281
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.175538197
   }
   avg_logprobs: -0.0042806666299521207
 }
 usage_metadata {
   prompt_token_count: 4297
   candidates_token_count: 83
   total_token_count: 4380
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"King Bedroom\",\n  \"bedType\": \"King Bed\",\n  \"ratePlanInclusives\": [\n    \"Meals included in food and beverage\"\n  ],\n  \"roomAmenities\": [],\n  \"mealPlan\": \"All Inclusive\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0888204128
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.19193311
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0384663157
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.119203046
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0736965165
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.165593475
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0780783668
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.142232075
   }
   avg_logprobs: -0.02252463225660653
 }
 usage_metadata {
   prompt_token_count: 4307
   candidates_token_count: 87
   total_token_count: 4394
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Cabana\",\n  \"bedType\": [\"King Bed\"],\n  \"ratePlanInclusives\": [\"Private pool\"],\n  \"roomAmenities\": [],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0926875919
     severity: HARM_SEVERITY_LOW
     severity_score: 0.201813355
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0460338742
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.115960866
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0609752387
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.182425365
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0618759878
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.158174783
   }
   avg_logprobs: -0.0053226414479707416
 }
 usage_metadata {
   prompt_token_count: 4302
   candidates_token_count: 76
   total_token_count: 4378
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Luxury Suite\",\n  \"bedType\": \"King Bed\",\n  \"ratePlanInclusives\": [\"Breakfast\", \"Air conditioning\"],\n  \"roomAmenities\": [\"Air conditioning\", \"Marble bathroom\"],\n  \"mealPlan\": \"Breakfast\",\n  \"roomView\": \"Lake view\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0850991607
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.169955954
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0408457257
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.102304742
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0583459213
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.165593475
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0758582428
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.115960866
   }
   avg_logprobs: -0.034778647039128446
 }
 usage_metadata {
   prompt_token_count: 4306
   candidates_token_count: 87
   total_token_count: 4393
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Junior Suite\",\n  \"bedType\": [\"Double/Full Bed\"],\n  \"ratePlanInclusives\": [\"Parking\"],\n  \"roomAmenities\": [],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0838904828
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.156104967
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0346188694
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.09401007
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0695418268
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.190724373
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0780783668
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.141281515
   }
   avg_logprobs: -0.0034748114548720324
 }
 usage_metadata {
   prompt_token_count: 4292
   candidates_token_count: 77
   total_token_count: 4369
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Junior Suite\",\n  \"bedType\": [\"King Bed\", \"Sofa Bed\"],\n  \"ratePlanInclusives\": [\"Unknown\"],\n  \"roomAmenities\": [\"Unknown\"],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.0900932476
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.173288032
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0378925279
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.105210766
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0736965165
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.195593983
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.060086742
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.132964358
   }
   avg_logprobs: -0.0036935158717779464
 }
 usage_metadata {
   prompt_token_count: 4300
   candidates_token_count: 81
   total_token_count: 4381
 }
 model_version: "gemini-1.5-flash-002",
 candidates {
   content {
     role: "model"
     parts {
       text: "```json\n{\n  \"roomType\": \"Studio Suite\",\n  \"bedType\": [\"Queen Bed\"],\n  \"ratePlanInclusives\": [\n    \"Free WIFI\",\n    \"Refrigerator\",\n    \"Microwave\"\n  ],\n  \"roomAmenities\": [\n    \"Wireless internet connection\",\n    \"Refrigerator\",\n    \"Microwave\",\n    \"HDTV\"\n  ],\n  \"mealPlan\": \"Unknown\",\n  \"roomView\": \"Unknown\",\n  \"taxesAndFees\": \"Unknown\"\n}\n```\n"
     }
   }
   finish_reason: STOP
   safety_ratings {
     category: HARM_CATEGORY_HATE_SPEECH
     probability: NEGLIGIBLE
     probability_score: 0.109705783
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.195593983
   }
   safety_ratings {
     category: HARM_CATEGORY_DANGEROUS_CONTENT
     probability: NEGLIGIBLE
     probability_score: 0.0558232591
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.146087155
   }
   safety_ratings {
     category: HARM_CATEGORY_HARASSMENT
     probability: NEGLIGIBLE
     probability_score: 0.0900932476
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.155078605
   }
   safety_ratings {
     category: HARM_CATEGORY_SEXUALLY_EXPLICIT
     probability: NEGLIGIBLE
     probability_score: 0.0792102143
     severity: HARM_SEVERITY_NEGLIGIBLE
     severity_score: 0.195593983
   }
   avg_logprobs: -0.01067823072274526
 }
 usage_metadata {
   prompt_token_count: 4307
   candidates_token_count: 120
   total_token_count: 4427
 }
 model_version: "gemini-1.5-flash-002"]

In [18]:
import json
with open('promptengg_gemini_all_attributes.json', 'w') as file:
    for res in results_few:
        json.dump(res.text, file, indent=4)

# Using a sample of 100 #

In [59]:
# create an empty column first
sample_texts_100['gemini_otherattr_result'] = None

# iterate with .items() to get index and text
for idx, text in sample_texts_100['Room Description Expanded'].items():
    try:
        result = process_single_text(model, text, examples,  output_format, output_format_example)
    except Exception as e:
        print(f"Error processing text at index {idx}: {text[:50]}…")
        print(f"Error: {e}")
        result = None

    # write it back into the DataFrame
    sample_texts_100.loc[idx, 'gemini_otherattr_result'] = result

# now each row in sample_texts_100 has its own result
print(sample_texts_100[['Room Description Expanded', 'gemini_otherattr_result']].head())

Error processing text at index 16135: REGULAR RATE|FLEXIBLE RATE, CLASSIC, GUEST ROOM, 1…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 11448: AAA WEEKDAY|AAA CAA RATE, MEMBERSHIP CARD REQUIRED…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30265: MRATE AVAIL FLEXIBLE RATE|THE HOTEL DOES NOT ACCEP…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26175: SAVE 15 PCT OFF PRESIDENTIAL S|PRESIDENTIAL SUITE:…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26277: WIN|REFURBISHED SUPERIOR SINGLE ROOM WITH AC SINGL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 18254: BOOK NOW, PAY LATER|1 KING BED DELUXE SUITE NON SM…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 896: DINE AND UNWIND|1 KING MOBILITY ACCESSIBLE WITHROL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 24725: READY.SET.TRAVEL|CLASSIC SUITE  ONE BEDROOM KING  …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 21880: CWT|SUPERIOR SUITE ENJOY 1,200 SQ. FT. OF PURE LUX…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 15286: FLEXIBLE RATE|1 KING EXECUTIVE FLOOR SHOWER ONLY C…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 22509: SENIOR DISCOUNT|1 KING BED SUPERIOR SUITE WEST BUI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 21134: BED AND BREAKFAST|SUPERIOR ROOM-1 KING BED-CITY VI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26398: DINNER BED AND BKFST FULLY|FLEXIBLE RATE INCLUDES …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 210: BEST AVAILABLE RATE FLEXIBLE|2 QUEEN ACCESSIBLE RO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 15746: BED AND BREAKFAST|GRAND CLASSIC KING-450SQFT-BACCA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 27980: BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14704: FLEXIBLE RATE|2 QUEEN BEDS EXECUTIVE 1 BEDROOM SUI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 20525: BEST AVAILABLE RATE|STANDARD ROOM-ACCESSIBLE-1K-NO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 9300: BEST AVAILABLE RATE|TWO BEDROOM COTTAGE - 720 SQ F…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4341: AAA SPECIAL|BRONZE KING ROOM-1 KING BED-250 SQ FT-…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26812: EXXONMOBIL|ECONOMY PETITE SINGLE ROOM 1 TWIN BED 9…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 11285: MEMBR PREPAY NONREF|SEE RATE DETAILS, CITY VIEW, G…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 491: STANDARD RATE|KING BED-ACCESSIBLE-NON-SMOKING…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25613: BEST FLEXIBLE RATE|1 KING BED PRESIDENTIAL SUITE N…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 22389: BEST AVAILABLE RATE|SUPERIOR SUITE PARTIAL OCEAN V…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 12384: CORPORATE RATE|BUNGALOW QUEEN ROOM…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6528: REGULAR RATE|FLEXIBLE RATE, STUDIO SUITE, STUDIO, …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30791: BCD TRAVEL|1 KING OR 2 QUEEN WHEN YOU ARRIVE, WE W…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 16338: REGULAR RATE - RO -|COMFORT ROOM WITH TWIN BEDS, 2…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26894: MASTERCARD OFFER|SINGLE ROOM PREMIUM 20 SQM QUEEN …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6081: STAY MORE GET 15-20 PCT DISC|TRIPLEX PENTHOUSE-2BA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 23964: BED AND BREAKFAST PKG|BED AND BREAKFAST WITH PARKI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25057: RADIUS BY HOTELREZ ROOM ONLY|CLASSIC SUITE ENSUITE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 96: FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ R…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 9375: COMPLIMENTARY DINING|ORANGE OCEAN VIEW COTTAGE 2BD…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 10337: AAA MEMBERSHIP RATE|DOUBLE LOFT SUITE-2 DOUBLE BED…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 23884: INTERNOVA  TRAVEL LEADERS|LUXURY ROOM, 2 SINGLE BE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 17556: SIGNATURE TRAVEL NETWORK RATE|DELUXE KING ROOM, 1 …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 13677: LUXURY GETAWAY AND VALET|JUNIOR SUITE-ACCESSIBLE-N…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 3752: EAT. DRINK. OUR TREAT|CITY VIEW KING ROOM - FREE W…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 1427: BEST AVAILABLE RATE|PLATINUM SUITE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 733: BED AND BRKFST* 1 KNG ACCESSIBLE SHOW|ACCESSIBLE 1…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6427: WORLD RAINBOW BAR RATE|JUNIOR STUDIO SUITE APPROX …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 8439: SEMI-FLEX|3 BEDS - 1 KING 2 QUEEN FAMILY SUITE NON…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 18273: AAA RATE|DELUXE SUITE WITH 1 KING BED AND QUEEN SO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25479: CWT BUSINESS RATES|GRAND PRESIDENTIAL SUITE.3035 S…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4168: REGULAR RATE|FLEXIBLE RATE, PREPAY IN FULL, LAGOON…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4894: CWT PROGRAM -HONORS DISCOUNT|QUEEN ROOM FREE WI-FI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 27048: MRATE AVAIL BOOK WITH CONFIDEN|SUPERIOR SINGLE ROO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 28360: MAGELLAN LUXURY HOTELS|CABANA KING 300SQFT-POOL-IN…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 1330: FLEXIBLE RATE|HASTENS ULTIMATE SLEEP SUITE - 2500 …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14928: WELCOME BACK SALE|EXECUTIVE 2 TWINS, NON SMOKING, …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 8517: MRATE AVAIL FLEXIBLE RATE|FAMILY ROOM WITH 1 DOUBL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 20959: SEASONAL RATE|SUPERIOR ROOM-1KING-CITY VIEW-LEDTV …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 16203: RESTRICTED RATE|CLASSIC KING ROOM  ISLAND VIEW 1 P…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 24688: ADVANCE PURCHASE|HOYT HOUSE CLASSIC SUITE-375SQFT-…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 2918: LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM WITH ACCESSI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14902: TRIPADVISOR PLUS RATE|EXC 431SF ACCESSIBLE ROLLN S…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30600: STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE TOWER…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6888: 2X POINTS|STUDIO SUITE - ONE KING BED SEATING AREA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 2900: FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM FREE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
                               Room Description Expanded  \
13134  VIRTUOSO 1BRM OCEAN VIEW POOL|ONE BEDROOM VILL...
7794   BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...
25853  SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...
23704  MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...
19681  CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...

                                 gemini_otherattr_result
13134  candidates {\n  content {\n    role: "model"\n...
7794   candidates {\n  content {\n    role: "model"\n...
25853  candidates {\n  content {\n    role: "model"\n...
23704  candidates {\n  content {\n    role: "model"\n...
19681  candidates {\n  content {\n    role: "model"\n...

In [66]:
sample_texts_100['gemini_otherattr_result'].iloc[1].text.split(',')

['```json\n{\n  "roomType": "Twin Room"',
 '\n  "bedType": ["Twin/Single Bed"]',
 '\n  "ratePlanInclusives": ["Unknown"]',
 '\n  "roomAmenities": ["Unknown"]',
 '\n  "mealPlan": "Unknown"',
 '\n  "roomView": "Unknown"',
 '\n  "taxesAndFees": "Unknown"\n}\n```\n']

In [71]:
import json
import pandas as pd

def extract_attributes(text: str) -> dict:
    """
    1) Finds the first “{” and last “}” in the text and slices it out.
    2) Attempts to json.loads() that substring.
    3) Flattens any list-valued entries into comma-joined strings.
    """
    try:
        # isolate just the JSON
        start = text.index("{")
        end   = text.rindex("}") + 1
        json_blob = text[start:end]
        data = json.loads(json_blob)
    except (ValueError, json.JSONDecodeError):
        # fallback to regex if JSON is malformed
        import re
        pattern = r'"(\w+)":\s*(\[[^\]]*\]|"[^"]*")'
        data = {}
        for key, raw in re.findall(pattern, text):
            if raw.startswith("["):
                items = json.loads(raw)
                data[key] = ", ".join(items)
            else:
                data[key] = raw.strip('"')
    # flatten lists to strings
    for k, v in data.items():
        if isinstance(v, list):
            data[k] = ", ".join(v)
    return data

# 1) apply to your column to get a dict per row
sample_texts_100["attrs"] = (
    sample_texts_100["gemini_otherattr_result"]
      .apply(lambda r: extract_attributes(r.text) if r is not None else {})
)

# 2) expand the dicts into their own columns
attrs_df = sample_texts_100["attrs"].apply(pd.Series)

# 3) concat back onto your original df
sample_texts_100 = pd.concat([sample_texts_100, attrs_df], axis=1)

# now you have columns like:
#   roomType, bedType, ratePlanInclusives, roomAmenities, mealPlan, …
print(sample_texts_100[[
    "roomType","bedType","ratePlanInclusives","roomAmenities","mealPlan"
]].head())

                 roomType               bedType  \
13134               Villa               Unknown
7794            Twin Room       Twin/Single Bed
25853  Presidential Suite              King Bed
23704         Luxury Room  King Bed, Single Bed
19681        Premier Room              King Bed

                    ratePlanInclusives         roomAmenities mealPlan
13134                 Ocean view, Pool  Balcony, Plunge pool  Unknown
7794                           Unknown               Unknown  Unknown
25853                        Free WIFI                        Unknown
23704                          Unknown               Unknown  Unknown
19681  Complimentary wireless internet          Sitting area  Unknown

In [73]:
sample_texts_100.to_csv('promptengg_gemini_all_attributes_100samples.csv')

## Room Type ##

In [ ]:
# Fetching the model
project_id = 'fluent-vortex-449308-f6'
model_name = 'gemini-1.5-flash-002'

In [20]:
# Initialize the Vertex AI client
vertexai.init(project = project_id, location = 'us-central1')
model = GenerativeModel(model_name = model_name)

In [16]:
# Examples and output format
examples = [
    """Text: IN THE ART OF NEW YORK|MADISON KING RM. 450 SQFT. MADISON AVE VIEWS LRGE MARBLE BATH SEP SHOWER. COMP WIFI
    JSON: {"roomType": "King Bedroom", "confidence": 0.82}""",

    """Text: AAA MEMBER RATE|ECO-FICIENT QUEEN ROOM RUNWAY VIEW. COMPLEMENTARY WIFI, IN ROOM COFFEE, IRON BOARD
    JSON: {"roomType": "Queen Bedroom", "confidence": 0.95}"""
]

output_format = """
    JSON: {"roomType": "string", "confidence": float}
"""

In [17]:

# Function to prompt the model with a single text
def process_single_text(model, text, examples,  output_format):
    # Preparing the prompt
    prompt = f"""
    Extract "Room Type" attribute from the TEXT below, along with a confidence score:
    Follow these steps:
    1. First, remember all the room types in the normalized list: {room_types_str}
    2. For TEXT, observe carefully and identify which is the closest normalized value.
    3. Validate against the allowed values list.
    4. When it is ambiguous, return the most likely room type and low confidence score accordingly.
    5. Very rarely there might be two room types during which case return both room types with appropriate confidence scores.
    6. If no match is found, return 'Unknown' and very low confidence score.
    7. Format the final output as plain text with roomType and confidence parameters separated by commas.
    
    Now extract from this TEXT: {text}

    """

    response = model.generate_content(prompt)
    return response

In [23]:
# Running for multiple input texts
# Process texts with the model in a loop
gemini_roomtype_results = []
for text in sample_texts:
    try:
        result = process_single_text(model, text, examples,  output_format)
        gemini_roomtype_results.append(result)
    except Exception as e:
        print(f"Error processing text: {text[:50]}...")
        print(f"Error: {str(e)}")
        gemini_roomtype_results.append(None)

In [24]:
# Saving input
with open('promptengg_gemini_roomtype.json', 'w') as file:
    for res in gemini_roomtype_results:
        file.write(res.text)

In [26]:
for res in gemini_roomtype_results:
    print(res.text)

Double Room,0.8

King Bedroom,0.95

Executive/Club Room,0.8

Twin Room,0.8

King Room,0.8

Cabana,0.95

Luxury Suite,0.95

JUNIOR SUITE,0.95

Junior Suite,1.0

Studio Suite,0.95

In [27]:
sample_texts_100[['Room Description Expanded', 'Guest Room Info']]

                               Room Description Expanded      Guest Room Info
13134  VIRTUOSO 1BRM OCEAN VIEW POOL|ONE BEDROOM VILL...                Villa
7794   BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...            Twin Room
25853  SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...   Presidential Suite
23704  MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...          Luxury Room
19681  CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...         Premier Room
...                                                  ...                  ...
2918   LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM WITH ACC...           Double Bed
14902  TRIPADVISOR PLUS RATE|EXC 431SF ACCESSIBLE ROL...  Executive/Club Room
30600  STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE T...         Luxury Suite
6888   2X POINTS|STUDIO SUITE - ONE KING BED SEATING ...         Studio Suite
2900   FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM ...           Double Bed

[100 rows x 2 columns]

In [32]:
# create an empty column first
sample_texts_100['gemini_roomtype_result'] = None

# iterate with .items() to get index and text
for idx, text in sample_texts_100['Room Description Expanded'].items():
    try:
        result = process_single_text(model, text, examples, output_format)
    except Exception as e:
        print(f"Error processing text at index {idx}: {text[:50]}…")
        print(f"Error: {e}")
        result = None


    # write it back into the DataFrame
    sample_texts_100.loc[idx, 'gemini_roomtype_result'] = result

# now each row in sample_texts_100 has its own result
print(sample_texts_100[['Room Description Expanded', 'gemini_roomtype_result']].head())

Python(377) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Error processing text at index 16135: REGULAR RATE|FLEXIBLE RATE, CLASSIC, GUEST ROOM, 1…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 11448: AAA WEEKDAY|AAA CAA RATE, MEMBERSHIP CARD REQUIRED…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30265: MRATE AVAIL FLEXIBLE RATE|THE HOTEL DOES NOT ACCEP…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26175: SAVE 15 PCT OFF PRESIDENTIAL S|PRESIDENTIAL SUITE:…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26277: WIN|REFURBISHED SUPERIOR SINGLE ROOM WITH AC SINGL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 18254: BOOK NOW, PAY LATER|1 KING BED DELUXE SUITE NON SM…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 896: DINE AND UNWIND|1 KING MOBILITY ACCESSIBLE WITHROL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 24725: READY.SET.TRAVEL|CLASSIC SUITE  ONE BEDROOM KING  …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 21880: CWT|SUPERIOR SUITE ENJOY 1,200 SQ. FT. OF PURE LUX…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 15286: FLEXIBLE RATE|1 KING EXECUTIVE FLOOR SHOWER ONLY C…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 22509: SENIOR DISCOUNT|1 KING BED SUPERIOR SUITE WEST BUI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 21134: BED AND BREAKFAST|SUPERIOR ROOM-1 KING BED-CITY VI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26398: DINNER BED AND BKFST FULLY|FLEXIBLE RATE INCLUDES …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 210: BEST AVAILABLE RATE FLEXIBLE|2 QUEEN ACCESSIBLE RO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 15746: BED AND BREAKFAST|GRAND CLASSIC KING-450SQFT-BACCA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 27980: BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14704: FLEXIBLE RATE|2 QUEEN BEDS EXECUTIVE 1 BEDROOM SUI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 20525: BEST AVAILABLE RATE|STANDARD ROOM-ACCESSIBLE-1K-NO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 9300: BEST AVAILABLE RATE|TWO BEDROOM COTTAGE - 720 SQ F…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4341: AAA SPECIAL|BRONZE KING ROOM-1 KING BED-250 SQ FT-…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26812: EXXONMOBIL|ECONOMY PETITE SINGLE ROOM 1 TWIN BED 9…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 11285: MEMBR PREPAY NONREF|SEE RATE DETAILS, CITY VIEW, G…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 491: STANDARD RATE|KING BED-ACCESSIBLE-NON-SMOKING…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25613: BEST FLEXIBLE RATE|1 KING BED PRESIDENTIAL SUITE N…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 22389: BEST AVAILABLE RATE|SUPERIOR SUITE PARTIAL OCEAN V…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 12384: CORPORATE RATE|BUNGALOW QUEEN ROOM…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6528: REGULAR RATE|FLEXIBLE RATE, STUDIO SUITE, STUDIO, …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30791: BCD TRAVEL|1 KING OR 2 QUEEN WHEN YOU ARRIVE, WE W…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 16338: REGULAR RATE - RO -|COMFORT ROOM WITH TWIN BEDS, 2…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 26894: MASTERCARD OFFER|SINGLE ROOM PREMIUM 20 SQM QUEEN …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6081: STAY MORE GET 15-20 PCT DISC|TRIPLEX PENTHOUSE-2BA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 23964: BED AND BREAKFAST PKG|BED AND BREAKFAST WITH PARKI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25057: RADIUS BY HOTELREZ ROOM ONLY|CLASSIC SUITE ENSUITE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 96: FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ R…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 9375: COMPLIMENTARY DINING|ORANGE OCEAN VIEW COTTAGE 2BD…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 10337: AAA MEMBERSHIP RATE|DOUBLE LOFT SUITE-2 DOUBLE BED…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 23884: INTERNOVA  TRAVEL LEADERS|LUXURY ROOM, 2 SINGLE BE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 17556: SIGNATURE TRAVEL NETWORK RATE|DELUXE KING ROOM, 1 …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 13677: LUXURY GETAWAY AND VALET|JUNIOR SUITE-ACCESSIBLE-N…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 3752: EAT. DRINK. OUR TREAT|CITY VIEW KING ROOM - FREE W…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 1427: BEST AVAILABLE RATE|PLATINUM SUITE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 733: BED AND BRKFST* 1 KNG ACCESSIBLE SHOW|ACCESSIBLE 1…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6427: WORLD RAINBOW BAR RATE|JUNIOR STUDIO SUITE APPROX …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 8439: SEMI-FLEX|3 BEDS - 1 KING 2 QUEEN FAMILY SUITE NON…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 18273: AAA RATE|DELUXE SUITE WITH 1 KING BED AND QUEEN SO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 25479: CWT BUSINESS RATES|GRAND PRESIDENTIAL SUITE.3035 S…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4168: REGULAR RATE|FLEXIBLE RATE, PREPAY IN FULL, LAGOON…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 4894: CWT PROGRAM -HONORS DISCOUNT|QUEEN ROOM FREE WI-FI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 27048: MRATE AVAIL BOOK WITH CONFIDEN|SUPERIOR SINGLE ROO…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 28360: MAGELLAN LUXURY HOTELS|CABANA KING 300SQFT-POOL-IN…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 1330: FLEXIBLE RATE|HASTENS ULTIMATE SLEEP SUITE - 2500 …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14928: WELCOME BACK SALE|EXECUTIVE 2 TWINS, NON SMOKING, …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 8517: MRATE AVAIL FLEXIBLE RATE|FAMILY ROOM WITH 1 DOUBL…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 20959: SEASONAL RATE|SUPERIOR ROOM-1KING-CITY VIEW-LEDTV …
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 16203: RESTRICTED RATE|CLASSIC KING ROOM  ISLAND VIEW 1 P…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 24688: ADVANCE PURCHASE|HOYT HOUSE CLASSIC SUITE-375SQFT-…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 2918: LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM WITH ACCESSI…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 14902: TRIPADVISOR PLUS RATE|EXC 431SF ACCESSIBLE ROLLN S…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 30600: STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE TOWER…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 6888: 2X POINTS|STUDIO SUITE - ONE KING BED SEATING AREA…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
Error processing text at index 2900: FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM FREE…
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.
                               Room Description Expanded  \
13134  VIRTUOSO 1BRM OCEAN VIEW POOL|ONE BEDROOM VILL...
7794   BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...
25853  SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...
23704  MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...
19681  CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...

                                  gemini_roomtype_result
13134  candidates {\n  content {\n    role: "model"\n...
7794   candidates {\n  content {\n    role: "model"\n...
25853  candidates {\n  content {\n    role: "model"\n...
23704  candidates {\n  content {\n    role: "model"\n...
19681  candidates {\n  content {\n    role: "model"\n...

In [50]:
for res in sample_texts_100['gemini_roomtype_result']:
    res1 = res.text
    res = res1

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded,gemini_roomtype_result
13134,13134,VIRTUOSO 1BRM OCN VW POOL|ONE BEDROOM VILLA W/...,Villa,VIRTUOSO 1BRM OCEAN VIEW POOL|ONE BEDROOM VILL...,"candidates {\n content {\n role: ""model""\n..."
7794,7794,BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...,Twin Room,BRITISH TELECOMMUNI-NEGOTIATED|TWIN ROOM WITH ...,"candidates {\n content {\n role: ""model""\n..."
25853,25853,SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...,Presidential Suite,SEATTLE SPA ESCAPE|PRESIDENTIAL SUITE KING-10T...,"candidates {\n content {\n role: ""model""\n..."
23704,23704,"MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...",Luxury Room,"MRATE AVAIL SAVOR, THE FRENCH|LUXURY ROOM, 1 K...","candidates {\n content {\n role: ""model""\n..."
19681,19681,CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...,Premier Room,CELEBRATE IN CHARLESTON|CLUB PREMIER ROOM-1KIN...,"candidates {\n content {\n role: ""model""\n..."
...,...,...,...,...,...
2918,2918,LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM W ADA FE...,Double Bed,LIVE LIKE A LOCAL|CAPITOL DOUBLE ROOM WITH ACC...,None
14902,14902,TRIPADVISOR PLUS RATE|EXC 431SF ACCESS ROLLN S...,Executive/Club Room,TRIPADVISOR PLUS RATE|EXC 431SF ACCESSIBLE ROL...,None
30600,30600,STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE T...,Luxury Suite,STATE GOVERNMENT|KING LUXURY SUITE EXECUTIVE T...,None
6888,6888,2X POINTS|STUDIO SUITE - ONE KING BED SEATING ...,Studio Suite,2X POINTS|STUDIO SUITE - ONE KING BED SEATING ...,None
2900,2900,FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM ...,Double Bed,FLEXIBLE -WITH BREAKFAST|SUPERIOR DOUBLE ROOM ...,None

In [53]:
# 1) Pull the .text field out, but only keep what comes before the first comma
sample_texts_100['pred_text'] = (sample_texts_100['gemini_roomtype_result'].apply(lambda res: res.text.split(',')[0].strip() if res is not None else None))
# 2) Create a Boolean “match” column
sample_texts_100['match'] = (
    sample_texts_100['pred_text'] == sample_texts_100['Guest Room Info']
)

# 3) Compute overall accuracy (fraction of True’s, ignoring rows where pred_text is None)
valid = sample_texts_100['pred_text'].notna()
accuracy = sample_texts_100.loc[valid, 'match'].mean()

print(f"Overall accuracy: {accuracy:.2%}")

Overall accuracy: 87.18%

In [52]:
sample_texts_100['gemini_roomtype_result'].apply(lambda res: res.text if res is not None else None)

13134                Villa,0.95\n
7794             Twin Room,0.95\n
25853    Presidential Suite,1.0\n
23704          Luxury Room,0.95\n
19681         Premier Room,0.95\n
                   ...
2918                         None
14902                        None
30600                        None
6888                         None
2900                         None
Name: gemini_roomtype_result, Length: 100, dtype: object

## LLAMA 1B ##

In [6]:
#%% Importing libraries
import transformers
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
import os
import pandas as pd
import random

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
# Authenticating with Hugging Face (The other option is Terminal Login)
os.environ['HF_TOKEN'] = ''

In [52]:
# Examples

example_input = [
    """Text: IN THE ART OF NEW YORK|MADISON KING RM. 450 SQFT. MADISON AVE VIEWS LRGE MARBLE BATH SEP SHOWER. COMP WIFI""",
]

output_format = """
    JSON: {"roomType": "string", "confidence": float}
"""

example_output = """
    JSON: {"roomType": "King Bedroom", "confidence": 0.8}
"""

In [71]:
def setup_llama_pipeline():
    model_id = "meta-llama/Llama-3.2-1B-Instruct"
    
    print(f"Loading model {model_id}...")
    
    device = torch.device("cpu")
    print(f"Using device: {device}")
    
    # Load tokenizer first
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    print("Tokenizer loaded successfully")
    
    # Set pad token explicitly
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        print("Set pad_token to eos_token")
    
    # Load model with explicit parameters
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float16,
        device_map={"": device},
        low_cpu_mem_usage=True
    )
    
    print("Model loaded successfully")
    
    # Test the model with proper attention mask
    test_prompt = "<s>[INST] What is 2+2? [/INST]</s>"
    inputs = tokenizer(test_prompt, return_tensors="pt", padding=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    
    # Generate with explicit attention mask
    test_output = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=20,
        temperature=0.1,
        pad_token_id=tokenizer.pad_token_id
    )
    
    test_response = tokenizer.decode(test_output[0], skip_special_tokens=True)
    print(f"Test response: {test_response}")
    
    # Create pipeline with explicit parameters
    pipeline = transformers.pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        device_map={"": device},
        pad_token_id=tokenizer.pad_token_id
    )
    
    return pipeline, tokenizer

In [72]:
import re

def process_single_text(text, pipeline, tokenizer, examples, room_types_str):
    # Use a more explicit prompt format
    prompt = f"""<s>[INST] <<SYS>>
You are a precise text extractor. Your response must contain only one JSON object and no extra text.
<</SYS>>

Extract the room type from this text: {text}

Choose from these room types only: {room_types_str}

Return ONLY a JSON object with roomType and confidence score.

Example input: {example_input}
Example output: {example_output}
 [/INST]</s>"""
    
    print(f"Sending prompt: {prompt[:100]}...")
    
    # Generate with explicit parameters
    inputs = tokenizer(prompt, return_tensors="pt", padding=True)
    inputs = {k: v.to(pipeline.device) for k, v in inputs.items()}
    
    outputs = pipeline(
        prompt,
        max_new_tokens=128,
        temperature=0.1,
        top_p=0.95,
        top_k=40,
        num_return_sequences=1,
        do_sample=True,
        pad_token_id=tokenizer.pad_token_id,
        return_full_text=False,
        repetition_penalty=1.0
    )
    
    # Extract response
    response_text = outputs[0]['generated_text']
    print(f"Raw response: {response_text}")
    
    # Try to parse JSON from response
    try:
        # Find JSON in response
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            result = json.loads(json_str)
            return result
        else:
            return {"roomType": "Unknown", "confidence": 0.0}
    except (json.JSONDecodeError, AttributeError) as e:
        print(f"Error parsing JSON: {e}")
        return {"roomType": "Unknown", "confidence": 0.0}

In [73]:
# Running for 1 input
pipeline, tokenizer = setup_llama_pipeline()
result = process_single_text(sample_texts[0], pipeline, tokenizer, examples, room_types_str)
result

Loading model meta-llama/Llama-3.2-1B-Instruct...
Using device: cpu
Tokenizer loaded successfully
Set pad_token to eos_token
Model loaded successfully

Device set to use cpu

Test response: <s>[INST] What is 2+2? [/INST]</s> <s>[INST] What is 2+2? </s> <s>[INST]
Sending prompt: <s>[INST] <<SYS>>
You are a precise text extractor. Your response must contain only one JSON object ...
Raw response:

{'roomType': 'Unknown', 'confidence': 0.0}

In [21]:
result

'\n    Extract the following attributes from the text below:\n    - Room Type\n    - Bed Type\n    - Rate Plan Inclusives\n    - Room Amenities\n    - Meal Plan\n    - Room View\n    - Taxes and Fees\n\n    Format your response as a JSON object with these exact keys: \n    JSON: {"roomType": "string", "bedType": "string", "ratePlanInclusives": ["string"], "roomAmenities": ["string"], "mealPlan": "string", "roomView": "string", "taxesAndFees": "string"}\n\n    \n    Here are two examples of correct extractions: [\'Text: IN THE ART OF NEW YORK|MADISON KING RM. 450 SQFT. MADISON AVE VIEWS LRGE MARBLE BATH SEP SHOWER. COMP WIFI\\n    JSON: {"roomType": "King Bedroom", "bedType": "Unknown", "ratePlanInclusives": ["Private bath or shower", "Complimentary wireless internet"], "roomAmenities": ["Separate tub and shower", "Wireless internet connection"], "mealPlan": "Unknown", "roomView": "Avenue View", "taxesAndFees": "Unknown"}\', \'Text: AAA MEMBER RATE|ECO-FICIENT QUEEN ROOM RUNWAY VIEW. COMPLEMENTARY WIFI, IN ROOM COFFEE, IRON BOARD\\n    JSON: {"roomType": "Queen Bedroom", "bedType": "Unknown", "ratePlanInclusives": ["Eco Friendly", "Complimentary in-room coffee or tea", "Ironing board"], "roomAmenities": ["Wireless internet connection", "Ironing board"], "mealPlan": "Unknown", "roomView": "Runway View", "taxesAndFees": "Unknown"}\']   \n\n    Now extract from this text: ADVANCE SAVER|2 DOUBLE BEDS STANDARD NON SMOKING IN THIS CONTEMPORARY TWO DOUBLE BEDS GUEST ROOM GUESTS WILL ENJOY A SPACIOUS WARDROBE \n\n    Extract room attributes using ONLY the following normalized values:\n    Room Types: Accessible Room , Suite, Executive/Club Suite, Double Room , King Bedroom, Apartment, Queen Bedroom, Penthouse, Studio Suite, Twin Room, Family Room/Suite, Cabin, Cottage, Loft, Guest Room, Bungalow, Villa, Junior Suite, Run of the House, Large/Master Suite, Executive/Club Room, Classic Room, Comfort Room, Deluxe Room, Deluxe Suite, Economy Room, Luxury Suite, Premier Room, Standard Guest Room, Superior Room, Superior Suite, Grand Room, Premier Suite, Luxury Room, Classic Suite, Presidential Suite, Single Room, Triple Room, Quadruple Room, Studio Room, Cabana, Privilege Room, Prestige Room, Corner Room, Signature Room, Traditional Room , Wellness Room, Terrace Room, Tower Room, Heritage Room, Urban Room\n    Bed Types: Double/Full Bed, Futon Bed, King Bed, Murphy Bed, Queen Bed, Sofa Bed, Twin/Single Bed, Single Bed, Run of the house, Dorm/Bunk Bed, Water Bed\n    Rate Plan Inclusives: Piano, 24-hour front desk, 24-hour room service, 24-hour security, adjoining rooms, Air conditioning, Airline desk, ATM/Cash machine, Baby sitting, BBQ/Picnic area, Bilingual staff, Bookstore, Boutiques/stores, Brailed elevators, Business library, Care rental desk, Casino, Check cashing policy, Check-in kiosk, Cocktail lounge, Coffee Shop, Coin operated laundry, Concierge desk, Concierge floor, Conference facilities, Courtyard, Currency exchange, Desk with electrical outlet, Doctor on call, Door man, Driving Range, Drugstore/pharmacy, Duty free shop, Elevators, Exective floor, Exercise gym, Express Check-In, Express Check-out, Family plan, Florist, Folios, free shuttle, free parking, Free Transportation, Game room, Gift/News Stand, Hairdresser/Barber, Accessible Facilities, Health Club, Heated Pool, Housekeeping - Daily, Housekeeping - Weekly, Ice Machine, Indoor Parking, Indoor Pool, Hot Tub, Jogging Track, Kennels, Laundry/Valet Service, Liquor Store, Live Entertainment, Massage Services, Nightclub, Off-site parking, On-site parking , Outdoor parking, Outdoor Pool, Package/Parcel services, Parking, Photocopy Center, Playground, Pool, Poolside Snack bar, Public Address systemRamp Access, Ramp Access, Recreational Vehicle Parking, Restaurant, Room Service , Safe deposit box, Sauna, Security, Shoe Shine Standa, Shopping Mall, Solarium, Spa, Sports Bar, Steam Bath, Storage Space, Sundry/Convenience Store, Technical Concierge , Theatre Desk, Tour/sightseeing desk, Translation services, Travel agency, Truck Parking , Valet cleaning, Dry cleaning, Valet Parking , Vending Machine, Video Tapes, Wakeup services, Wheelchair access, Whirlpool, Multilingual staff, Wedding services, Banquet facilities, Bell staff/porter, Beauty shop/salon, Complimentary self service laundry, Direct  dial telephone , Female traveler room/floor, Pharmacy, Stables, 120 AC, 120 DC, 220 AC, Accessible Parking, 220 DC, Barbeque Grills, Women\'s clothing, Men\'s clothing, Children\'s clothing, Shops and commercial services, Video games, Sports bar open for lunch, Sports bar open for dinner, Room Service - full menu, Room Service - Limited menu, Room Service - limited hours, Valet same day dry clening, Body scrub, Body wrap, Public area air conditioned, Efolio available to company, Induvidual Efolio available, Video review billinh, Butler service, Complimentary in-room coffee or tea, Complimentary buffet breakfast, Complimentary cocktails, Complimentary coffee in lobby , Complimentary continental breakfast, Complimentary full american breakfast, Dinner delivery service from local restaurant, Complimentary newspaper delivered to room, Complimentary newspaper in lobby, Complimentary shoeshine, Evening reception, Front desk, Grocery shopping service available, Halal food available, Kosher food available, Limousine service, Managers reception, Medical facilities service, Telephone jack adaptor available, All-incusive meal plan, Buffet breakfast, Communcal bar area, Continental breakfast, Full meal plan, Full American breakfast, Meal plan availabe, Modified american meal plan, Food and Beverage outlets, Lounges/bars, Barber shop, Video checkout, Onsite laundry, 24-hour food & beverage kiosk, Concierge lounge, Parking fee managed by Hotel, Transportation, Breakfast served in restaurant, Lunch served in restaurant, Dinner served in restaurant, Full service housekeeping, Limited service housekeeping, High speed internet access for laptop in public area, Wirless internet connection in public area, Additional services/amenities/facilities on property, Transportation services - local area, Transportation srevices - local office, DVD/video rental, Parking lot, Parking deck, Street side parking, Cocktail lounge with entertainment, Cocktail lounge with light fare, Motorcycle parking , Phone services, Ballroom, Bus parking, Children\'s play area, Children\'s nursery, Disco, Early Check-in, Locker room, Non-smoking rooms (generic), Train access, Aerobics instruction, Baggage hold, Bicycle rentals, Dietician, Late check-out available, Pet-sitting services, prayer mats, Sports trainer, Turndown service, DVSs/videos - children, Bank, Lobby coffee service, Banking services, Stairwells, Pet amenities available, Exhibition/convention floor, Long term parking, Children not alowed, Children welcome, Courtesy car, Hotel does not provide porographic films/TV, Hotspots, Free high speed internet connections, Internet services, Pets allowed, Gourmet highlights, Catering services, Complimentary breakfast, Business center, Business services , Secured parking, Racquetball, Snow sports, Tennis court, Water sports, Child programs, Golf, Horseback riding, Oceanfront, Beachfront, Hair dryer, Ironing board, Heated guest rooms, Toilet, Parlor, Video game player, Thalassotheraphy, Private dining for groups, Hearing impaired services, Carryout breakfast, Deluxe Continental brekfast, Hot continental breakfast, Hot breakfast, Private pool, Connecting rooms, Data port, Exterior Corridors, Gulf view, ADA accessible, High speed internet access  , Interior corridors, High speed wireless, Kitchenette, Private bath or shower, Fire safety compliant, Welcome Drink, Boarding pass print-out available, Printing services available, All public areas non-smoking, Meeting rooms, Movies in room, Secretarial service, Snow skiing , Water skiing , Fax service, Great room , Multiple phone lines billed separetly, Umbrellas, Gas station, Grocery store, 24-hour coffee shop, Airport shuttle service, Luggage service, Piano bar, VIP security, Complimetary wirless internet,  Concierge breakfast, Same gender floor, Children programs, Buildin meets local, state and countru building codes, Internet browser on TV, Newspaper, Parking - controlled access gates to enter parking area, Hotel safe deposit box (not room safe box), Storage space available - fee, Type of entrances to guest rooms, Beverage/cocktail, Cell phone rental, Coffee/tea, Early check in guarantee, Food and beverage discount, Late check out guarantee, Room upgrade confirmed, Room upgrade on availability, Shuttle to local businesses, Shuttle to local attractions, Social hour, Video billing, Welcome gift , Hypoallergenic rooms, Room air filtration, Smoke-free property, Water purification system in use, Poolside service, Clothing store, Electric car charging stations, Office rental, Incoming fax, Outgoing fax, Semi-private space, Loading dock, Baby kit, Children\'s breakfast, Cloakroom service, Coffee lounge, Events ticket service, Late check-in, Limited parking , Outdoor summer bar/caf?, No parking available, Beer garden, Garden lounge bar, Summer terrace, Winter terrace, Roof terrace, Beach bar, Helicopter service, Ferry, Tapas bar, Caf? Bar, Snack bar, Guestroom wired internet, Guestroom wireless internet, Fietness center, Alcoholic beverages, Non-alcoholic beverages, Health and beauty services, Eco Friendly , Stay safe, Rooms with balcony, Local calls, Minibar, Refrigerator, In Room Safe, Smoking rooms available, Free WIFI in meeting rooms, Beach view, Ocean view, Mountain view, Pool view, Family Room, Rollaway adult, Crib charge, Extra person, Disney Park Tikcets included, Water Park Passes included, Free Minibar, Ski pass included, Free Airport Parking, Free Ski Lift Ticket & Rental, Free one way Airport transfer, Massage services included, Spa Access included , Golf access included, Free valet parking, Train station shuttle services, Golf clubs (equipments), Beach club, Theme park shuttle\n    Room Amenities: Adjoining rooms, Air conditioning, Alarm clock, All news channel, radio, Baby listening device, balcony, Barbeque grills, Bathtub with spray jets, Bathrobe, Bathroom amenities, Bathroom telephone, Bathtub, Bathtub only, Bathtub & shower, Bidet, Bottled water, Cable television, Coffee maker, Color television, Computer, Connecting rooms, electric converters , Copier, Cordless phone, Cribs, Data port, Desk, Desk with lamp, Dining guide, Direct dial phone number, Dishwasher, Double beds, Dual voltage outlet, Electrical current voltage, Ergonomic chair, Extended phone cord, Fax machine, Fire alarm, Fire alarm with light, Fireplace, Free toll free calls, Free calls, Free credit card access calls, Free local calls, Free movies, Full kitchen, Grab bars in bathroom, Grecian tub, Hairdryer, High speed internet connection, Interactive web TV, International direct dialing, Internet access, Iron, Ironing board, Whirlpool, King bed, Kitchen, Kitchen supplies, Kitchenette, Knock light, Laptop, Large desk, Large work area, Laundry basket, Loft, Microwave, Minibar, Modem, Modem jack, Multi-line phone, Newspaper, Non-smoking, Notepads, Office supplies, Oven, Pay per view movies on TV, Pens, Phone in bathroom, Plates and bowls, Pots and pans, Prayer mats, Printer, Private bathroom, Queen bed, Recliner, Refrigerator, Refrigerator with ice maker, Remote control television, Rollaway bed, Safe, Scanner, Separate closet, Separate modem line available, Shoe polisher, Shower only, Silverware, Sitting area, Smoke detectors, Smoking, Sofa bed, Speaker phone, Stereo, Stove, Tape recorder, Telephone, Telephone for hearing impaired, Telephones with message light, Toaster oven, Trouser press, Turn down service, Twin bed, Vaulted ceilings, VCR movies, VCR player, Video games, Voice mail, Wake-up calls, Water closet, Water purification system, Wet bar, Wireless internet connection, Wireless keyboard, Adaptor available for telephone PC use, Air conditioning individually controlled in room, Bathtub & whirlpool, Telephone with data ports, CD player, Complimentary local calls time limit, Extra person charge for rollaway use, feather pillows, Desk with electrical outlet, ESPN available, Foam pillows, HBO available, High ceilings, Marble bathroom, List of movie channels available, Pets allowed, Oversized bathtub, Shower, Sink in-room, Soundproofed room, Storage space, Tables and chairs, Two-line phone, Walk-in closet, Washer dryer, Weight scale, Welcome gift, Spare electrical outlet available at desk, Non refundable charge for pets, Refundable deposit for pets, Separate tub and shower, Entrance type to guest room, Ceiling fan, CNN available, Electrical adaptors available, Buffet breakfast, Accessible room, Closets in room, DVD player, Mini refrigerator, Separate line billing for multi-line phone, Self-controlled heating/cooling system, Toaster, Analog data port, Collect calls, International calls, Carrier access, Interstate calls, Intrastate calls, Local calls, Long distance calls, Operator assisted calls, Credit card access calls, Calling card calls, Toll free calls, Universal adaptors, Bathtub seat, Canopy, glassware, Entertainment center, Family room, Hypoallergenic bed, Hypoallergenic pillows, Lamp, Meal included - breakfast, Meal included - continental breakfast, Meal included - dinner, Meal included - lunch, Shared bathroom, Textphone, Water bed, Extra adult charge, Extra child charge, Extra child charge for rollaway use, Meal included: full American breakfast, Futon, Murphy bed, Tatami mats, Single bed, Annex room, Free newspaper, Honeymoon suites, Complimentary high speed internet in room, Maid service, PC hook-up in room, Satellite television, VIP rooms, Cell phone recharger, DVR player, iPod docking station, Media center, Plug & play panel, Satellite radio, Video on demand, Exterior corridors, Gulf view, Interior corridors, Mountain view, Ocean view, High speed internet access for fee, High speed wireless, Premium movie channels, Slippers, First nighters\' kit, Chair provided with desk, Pillow top mattress, Feather bed, Duvet, Luxury linen type, International channels, Pantry, Dish-cleaning supplies, Double vanity, Lighted makeup mirror, Upgraded bathroom amenities, VCR player available at front desk, Instant hot water, Outdoor space, Hinoki tub, Private pool, High Definition (HD) Flat Panel Television - 32 inches or greater, Room windows open, Bedding type unknown or unspecified, Full bed, Round bed, TV, Child rollaway, DVD player available at front desk, Video game player:, Video game player available at front desk, Dining room seats, Full size mirror, Mobile/cellular phones, Movies, Multiple closets, Plates/glassware, Safe large enough to accommodate a laptop, Bed linen thread count, Blackout curtain, Bluray player, Device with mp3, No adult channels or adult channel lock, Non-allergenic room, Pillow type, Seating area with sofa/chair, Separate toilet area, Web enabled, Widescreen TV, Other data connection, Phoneline billed separately, Separate tub or shower, Roof ventilator, Children\'s playpen, Plunge pool, DVD movies, Air filtration, Exercise Equipment in Room, Towels Sheets, Electric Kettle, Portable Fan, Washing Machine, Towels Provided, Smart TV, Streaming Services, Highchair, Toilet with electronic bidet, Free tea bags instant coffee, Outdoor Shower, Baby bath, Changing table, Heating/Heated floor, Indoor private mineral hot springs (japanese style onsen), Freezer, Ice maker, In room childcare, Digital TV serviceWired Internet Access, Wired Internet Access, Pillow Menu, Room Size(Square feet), Room Size (Square meters), Cleaning Supplies, Dryer, Tatami (Woven mat) floors, Private spa tub, Cookware, dishware, and utensils\n    Meal Plans: All Inclusive, Full Board or American, Buffet Breakfast, Continental Breakfast, Family Plan, Full Board, Half Board or Modified American, Room Only or European, Self Catering, Breakfast and Dinner, Breakfast , Lunch, Dinner, Breakfast and Lunch, Lunch and Dinner\n    Room Views: Airport view, Bay view, City view, Courtyard view, Golf View, Harbor view, Intercoastal view, Lake view, Marina view, Mountain view, Ocean view, Pool view, River view, Water view, Beach view, Garden view, Park view, Forest view, Rain forest view, Various views, Limited view, Slope view, Strip view, Countryside view, Sea view, Gulf view, Landmark View, Resort View, Lagoon View, Street View, Panoramic View, Hill View, Valley View, Vineyard View, Desert View, Mansion View, Metro View, Balcony View, Rock View, Skyline View, Village View, Stadium View, Island View, Runway View, Avenue View, Tower View, Fountain View, Cathedral View, Church View, Sunset View\n    Taxes and Fees: Bed tax, City hotel fee, PropertyFee, City tax, Municipal Tax, County tax, Energy tax, Federal tax, Food & beverage tax, Lodging tax, Maintenance fee, Occupancy tax, HotelOccupancyTax, Package fee, Resort fee, ResortFee, Sales tax, Taxes, SalesTax, Service charge, ServiceFee, State tax, Province Tax, Surcharge, Total tax, Tourism tax, VAT/GST tax, Surplus Lines Tax, Insurance Premium Tax, Application Fee, Express Handling Fee, Exempt, Standard, Zero-rated, Miscellaneous, MandatoryTax, Room Tax, Tax, Early checkout fee, Country tax, Extra person charge, ExtraPersonFee, Banquet service fee, Room service fee, Local fee, Goods and services tax (GST), Value Added Tax (VAT), Crib fee, Rollaway fee, Assessment/license tax, Pet sanitation fee, Not known, Child rollaway charge, Convention tax, Extra child charge, Standard food and beverage gratuity, National government tax, Adult rollaway fee, Beverage with alcohol, Beverage without alcohol, Tobacco, Food, Total surcharges, TaxAndServiceFee, State cost recovery fee, Miscellaneous fee, Mandatory Fee, MandatoryFee, Destination amenity fee, Refundable pet fee, Property Fee, Tax Recovery Charges and Service Fees, Tax Recovery Charges\n\n    If no clear match exists, return \'Unknown\'.\n\n    Rules for extraction:\n    1. Each room must have exactly one room type\n    2. Each room must have at least one bed type\n    3. Rate Plan Inclusives should be a list\n    4. Meal Plan is optional\n    5. View is optional\n    6. Amenities should be a list\n    7. Do not infer attributes that aren\'t explicitly mentioned\n\n    Special cases to handle:\n    - If multiple bed types are mentioned, list all of them\n    - If amenities are described but not in our standard list, choose the closest match\n    - Unclear if ambiguous.\n    - Ignore pricing and promotional information\n\n    For each extracted attribute, provide a confidence score, like below example: \n    JSON: {"roomType": "Queen Bedroom", "bedType": "King Bed", "ratePlanInclusives": {"values": ["Unknown"], "confidence": 0.85}, "roomAmenities": {"values": ["Wireless internet connection", "Ironing board"], "confidence": 0.85}, "mealPlan": {"value": "Unknown", "confidence": 0.8}, "roomView": {"value": "Ocean view", "confidence": 0.95}, "taxesAndFees": {"value": "Unknown", "confidence": 0.95}}\n\n    \n    Follow these steps:\n    1. First, identify all mentioned attributes in the text\n    2. Then, match each attribute to the closest normalized value\n    3. Validate against the allowed values list\n    4. Format the final output as JSON without escaping\n    5. Explain your reasoning for any uncertain matches\n\n    Show your work:\n    Identified attributes: ...\n    Normalized matches: ...\n    Final output: ...\n    Reasoning: ...\n    Return the final result similar to the example, with no extra text.\n\n     Identified attributes: \n    - Room Type\n    - Bed Type\n    - Rate Plan Inclusives\n    - Room Amenities\n    - Meal Plan\n    - Room View\n    - Taxes and Fees\n    - Room View\n    - Taxes and Fees\n    - Room View\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes and Fees\n    - Taxes 

# Finetuning #

## Preparing Datasets ##

In [91]:
raw_text = dataset['Room Description Expanded'].to_list()
raw_text

['FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'BEST AVAILABLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'STANDARD RATE ACCESSIBLE 1BR KING TUB|ACCESSIBLE ONE BEDROOM KING SUITE WITH/ ACCESSIBLE BATHTUB',
 'STAY PARK FLY ACCESSIBLE 1BR KING TUB|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'FLEXIBLE RATE|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'DREAM AWAY|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'PRE/POST CRUISE ACCESSIBLE 1BR KING T|RATE COVERS DOUBLE OCCUPANCY. TRANSFERS TO',
 'TRIPADVISOR PLUS|ACCESSIBLE ROOM - AC-SITTING AREA-FREE WI-FI-DESK LG ROLL-IN SHOWER - INC CONT BREAKFAST',
 'FLEXIBLE RATE|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 '2X POINTS PACKAGE|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'SEMI-FLEX|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'PARK AND STAY AARP|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'SEMI-FLEX|1KING HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'FLEXIBLE RATE|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 '2X POINTS PACKAGE|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'TRIP ADVISOR|2QUEEN BEDS MINI FRIDGE 43 TV 318 SQ FT 5 PPL ACCESSIBLE ROOMS AVAIL UPON REQUEST COMP BOTTLED H20 BREAKFAST IN OUR RESTAURANT',
 'STANDARD RATE ACCESSIBLE KING SHR NSB|ACCESSIBLE KING ROOM WITH ACCESSIBLE SHOWER',
 'CANCELLATION POLICY: DAY OF AR|SUPERIOR ACCESSIBLE ROOM KING BED-350 SQFT-LUXURY BATH AMENITIES-FREE WIFI-MAX 2 PPL CANCELLATION POLICY: DAY OF ARRIVAL AT 4 PM EXEMPT FROM FACILITY FEE REVERE CLUB ACCESSIBLE',
 'SEMI-FLEX|2QUEEN ACCESSIBLE BATHTUB STUDIO NONSMOKING FREE BRKFST/WI-FI-KITCHEN WITHMICRO/FRIDGE',
 'CANCELLATION POLICY: DAY OF AR|SUPERIOR ACCESSIBLE ROOM 2 QUEEN BED-350 SQFT-LIVING SPACE-ROLL IN SHOWER-FREE WIFI-MAX 4 PPL CANCELLATION POLICY: DAY OF ARRIVAL AT 4 PM EXEMPT FROM FACILITY FEE REVERE CLUB ACCESSIBLE',
 'FLEXIBLE RATE|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'FLEXIBLE RATE|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'TRIPADVISOR PLUS RATE|MOBILITY ACCESSIBLE TWO QUEEN GULF VIEW ROOM FURNISHED BALCONY 15PCT OFF 20USD CREDIT DAILY WELCOME GIFT',
 'FLEXIBLE RATE|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'TRIP ADVISOR PLUS RATE|ACCESSIBLE DELUXE KING-CITY VIEW-1 KING-374SQFT- WIFI-ROLL IN SHOWER-LUXURY LINENS',
 'FLEXIBLE RATE|KING BED URBAN ROOM MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/CONTEMP DESIGN/55 IN TV/FRIDGE',
 'TRIP ADVISOR PLUS RATE|ACCESSIBLE DELUXE 2 QUEENS-CITY VIEW-2 QUEENS-495SQFT- WIFI-ROLL IN SHOWER-LUXURY LINENS',
 'BEST AVAILABLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'FLEXIBLE RATE|URBAN 2 DOUBLE HEARING ACCESSIBLE 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 '2X POINTS PACKAGE|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'WYNDHAM REWARDS DOUBLE POINTS|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'SEMI-FLEX|1 KING MOBILITY/HEARING ACCESSIBLE WITHTUB NONSMOK VIS FIREALRM/DOOR/PHN ALRT',
 'FLEXIBLE RATE|URBAN 1 KING MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'BEST AVAILABLE RATE|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 '2X POINTS PACKAGE|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SEMI-FLEX|1 KING HEARING ACCESSIBLE STUDIO WITHSOFABED NON SMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'SEMI-FLEX|URBAN 2 DOUBLE HEARING ACCESSIBLE 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'AAA HOT DEALS|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'BEST AVAILABLE RATE FLEXIBLE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'PARK STAY FLY ACCESSIBLE KING SHR NSB|FREE LONGTERM PARKING FOR UP TO 14 NIGHTS',
 'SNOOZE   CRUISE ACCESSIBLE KING SHR N|TRANSPORTATION FROM TAMPA AIRPORT TO HOTEL',
 'PAY NOW SAVE NON-CX|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'AAA RATE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'SEMI-FLEX|1KING MOBILTY/HEARING ACCESSIBLE RI SHWR SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 '2X POINTS PACKAGE|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 'FLEXIBLE RATE|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 '2X POINTS|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'BREAKFAST INCLUDED|2QN MOBILITY ACCESSIBLE WITHBATHTUB COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'FAMILY FUN PACKAGE.|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 'SEMI-FLEX|URBAN 1 KING MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/VIS FIREALRM/DOOR/PHN ALRT',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE KING SUITE WITH FULL SOFA SLEEPER 500 SQ FT - ACCESSIBLE SHOWER - GROUND FLOOR',
 'SENIOR DISCOUNT|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'AARP RATE|1 KING BED ACCESSIBLE ROOM NON SMOKING WITH FREE WIFI, FREE CONTINENTAL BREAKFAST, ACCESSIBLE BATH',
 'JEAN GEORGES BED AND BREAKFAST|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'BEST AVAILABLE RATE|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'TRIPADVISOR PLUS RATE|2 ACCESSIBLE ROOMS KING BED FULL KITCHEN 1 QUEEN SLEEPER DINING AREA 2 BATHROOMS 15PCT OFF 20USD CREDIT DAILY WELCOME GIFT',
 'FLEXIBLE RATE|ACCESSIBLE SUPERIOR TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'CWT FREE WIFI FOR IHG REWARDS|MEMBERS. 10 IHG PTS PER 1 USD SPENT DESTINATION KING IC MOBILITY ACCESSIBLE ROLL IN SHWR MOBILITY ACCESSIBLE.  EXPECT MODERN ELEGANCE WHILE STAYING TRUE TO',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE KING SHOWER ONLY 1 KING BED ',
 'STAY PARK FLY ACCESSIBLE 2BR 2D1K SHW|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'STANDARD RATE ACCESSIBLE KING TUB NO SB|ACCESSIBLE KING ROOM WITH ACCESSIBLE BATHTUB',
 'FLEXIBLE RATE|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 '2X POINTS|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 'DREAM AWAY|KING BED URBAN ROOM MOBILITY ACCESSIBLE BATHTUB 30USD MAND CHG/CONTEMP DESIGN/55 IN TV/FRIDGE',
 'FLEXIBLE RATE|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 '2X POINTS|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'BREAKFAST INCLUDED|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SUPERIOR TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'FLEXIBLE RATE|RESORT ACCESSIBLE KING, 1 KING BED MOBILITY ACCESSIBLE THROUGHOUT ROOM',
 'TRIPADVISOR PLUS|SPANISH KING ACCESSIBLE ROOM BRK FOR 2 AND PRKING NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 'FLEXIBLE RATE|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'TRIPADVISOR PLUS|1 KING BED NON SMOKING ACCESSIBLE ACCESSIBLE WITH ROLL-IN SHOWER',
 '2X POINTS PACKAGE|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AAA|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|RESORT ACCESSIBLE TWO QUEEN, 2 QUEEN BEDS MOBILITY ACCESSIBLE THROUGHOUT ROOM',
 'PARK AND GO|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ BATHTUB VIS DOORBELL ALRT AND VIS PHONE ALRT',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 '2X POINTS PACKAGE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 'TRIPADVISOR PLUS|KING ACCESSIBLE ROOM WITH ROLL IN SHOWER NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 '2X POINTS|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ BATHTUB VIS DOORBELL ALRT AND VIS PHONE ALRT',
 'DINE AND UNWIND|1KNG MOB ACC RI-SHW COMP WIFI- HDTVS WITH HIDEF CHANNELS',
 'FAMILY FUN PACKAGE.|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR NO SMOK SWEET DREAMS EXPERIENCE BED',
 'TRIPADVISOR PLUS RATE|1 QUEEN MOBILITY ACCESSIBLE ROOM, GENESEE BUILDING NON SMOKING WITH FREE WIFI, BATHTUB GRAB BARS',
 'BREAKFAST INCLUDED|1 KING HEARING/MOBILITY ACCESSIBLE WITH BATHTUB VIS FIREALRM/DOOR/PHN ALRT-FRIDGE-340SQFT',
 'FLEXIBLE RATE|ACCESSIBLE SUPERIOR KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'FLEXIBLE RATE|RESORT ACCESSIBLE ROOM, 1 KING BED 510 SQ FT, MULTIPLE VIEWS, SAFETY BARS',
 'FLEXIBLE RATE|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 '2X POINTS PACKAGE|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'FLEXIBLE RATE|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'PARK AND STAY AAA|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND STAY AARP|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'PARK AND GO|1KING MOBILTY/HEARING ACCESSIBLE TUB STUDIO NOSMK VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'JP MORGAN CHASE AND COMP|WIFI. 6 PM CXL. 10 IHG PTS PER 1USD SPENT. KING IC MOBILITY ACCESSIBLE ROLL IN SHWR MOBILITY ACCESSIBLE.  EXPECT MODERN ELEGANCE WHILE STAYING TRUE TO',
 'SEMI-FLEX|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|2 DOUBLE BEDS MOBILITY ACCESSIBLE WITH/ BATHTUB 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 'CWT SMALLBIZ -24HR CXL LATE CK|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'OUR BEST AVAILABLE RATE|ACCESSIBLE 2 QUEENS APPROX 395 SQ FT - JULIET BALCONY ACCESSIBLE ROOM - WHEELCHAIR ACCESSIBLE BATH',
 '2X POINTS|2 DOUBLE MOBILITY ACCESSIBLE WITH/ RI SHWR 37IN FLAT SCREEN HDTV / COMP FITNESS CENTER',
 'FLEXIBLE RATE|PARK MGM KING - 1 KING BED ACCESSIBLE 406 SQ FT, BEDSIDE OUTLETS, SAFETY BAR',
 'FLEXIBLE RATE|PARK ACC KING ROLL IN SHOWER, 1 KING BED 406 SQ FT, ROLL IN SHOWER, SAFETY BAR',
 'DAILY PARKING PKG PACKAGE|INCLUDES ROOM ACCOMMODATIONS AND PARKING FOR 1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP TO TWO ADULTS SHARING A 1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BEST FLEXIBLE RATE|1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'DAILY PARKING PKG PACKAGE|INCLUDES ROOM ACCOMMODATIONS AND PARKING FOR 1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST FOR 2 ADULTS FULL|BREAKFAST DAILY FOR UP TO TWO ADULTS SHARING A 1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BEST FLEXIBLE RATE|1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'JP MORGAN CHASE -PREFERRED RAT|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ ROLL IN SHW VIS FIREALRM/DOOR/PHN ALRT',
 'AARP RATE|KING BED-ACCESSIBLE-NON-SMOKING -EXCLUSIVE RATE FOR AARP MEMBERS',
 'FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ RI SHWR VISUAL FIREALARM/DOOR/PHONE ALERT',
 'ADVANCE SAVER|1 KING BED HEARING ACCESSIBLE NON SMOKING IN THIS CONTEMPORARY ONE KING BED HEARING ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE SUPERIOR KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'ADVANCE SAVER|1 QUEEN BED MOBILITY ACCESSIBLE TUB NON SMOKING IN THIS CONTEMPORARY ONE QUEEN BED MOBILITY ACCESSIBLE GUEST ROOM GUESTS WILL ENJOY A',
 'BREAKFAST, WIFI  PARKING|1 SOFA PARLOR MOBILITY ACCESSIBLE TUB NO SMOK PARLOR-CUSTOM KING SLEEPER SOFA',
 '2X POINTS|1 KING MOBILITY/HEARING ACCESSIBLE WITH/ ROLL IN SHW VIS FIREALRM/DOOR/PHN ALRT',
 'BEST AVAILABLE RATE|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 '2X POINTS PACKAGE|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILABLE RATE|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 '2X POINTS PACKAGE|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'HOLIDAY WEEKEND PKG|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILABLE RATE WITH DINNE|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'AAA FLEXIBLE OFFER|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'HOLIDAY WEEKEND PKG|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SHOPPING AT CABELAS|1 KING HEARING ACCESSIBLE SUITE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/SOFABED',
 'SHOPPING AT CABELAS|2 QUEENS HEARING ACCESSIBLE NONSMOKING VIS FIREALRM/DOOR/PHN ALRT/HDTV',
 'BEST AVAILBALE RATE WITH BREAK|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'FLEXIBLE RATE|ACCESSIBLE CATHEDRAL VIEW KING - 360 SF OR 33 SM - SPACIOUS ACCESSIBLE COMPLIANT ROOM',
 'BEST AVAILABLE RATE|ACCESSIBLE ROOM FULLY EQUIPPED FREE IN ROOM WI-FI AVAILABLE',
 'BOOKS FOR KIDS|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
 'CWT BUSINESS RATES|ACCESSIBLE SKYLINE CATHEDRAL VIEW KING - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM ON HIGH FLOOR',
 'PRE/POST CRUISE ACCESSIBLE ST KING SH|RATE COVERS DOUBLE OCCUPANCY. TRANSFERS TO',
 'AAA RATE-ID REQUIRED|PARK MGM KING - 1 KING BED ACCESSIBLE 406 SQ FT, BEDSIDE OUTLETS, SAFETY BAR',
 'STAY PARK FLY ACCESSIBLE ST KING SHWR|INCLUDES ONE NIGHT STAY AND 7 NIGHTS',
 'FLEXIBLE RATE|2 DOUBLE MOBILITY/HEARING ACCESSIBLE WITHBATHTUB VIS FIRE ALARM/ DOOR/PHONE ALERT',
 'SAVE 10 PCT OFF ACCESSIBLE KING TUB|ACCESSIBLE KING ROOM WITHACCESSIBLE SHOWER AND TUB: SOFABED:',
 'TRIPADVISOR PLUS|CASA SURF ACESSIBLE ROOM NO RST COMP WIFI PARKING HIST SPANISH BOUTIQUE HOTEL LOCATED ON THE BCH',
 'CWT BUSINESS RATES|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'AAA FLEXIBLE OFFER|ACCESSIBLE SKYLINE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'OUR BEST AVAILABLE RATE|ACCESSIBLE KING APPROX 395 SQFT - PATIO.JULIET OPTIONS ACCESSIBLE ROOM - WHEELCHAIR ACCESSIBLE BATH',
 'TRIPADVISOR PLUS|ACCESSIBLE 1 QUEEN BED- 17 SQM- QUEEN BED- AC- FREE WIFI- SHOWER- WORK DESK- HAIRDYER-',
 'STANDARD RATE ACCESSIBLE KING TUB|ACCESSIBLE KING ROOM WITHACCESSIBLE SHOWER AND TUB: SOFABED:',
 'CWT PROGRAM -HONORS SEMI-FLEX|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR',
 'FLEXIBLE RATE|ACCESSIBLE CATHEDRAL VIEW TWO DOUBLE BEDS - 360 SF OR 33 SM - ACCESSIBLE COMPLIANT ROOM',
 'BEST FLEXIBLE RATE|HUDSON SQUARE KING ACCESSIBLE ROOM - URBAN VIEW 1 KING BED  - 430 SQF - 40 SQM',
 'WORLD RAINBOW HOTELS BAR|ACCESSIBLE CATHEDRAL VIEW KING - 360 SF OR 33 SM - SPACIOUS ACCESSIBLE COMPLIANT ROOM',
 'STANDARD RATE ACCESSIBLE DOUBLE TUB NOSB|ACCESSIBLE DOUBLE ROOM WITH ACCESSIBLE BATHTUB',
 'FLEXIBLE RATE|1KG MOBILITY/HEARING ACCESSIBLE 3X3SHW NO SMOK VIS FIREALRM/DOOR/PHN ALRT',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE DOUBLE - ROLL-IN SHOWER - CITY VIEW 350 SQ.FT. FLAT SCREEN TV',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE KING LOFT SUITE -1 KING BED - 550 SQ.FT. LIVING ROOM - FLAT SCREEN TV - COTTON ROBES',
 'TRIPADVISOR PLUS RATE|ACCESSIBLE DELUXE KING -1 KING BED -350 SQ.FT. FLAT SCREEN TV-MAISON MARGIELA BATH AMENITIES',
 'PREFERRED SUITES|ACCESSIBLE ACCESSIBLE ROOM. KING BED. 450 SQFT. COURTYARD VIEW. COMP WIFI',
 'CWT BUSINESS RATES|ACCESSIBLE TOWERS ROOM TWO QUEENS - 465 SF OR 43 SM - ACCESSIBLE ROOM ON FLOORS 41 TO 55',
 'WORLD RAINBOW BAR RATE|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'NO-AMENITY FEE-UP TO 10PCT OFF|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'SENIOR-AARP DISCOUNT|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'BEST AVAILABLE RATE *|MOBILITY HEARING ACCESSIBLE KING. SEATING AREA. SOFABED. TUB WITH GRAB BARS',
 'STANDARD RATE 1 KNG ACCESSIBLE SHOWER|ACCESSIBLE 1 KING BED: ROLL IN SHOWER:OUTSIDE/ATRIUM',
 '2X POINTS PACKAGE|QUEEN ACCESSIBLE ROOM HDTV/WORK AREA/SOFA BED',
 'PARK STAY FLY ACCESSIBLE DOUBLE TUB NOSB|FREE LONGTERM PARKING FOR UP TO 14 NIGHTS',
 'SNOOZE   CRUISE ACCESSIBLE DOUBLE TUB NO|TRANSPORTATION FROM TAMPA AIRPORT TO HOTEL',
 'FLEXIBLE RATE|1 KNG WHRPL ROOM MOBILITY ACCESSIBLE WITHRI SHWR FIREPLACE-COMP WIFI-BED WITH/ ADJUST FIRM DIAL',

In [92]:
dataset['Room Description Expanded'].groupby(dataset['Guest Room Info']).count()

Guest Room Info
Accessible Room          962
Apartment                959
Bungalow                 978
Cabana                   984
Classic Room             907
Classic Suite            846
Comfort Room             900
Cottage                 1000
Deluxe Room              955
Deluxe Suite             954
Double Bed               815
Executive/Club Room      981
Executive/Club Suite     860
Family Room/Suite        965
Guest Room               694
Junior Suite             922
King Bedroom             921
Loft                     963
Luxury Room              958
Luxury Suite             949
Penthouse                975
Premier Room             878
Premier Suite            657
Presidential Suite       949
Queen Bedroom            813
Run of the House         593
Single Room              943
Standard Room            919
Studio Room              607
Studio Suite             864
Suite                    987
Superior Room            964
Superior Suite           950
Twin Room                738
Villa                    927
Name: Room Description Expanded, dtype: int64

# Creating a Stratified Sample to represent each Room Type alike #

In [93]:
import numpy as np

def create_stratified_sample(dataset, n_samples_per_class, seed = 42):
    """
    Creates a stratified sample from dataset
    """

    # Seed everything
    random.seed(seed)
    np.random.seed(seed)

    # Rest of the sampling process
    room_types = dataset['Guest Room Info'].unique()
    sample_rows = []
    sampled_indices = set()
    
    print(f"\nSampling {n_samples_per_class} descriptions per room type:")
    print("=" * 50)
    
    for room_type in room_types:
        room_type_data = dataset[dataset['Guest Room Info'] == room_type]
        available = len(room_type_data)
        
        if available < n_samples_per_class:
            print(f"\nWarning: Only {available} samples available for {room_type}")
            n_to_sample = available
        else:
            n_to_sample = n_samples_per_class
            
        sampled = room_type_data.sample(n=n_to_sample, random_state=seed)
        sample_rows.append(sampled)
        sampled_indices.update(sampled.index)
        
        print(f"\n{room_type}:")
        print(f"- Sampled {n_to_sample} from {available} available")
    
    sample_df = pd.concat(sample_rows, axis=0).reset_index(drop=True)
    remaining_df = dataset[~dataset.index.isin(sampled_indices)].reset_index(drop=True)
    
    print(f"\nFinal counts:")
    print(f"Sample size: {len(sample_df)}")
    print(f"Remaining size: {len(remaining_df)}")
    
    return sample_df, remaining_df

# Creating Training data with 1% of the data

In [94]:
# 1% of each room type as training data

n_samples_per_class = 10
sample_df_1pct, remaining_df_1pct = create_stratified_sample(dataset, n_samples_per_class)

Sampling 10 descriptions per room type:
==================================================

Accessible Room:
- Sampled 10 from 962 available

Suite:
- Sampled 10 from 987 available

Executive/Club Suite:
- Sampled 10 from 860 available

Double Bed:
- Sampled 10 from 815 available

King Bedroom:
- Sampled 10 from 921 available

Queen Bedroom:
- Sampled 10 from 813 available

Penthouse:
- Sampled 10 from 975 available

Studio Suite:
- Sampled 10 from 864 available

Twin Room:
- Sampled 10 from 738 available

Family Room/Suite:
- Sampled 10 from 965 available

Cottage:
- Sampled 10 from 1000 available

Loft:
- Sampled 10 from 963 available

Guest Room:
- Sampled 10 from 694 available

Bungalow:
- Sampled 10 from 978 available

Villa:
- Sampled 10 from 927 available

Junior Suite:
- Sampled 10 from 922 available

Executive/Club Room:
- Sampled 10 from 981 available

Classic Room:
- Sampled 10 from 907 available

Comfort Room:
- Sampled 10 from 900 available

Deluxe Room:
- Sampled 10 from 955 available

Deluxe Suite:
- Sampled 10 from 954 available

Premier Room:
- Sampled 10 from 878 available

Standard Room:
- Sampled 10 from 919 available

Superior Room:
- Sampled 10 from 964 available

Superior Suite:
- Sampled 10 from 950 available

Premier Suite:
- Sampled 10 from 657 available

Luxury Room:
- Sampled 10 from 958 available

Classic Suite:
- Sampled 10 from 846 available

Presidential Suite:
- Sampled 10 from 949 available

Single Room:
- Sampled 10 from 943 available

Studio Room:
- Sampled 10 from 607 available

Cabana:
- Sampled 10 from 984 available

Apartment:
- Sampled 10 from 959 available

Luxury Suite:
- Sampled 10 from 949 available

Run of the House:
- Sampled 10 from 593 available

Final counts:
Sample size: 350
Remaining size: 30887

# Creating Training data with 5% of the data

In [ ]:
n_samples_per_class = 50
sample_df_5pct, remaining_df_5pct = create_stratified_sample(dataset, n_samples_per_class)

Sampling 50 descriptions per room type:
==================================================

Accessible Room:
- Sampled 50 from 962 available

Suite:
- Sampled 50 from 987 available

Executive/Club Suite:
- Sampled 50 from 860 available

Double Bed:
- Sampled 50 from 815 available

King Bedroom:
- Sampled 50 from 921 available

Queen Bedroom:
- Sampled 50 from 813 available

Penthouse:
- Sampled 50 from 975 available

Studio Suite:
- Sampled 50 from 864 available

Twin Room:
- Sampled 50 from 738 available

Family Room/Suite:
- Sampled 50 from 965 available

Cottage:
- Sampled 50 from 1000 available

Loft:
- Sampled 50 from 963 available

Guest Room:
- Sampled 50 from 694 available

Bungalow:
- Sampled 50 from 978 available

Villa:
- Sampled 50 from 927 available

Junior Suite:
- Sampled 50 from 922 available

Executive/Club Room:
- Sampled 50 from 981 available

Classic Room:
- Sampled 50 from 907 available

Comfort Room:
- Sampled 50 from 900 available

Deluxe Room:
- Sampled 50 from 955 available

Deluxe Suite:
- Sampled 50 from 954 available

Premier Room:
- Sampled 50 from 878 available

Standard Room:
- Sampled 50 from 919 available

Superior Room:
- Sampled 50 from 964 available

Superior Suite:
- Sampled 50 from 950 available

Premier Suite:
- Sampled 50 from 657 available

Luxury Room:
- Sampled 50 from 958 available

Classic Suite:
- Sampled 50 from 846 available

Presidential Suite:
- Sampled 50 from 949 available

Single Room:
- Sampled 50 from 943 available

Studio Room:
- Sampled 50 from 607 available

Cabana:
- Sampled 50 from 984 available

Apartment:
- Sampled 50 from 959 available

Luxury Suite:
- Sampled 50 from 949 available

Run of the House:
- Sampled 50 from 593 available

Final counts:
Sample size: 1750
Remaining size: 29487

# Creating Training data with 10% of the data

In [ ]:

n_samples_per_class = 100
sample_df_10pct, remaining_df_10pct = create_stratified_sample(dataset, n_samples_per_class)

Sampling 100 descriptions per room type:
==================================================

Accessible Room:
- Sampled 100 from 962 available

Suite:
- Sampled 100 from 987 available

Executive/Club Suite:
- Sampled 100 from 860 available

Double Bed:
- Sampled 100 from 815 available

King Bedroom:
- Sampled 100 from 921 available

Queen Bedroom:
- Sampled 100 from 813 available

Penthouse:
- Sampled 100 from 975 available

Studio Suite:
- Sampled 100 from 864 available

Twin Room:
- Sampled 100 from 738 available

Family Room/Suite:
- Sampled 100 from 965 available

Cottage:
- Sampled 100 from 1000 available

Loft:
- Sampled 100 from 963 available

Guest Room:
- Sampled 100 from 694 available

Bungalow:
- Sampled 100 from 978 available

Villa:
- Sampled 100 from 927 available

Junior Suite:
- Sampled 100 from 922 available

Executive/Club Room:
- Sampled 100 from 981 available

Classic Room:
- Sampled 100 from 907 available

Comfort Room:
- Sampled 100 from 900 available

Deluxe Room:
- Sampled 100 from 955 available

Deluxe Suite:
- Sampled 100 from 954 available

Premier Room:
- Sampled 100 from 878 available

Standard Room:
- Sampled 100 from 919 available

Superior Room:
- Sampled 100 from 964 available

Superior Suite:
- Sampled 100 from 950 available

Premier Suite:
- Sampled 100 from 657 available

Luxury Room:
- Sampled 100 from 958 available

Classic Suite:
- Sampled 100 from 846 available

Presidential Suite:
- Sampled 100 from 949 available

Single Room:
- Sampled 100 from 943 available

Studio Room:
- Sampled 100 from 607 available

Cabana:
- Sampled 100 from 984 available

Apartment:
- Sampled 100 from 959 available

Luxury Suite:
- Sampled 100 from 949 available

Run of the House:
- Sampled 100 from 593 available

Final counts:
Sample size: 3500
Remaining size: 27737

## LLAMA ##

Finetuning LLAMA 3.1B is in a different ipynb file - final_codes/finetuned_llama_3_1b.ipynb

## BERT ##

In [97]:
#%% Importing libraries
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from datasets import Dataset
import numpy as np
from sklearn.metrics import accuracy_score, classification_report
import torch
from sklearn.model_selection import train_test_split
import pandas as pd
from tqdm import tqdm

In [98]:
from huggingface_hub import login
login(token='') # Input a Hugging Face Token

In [99]:
dataset['Room Description Expanded'].unique()

array(['FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
       '2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
       'PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NON SMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT',
       ...,
       'BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WHEN YOU ARRIVE WE WILL DO OUR BEST TO MEET YOUR ROOM BED TYPE AND SMOKING PREFERENCES. RMS SUBJ',
       'GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STANDARD ROOM DOUBLE BED OR 2 SINGLES WOODEN FLOOR',
       'CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS AREA AND BREAKFAST FOR 1 SPECIALTY ROOM WHEN YOU ARRIVE AT THE HOTEL WE WILL DO OUR BEST TO MEET YOUR ROOM TYPE PREFERENCE THIS IS SUBJECT TO'],
      dtype=object)

In [100]:
def create_stratified_sample(dataset, n_samples_per_class):
    """
    Creates a stratified sample from deduplicated dataset
    """
    # First deduplicate the dataset
    deduplicated_data = dataset.drop_duplicates(subset=['Room Description']).reset_index(drop=True)
    print(f"Original rows: {len(dataset)}")
    print(f"After deduplication: {len(deduplicated_data)}")
    
    # Rest of the sampling process
    room_types = deduplicated_data['Guest Room Info'].unique()
    sample_rows = []
    sampled_indices = set()
    
    print(f"\nSampling {n_samples_per_class} descriptions per room type:")
    print("=" * 50)
    
    for room_type in room_types:
        room_type_data = deduplicated_data[deduplicated_data['Guest Room Info'] == room_type]
        available = len(room_type_data)
        
        if available < n_samples_per_class:
            print(f"\nWarning: Only {available} samples available for {room_type}")
            n_to_sample = available
        else:
            n_to_sample = n_samples_per_class
            
        sampled = room_type_data.sample(n=n_to_sample, random_state=42)
        sample_rows.append(sampled)
        sampled_indices.update(sampled.index)
        
        print(f"\n{room_type}:")
        print(f"- Sampled {n_to_sample} from {available} available")
    
    sample_df = pd.concat(sample_rows, axis=0).reset_index(drop=True)
    remaining_df = deduplicated_data[~deduplicated_data.index.isin(sampled_indices)].reset_index(drop=True)
    
    print(f"\nFinal counts:")
    print(f"Sample size: {len(sample_df)}")
    print(f"Remaining size: {len(remaining_df)}")
    
    return sample_df, remaining_df

In [103]:
labels = sample_df_1pct['Guest Room Info'].unique()
label2id = {label: i for i, label in enumerate(labels)}
id2label = {i: label for label, i in label2id.items()}
num_labels = len(labels)

print(f"Number of labels: {num_labels}")
model_name = "bert-base-uncased"

Number of labels: 35

In [104]:
def train_final_model(full_sample_data, model_name, label2id, output_dir="final_bert_base_uncased"):
    """Train final model on all 350 or 3500 samples"""
    id2label = {i: label for label, i in label2id.items()}
    num_labels = len(label2id)
    
    print("\nTraining final model on all sample data...")
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=num_labels,
        id2label=id2label,
        label2id=label2id
    )
    
    # Prepare full dataset
    texts = full_sample_data['Room Description Expanded'].tolist()
    labels = [label2id[label] for label in full_sample_data['Guest Room Info']]
    
    tokenized = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    )
    
    full_dataset = Dataset.from_dict({
        'input_ids': tokenized['input_ids'],
        'attention_mask': tokenized['attention_mask'],
        'labels': labels
    })
    
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=5,  # More epochs for final training
        per_device_train_batch_size=16,
        learning_rate=2e-5,
        save_strategy="epoch"
    )
    
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=full_dataset,
        tokenizer=tokenizer
    )
    
    trainer.train()
    trainer.save_model()
    tokenizer.save_pretrained(output_dir)
    
    return model, tokenizer

In [105]:
def classify_remaining_data(model, tokenizer, label2id, remaining_data):
    """Classify the remaining 35k descriptions"""
    device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
    model = model.to(device)
    
    id2label = {i: label for label, i in label2id.items()}
    results = []
    
    print("\nClassifying remaining descriptions...")
    for _, row in tqdm(remaining_data.iterrows(), total=len(remaining_data)):
        inputs = tokenizer(
            row['Room Description Expanded'],
            padding=True,
            truncation=True,
            max_length=128,
            return_tensors="pt"
        )
        inputs = {k: v.to(device) for k, v in inputs.items()}
        
        outputs = model(**inputs)
        predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
        predicted_id = torch.argmax(predictions, dim=-1).item()
        confidence = predictions[0][predicted_id].item()
        
        results.append({
            'Room Description': row['Room Description Expanded'],
            'Actual_Room_Type': row['Guest Room Info'],  # Added actual label
            'Predicted_Room_Type': id2label[predicted_id],
            'Confidence': confidence
        })
    
    results_df = pd.DataFrame(results)
    
    # Add accuracy column
    results_df['Correct'] = results_df['Actual_Room_Type'] == results_df['Predicted_Room_Type']
    
    # Print overall accuracy
    accuracy = results_df['Correct'].mean()
    print(f"\nOverall Accuracy: {accuracy:.2%}")
    
    return results_df

## Finetuning BERT on 1% of dataset ##

In [104]:
# 2. Train on full sample dataset
final_model, final_tokenizer = train_final_model(sample_df_1pct, model_name, label2id)

Training final model on all sample data...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_53697/406571484.py:42: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Python(88289) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(88290) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
Python(88297) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(88298) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
wandb: Currently logged in as: karthik1705 (karthik1705-the-university-of-texas-at-austin). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
Python(88299) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(88306) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(88309) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [107]:
# 3. Classify remaining data
#remaining_data = remaining_data
results_df = classify_remaining_data(final_model, final_tokenizer, label2id, remaining_df_1pct)

Classifying remaining descriptions...

100%|██████████| 30887/30887 [10:50<00:00, 47.48it/s]

Overall Accuracy: 5.24%

In [108]:
results_df

,Room Description,Actual_Room_Type,Predicted_Room_Type,Confidence,Correct
0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,Queen Bedroom,0.038105,False
1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,Deluxe Room,0.045132,False
2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,Executive/Club Room,0.042131,False
3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,Queen Bedroom,0.047071,False
4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,Apartment,0.041257,False
...,...,...,...,...,...
30882,BEST FLEXIBLE RATE|PREMIUM OCEAN VIEW ROOM WHE...,Run of the House,Loft,0.065389,False
30883,1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...,Run of the House,Guest Room,0.054472,False
30884,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...,Run of the House,Comfort Room,0.053569,False
30885,GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...,Run of the House,Executive/Club Suite,0.040513,False
30886,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...,Run of the House,Classic Room,0.055917,False

In [109]:
results_df.to_csv('finetuned_bert_base_uncased_1pct.csv', index=False)

## Finetuning BERT on 5% of dataset ##

In [116]:
# Train on full sample dataset
final_model, final_tokenizer = train_final_model(sample_df_5pct, model_name, label2id)

Training final model on all sample data...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_53697/406571484.py:42: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [117]:
# 3. Classify remaining data
#remaining_data = remaining_data
results_df = classify_remaining_data(final_model, final_tokenizer, label2id, remaining_df_5pct)

Classifying remaining descriptions...

100%|██████████| 29487/29487 [11:31<00:00, 42.65it/s]

Overall Accuracy: 92.50%

In [ ]:
results_df.to_csv('finetuned_bert_base_uncased_5pct.csv', index=False)

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...
...,...,...,...,...
29482,31230,TRAVEL LEADERS WORLDWIDE|HOTEL STANDARD ROOMV ...,Run of the House,TRAVEL LEADERS WORLDWIDE|HOTEL STANDARD ROOMV ...
29483,31231,A T AND T INC GOLD|STANDARD NONSMOKING ROOM WH...,Run of the House,A T AND T INC GOLD|STANDARD NONSMOKING ROOM WH...
29484,31234,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...,Run of the House,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...
29485,31235,GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...,Run of the House,GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...
29486,31236,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...,Run of the House,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...

## Finetuning BERT on 10% of dataset ##

In [106]:
# Train on full sample dataset
final_model, final_tokenizer = train_final_model(sample_df_10pct, model_name, label2id)

Training final model on all sample data...

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_21018/406571484.py:42: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
Python(57139) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(57140) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
Python(57143) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(57144) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
wandb: Currently logged in as: karthik1705 (karthik1705-the-university-of-texas-at-austin). Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
Python(57146) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(57147) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Python(57156) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)
/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/torch/utils/data/dataloader.py:682: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [107]:
# 3. Classify remaining data
#remaining_data = remaining_data
results_df = classify_remaining_data(final_model, final_tokenizer, label2id, remaining_df_10pct)

Python(71604) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Classifying remaining descriptions...

  0%|          | 0/27737 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
100%|██████████| 27737/27737 [10:18<00:00, 44.83it/s]

Overall Accuracy: 96.05%

In [113]:
results_df.to_csv('finetuned_bert_base_uncased_10pct.csv', index=False)

In [114]:
results_df

,Room Description,Actual_Room_Type,Predicted_Room_Type,Confidence,Correct
0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,Accessible Room,0.873286,True
1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,Accessible Room,0.802240,True
2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,Accessible Room,0.703507,True
3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,Accessible Room,0.863557,True
4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,Accessible Room,0.683872,True
...,...,...,...,...,...
27732,TRAVEL LEADERS WORLDWIDE|HOTEL STANDARD WHEN Y...,Run of the House,Run of the House,0.910508,True
27733,TRAVEL LEADERS WORLDWIDE|HOTEL STANDARD ROOMV ...,Run of the House,Standard Room,0.754381,False
27734,A T AND T INC GOLD|STANDARD NONSMOKING ROOM WH...,Run of the House,Run of the House,0.919636,True
27735,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...,Run of the House,Run of the House,0.901116,True
27736,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...,Run of the House,Run of the House,0.887471,True

# Classification Report on the Best Model #

In [77]:
from sklearn.metrics import precision_score, recall_score, classification_report

In [ ]:

print(classification_report(results_df['Actual_Room_Type'], results_df['Predicted_Room_Type']))

                      precision    recall  f1-score   support

     Accessible Room       0.94      0.91      0.92       862
           Apartment       0.98      0.98      0.98       859
            Bungalow       0.99      1.00      0.99       878
              Cabana       1.00      0.99      0.99       884
        Classic Room       0.97      0.97      0.97       807
       Classic Suite       0.99      1.00      0.99       746
        Comfort Room       1.00      1.00      1.00       800
             Cottage       1.00      1.00      1.00       900
         Deluxe Room       0.93      0.94      0.93       855
        Deluxe Suite       0.98      0.99      0.98       854
          Double Bed       0.97      0.97      0.97       715
 Executive/Club Room       0.94      0.89      0.91       881
Executive/Club Suite       0.92      0.98      0.95       760
   Family Room/Suite       0.97      0.99      0.98       865
          Guest Room       0.89      0.91      0.90       594
        Junior Suite       0.98      0.98      0.98       822
        King Bedroom       0.97      0.90      0.94       821
                Loft       0.98      0.97      0.98       863
         Luxury Room       0.96      0.99      0.97       858
        Luxury Suite       0.99      0.97      0.98       849
           Penthouse       0.98      1.00      0.99       875
        Premier Room       0.95      0.91      0.93       778
       Premier Suite       0.96      1.00      0.98       557
  Presidential Suite       0.96      0.99      0.98       849
       Queen Bedroom       0.97      0.99      0.98       713
    Run of the House       0.97      0.96      0.96       493
         Single Room       0.99      0.98      0.99       843
       Standard Room       0.93      0.94      0.93       819
         Studio Room       0.74      0.91      0.82       507
        Studio Suite       0.92      0.79      0.85       764
               Suite       0.96      0.87      0.91       887
       Superior Room       0.94      0.97      0.95       864
      Superior Suite       0.99      1.00      1.00       850
           Twin Room       0.96      0.99      0.97       638
               Villa       0.98      0.99      0.99       827

            accuracy                           0.96     27737
           macro avg       0.96      0.96      0.96     27737
        weighted avg       0.96      0.96      0.96     27737

In [80]:
# micro
p_micro = precision_score(results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='micro')
r_micro = recall_score   (results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='micro')

# macro
p_macro = precision_score(results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='macro')
r_macro = recall_score   (results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='macro')

# weighted
p_w = precision_score(results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='weighted')
r_w = recall_score   (results_df['Actual_Room_Type'], results_df['Predicted_Room_Type'], average='weighted')

print(f"Micro P/R: {p_micro:.3f}/{r_micro:.3f}")
print(f"Macro P/R: {p_macro:.3f}/{r_macro:.3f}")
print(f"Weighted P/R: {p_w:.3f}/{r_w:.3f}")

Micro P/R: 0.961/0.961
Macro P/R: 0.958/0.960
Weighted P/R: 0.962/0.961