In [3]:
import pandas as pd
import re

In [4]:
# Prep data for attribute extraction
dataset_normalized_attributes = pd.read_excel('../Data/Normalized_product_attribute_name.xlsx', sheet_name = 'Normalized Product Attributes')
dataset_normalized_attributes

,BedType,OTA TYPE = BED,Unnamed: 2,RoomType,OTA TYPE = GRI,Unnamed: 5,Rateplan Incl/Value-adds,OTA TYPE = HAC,Unnamed: 8,Room Amenities,OTA TYPE = RMA,Unnamed: 11,Mealplan,OTA TYPE = MPT,Unnamed: 14,RoomView,OTA TYPE = RVT,Unnamed: 17,Taxes & Fees,OTA TYPE = FTT
0,Double/Full Bed,1.0,NaN,Accessible Room,1.0,NaN,Piano,0,NaN,Adjoining rooms,1.0,NaN,All Inclusive,1.0,NaN,Airport view,1.0,NaN,Bed tax,1.0
1,Futon Bed,2.0,NaN,Suite,3.0,NaN,24-hour front desk,1,NaN,Air conditioning,2.0,NaN,Full Board or American,2.0,NaN,Bay view,2.0,NaN,City hotel fee,2.0
2,King Bed,3.0,NaN,Executive/Club Suite,6.0,NaN,24-hour room service,2,NaN,Alarm clock,3.0,NaN,Buffet Breakfast,4.0,NaN,City view,3.0,NaN,PropertyFee,2.0
3,Murphy Bed,4.0,NaN,Double Room,10.0,NaN,24-hour security,3,NaN,All news channel,4.0,NaN,Continental Breakfast,6.0,NaN,Courtyard view,4.0,NaN,City tax,3.0
4,Queen Bed,5.0,NaN,King Bedroom,11.0,NaN,adjoining rooms,4,NaN,radio,5.0,NaN,Family Plan,9.0,NaN,Golf View,5.0,NaN,Municipal Tax,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,NaN,NaN,NaN,NaN,NaN,NaN,Train station shuttle services,2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,NaN,NaN,NaN,NaN,NaN,NaN,Electric car charging stations,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,Golf clubs (equipments),2032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,NaN,NaN,NaN,NaN,NaN,NaN,Beach club,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,NaN,NaN,NaN,NaN,NaN,NaN,Theme park shuttle,2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()

bed_types = dataset_normalized_attributes['BedType'].dropna().unique()
bed_types_list = bed_types.tolist()

room_amenities = dataset_normalized_attributes['Room Amenities'].dropna().unique()
room_amenities_list = room_amenities.tolist()

In [5]:
room_types_list

['Accessible Room ',
 'Suite',
 'Executive/Club Suite',
 'Double Room ',
 'King Bedroom',
 'Apartment',
 'Queen Bedroom',
 'Penthouse',
 'Studio Suite',
 'Twin Room',
 'Family Room/Suite',
 'Cabin',
 'Cottage',
 'Loft',
 'Guest Room',
 'Bungalow',
 'Villa',
 'Junior Suite',
 'Run of the House',
 'Large/Master Suite',
 'Executive/Club Room',
 'Classic Room',
 'Comfort Room',
 'Deluxe Room',
 'Deluxe Suite',
 'Economy Room',
 'Luxury Suite',
 'Premier Room',
 'Standard Guest Room',
 'Superior Room',
 'Superior Suite',
 'Grand Room',
 'Premier Suite',
 'Luxury Room',
 'Classic Suite',
 'Presidential Suite',
 'Single Room',
 'Triple Room',
 'Quadruple Room',
 'Studio Room',
 'Cabana',
 'Privilege Room',
 'Prestige Room',
 'Corner Room',
 'Signature Room',
 'Traditional Room ',
 'Wellness Room',
 'Terrace Room',
 'Tower Room',
 'Heritage Room',
 'Urban Room']

In [6]:
bed_types_list

['Double/Full Bed',
 'Futon Bed',
 'King Bed',
 'Murphy Bed',
 'Queen Bed',
 'Sofa Bed',
 'Twin/Single Bed',
 'Single Bed',
 'Run of the house',
 'Dorm/Bunk Bed',
 'Water Bed']

In [7]:
room_amenities_list

['Adjoining rooms',
 'Air conditioning',
 'Alarm clock',
 'All news channel',
 'radio',
 'Baby listening device',
 'balcony',
 'Barbeque grills',
 'Bathtub with spray jets',
 'Bathrobe',
 'Bathroom amenities',
 'Bathroom telephone',
 'Bathtub',
 'Bathtub only',
 'Bathtub & shower',
 'Bidet',
 'Bottled water',
 'Cable television',
 'Coffee maker',
 'Color television',
 'Computer',
 'Connecting rooms',
 'electric converters ',
 'Copier',
 'Cordless phone',
 'Cribs',
 'Data port',
 'Desk',
 'Desk with lamp',
 'Dining guide',
 'Direct dial phone number',
 'Dishwasher',
 'Double beds',
 'Dual voltage outlet',
 'Electrical current voltage',
 'Ergonomic chair',
 'Extended phone cord',
 'Fax machine',
 'Fire alarm',
 'Fire alarm with light',
 'Fireplace',
 'Free toll free calls',
 'Free calls',
 'Free credit card access calls',
 'Free local calls',
 'Free movies',
 'Full kitchen',
 'Grab bars in bathroom',
 'Grecian tub',
 'Hairdryer',
 'High speed internet connection',
 'Interactive web TV',
 'International direct dialing',
 'Internet access',
 'Iron',
 'Ironing board',
 'Whirlpool',
 'King bed',
 'Kitchen',
 'Kitchen supplies',
 'Kitchenette',
 'Knock light',
 'Laptop',
 'Large desk',
 'Large work area',
 'Laundry basket',
 'Loft',
 'Microwave',
 'Minibar',
 'Modem',
 'Modem jack',
 'Multi-line phone',
 'Newspaper',
 'Non-smoking',
 'Notepads',
 'Office supplies',
 'Oven',
 'Pay per view movies on TV',
 'Pens',
 'Phone in bathroom',
 'Plates and bowls',
 'Pots and pans',
 'Prayer mats',
 'Printer',
 'Private bathroom',
 'Queen bed',
 'Recliner',
 'Refrigerator',
 'Refrigerator with ice maker',
 'Remote control television',
 'Rollaway bed',
 'Safe',
 'Scanner',
 'Separate closet',
 'Separate modem line available',
 'Shoe polisher',
 'Shower only',
 'Silverware',
 'Sitting area',
 'Smoke detectors',
 'Smoking',
 'Sofa bed',
 'Speaker phone',
 'Stereo',
 'Stove',
 'Tape recorder',
 'Telephone',
 'Telephone for hearing impaired',
 'Telephones with message light',
 'Toaster oven',
 'Trouser press',
 'Turn down service',
 'Twin bed',
 'Vaulted ceilings',
 'VCR movies',
 'VCR player',
 'Video games',
 'Voice mail',
 'Wake-up calls',
 'Water closet',
 'Water purification system',
 'Wet bar',
 'Wireless internet connection',
 'Wireless keyboard',
 'Adaptor available for telephone PC use',
 'Air conditioning individually controlled in room',
 'Bathtub & whirlpool',
 'Telephone with data ports',
 'CD player',
 'Complimentary local calls time limit',
 'Extra person charge for rollaway use',
 'feather pillows',
 'Desk with electrical outlet',
 'ESPN available',
 'Foam pillows',
 'HBO available',
 'High ceilings',
 'Marble bathroom',
 'List of movie channels available',
 'Pets allowed',
 'Oversized bathtub',
 'Shower',
 'Sink in-room',
 'Soundproofed room',
 'Storage space',
 'Tables and chairs',
 'Two-line phone',
 'Walk-in closet',
 'Washer dryer',
 'Weight scale',
 'Welcome gift',
 'Spare electrical outlet available at desk',
 'Non refundable charge for pets',
 'Refundable deposit for pets',
 'Separate tub and shower',
 'Entrance type to guest room',
 'Ceiling fan',
 'CNN available',
 'Electrical adaptors available',
 'Buffet breakfast',
 'Accessible room',
 'Closets in room',
 'DVD player',
 'Mini refrigerator',
 'Separate line billing for multi-line phone',
 'Self-controlled heating/cooling system',
 'Toaster',
 'Analog data port',
 'Collect calls',
 'International calls',
 'Carrier access',
 'Interstate calls',
 'Intrastate calls',
 'Local calls',
 'Long distance calls',
 'Operator assisted calls',
 'Credit card access calls',
 'Calling card calls',
 'Toll free calls',
 'Universal adaptors',
 'Bathtub seat',
 'Canopy',
 'glassware',
 'Entertainment center',
 'Family room',
 'Hypoallergenic bed',
 'Hypoallergenic pillows',
 'Lamp',
 'Meal included - breakfast',
 'Meal included - continental breakfast',
 'Meal included - dinner',
 'Meal included - lunch',
 'Shared bathroom',
 'Textphone',
 'Water bed',
 'Extra adult charge',
 'Extra child charge',
 'Extra child charge for rollaway use',
 'Meal included: full American breakfast',
 'Futon',
 'Murphy bed',
 'Tatami mats',
 'Single bed',
 'Annex room',
 'Free newspaper',
 'Honeymoon suites',
 'Complimentary high speed internet in room',
 'Maid service',
 'PC hook-up in room',
 'Satellite television',
 'VIP rooms',
 'Cell phone recharger',
 'DVR player',
 'iPod docking station',
 'Media center',
 'Plug & play panel',
 'Satellite radio',
 'Video on demand',
 'Exterior corridors',
 'Gulf view',
 'Interior corridors',
 'Mountain view',
 'Ocean view',
 'High speed internet access for fee',
 'High speed wireless',
 'Premium movie channels',
 'Slippers',
 "First nighters' kit",
 'Chair provided with desk',
 'Pillow top mattress',
 'Feather bed',
 'Duvet',
 'Luxury linen type',
 'International channels',
 'Pantry',
 'Dish-cleaning supplies',
 'Double vanity',
 'Lighted makeup mirror',
 'Upgraded bathroom amenities',
 'VCR player available at front desk',
 'Instant hot water',
 'Outdoor space',
 'Hinoki tub',
 'Private pool',
 'High Definition (HD) Flat Panel Television - 32 inches or greater',
 'Room windows open',
 'Bedding type unknown or unspecified',
 'Full bed',
 'Round bed',
 'TV',
 'Child rollaway',
 'DVD player available at front desk',
 'Video game player:',
 'Video game player available at front desk',
 'Dining room seats',
 'Full size mirror',
 'Mobile/cellular phones',
 'Movies',
 'Multiple closets',
 'Plates/glassware',
 'Safe large enough to accommodate a laptop',
 'Bed linen thread count',
 'Blackout curtain',
 'Bluray player',
 'Device with mp3',
 'No adult channels or adult channel lock',
 'Non-allergenic room',
 'Pillow type',
 'Seating area with sofa/chair',
 'Separate toilet area',
 'Web enabled',
 'Widescreen TV',
 'Other data connection',
 'Phoneline billed separately',
 'Separate tub or shower',
 'Roof ventilator',
 "Children's playpen",
 'Plunge pool',
 'DVD movies',
 'Air filtration',
 'Exercise Equipment in Room',
 'Towels Sheets',
 'Electric Kettle',
 'Portable Fan',
 'Washing Machine',
 'Towels Provided',
 'Smart TV',
 'Streaming Services',
 'Highchair',
 'Toilet with electronic bidet',
 'Free tea bags instant coffee',
 'Outdoor Shower',
 'Baby bath',
 'Changing table',
 'Heating/Heated floor',
 'Indoor private mineral hot springs (japanese style onsen)',
 'Freezer',
 'Ice maker',
 'In room childcare',
 'Digital TV serviceWired Internet Access',
 'Wired Internet Access',
 'Pillow Menu',
 'Room Size(Square feet)',
 'Room Size (Square meters)',
 'Cleaning Supplies',
 'Dryer',
 'Tatami (Woven mat) floors',
 'Private spa tub',
 'Cookware, dishware, and utensils']

In [6]:
dataset = pd.read_csv('../Data/Product_Normalization_GRI_Expanded.csv')
dataset.head()

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...

In [10]:
sampled_descriptions = dataset.groupby('Guest Room Info').apply(
    lambda x: x['Room Description Expanded'].sample()
)

print(sampled_descriptions)

Guest Room Info
Accessible Room       513      1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...
Apartment             32722    BEST AVAILABLE RATE|TWO BEDROOM APARTMENT - 2X...
Bungalow              13752    BEST FLEXIBLE RATE|1 DOUBLE OVERWATER HORIZON ...
Cabana                31263    CWT PROGRAM -HONORS DISCOUNT|POOL SIDE CABANA ...
Classic Room          17501    MRATE AVAIL BOOK WITH CONFIDEN|FAMILY CLASSIC ...
Classic Suite         27717    NOT REFUNDABLE RATE BB|CLASSIC SUITE AC-WIFI-S...
Comfort Room          18998    SPECIAL RATE - NON REFUNDABLE|COMFORT ROOM-BAT...
Cottage               10580    CWT PROGRAM -PREFERRED|COTTAGE ROOM - PATIO FI...
Deluxe Room           19806    BED BREAKFAST AND MORE|DELUXE ROOM CITY VIEW K...
Deluxe Suite          20622    ROCCO FORTE FAMILY EXPERIENCE|DELUXE SUITE - 1...
Double Bed            3496     TRAVEL LEADERS WORLDWIDE|HOTEL COMP WIFI AND 2...
Executive/Club Room   16960    BEST AVAILABLE RATE|1 KING BED EXECUTIVE WITH ...
Executive/Club Suite  2507     EAT. DRINK. OUR TREAT|EXECUTIVE SUITE.1 KING.4...
Family Room/Suite     9680     FREE PARKING. BREAKFAST INCLUD|FAMILY ROOM TRI...
Guest Room            12457    PREPAY NONREF NO CHNG|PREPAY NON-REFUNDABLE NO...
Junior Suite          15034    MRATE AVAIL BOOK WITH CONFIDEN|JUNIOR SUITE, D...
King Bedroom          4511     ABC GLOBAL SERVICES|DUMBO KING BED ROOM 300 SQ...
Loft                  11638    BEST FLEXIBLE RATE|1 KNG LOFT VILLA MARINA VIE...
Luxury Room           26609                   BCD TRAVEL|LUXURY ROOM, 1 KING BED
Luxury Suite          33990    BOOK AHEAD - BED - BREAKFAST|LUXURY SUITE  - 1...
Penthouse             6248     BEST FLEX RATE -NO HIDDEN FEES|PENTHOUSE SUITE...
Premier Room          21815    FREE PARKING. BREAKFAST INCLUD|PREMIUM WITHVIE...
Premier Suite         25783    FLEXIBLE RATE|2 ROOM PREMIUM SUITE-2 DOUBLE BE...
Presidential Suite    28105    FLEXIBLE RATE|PRESIDENTIAL SUITE WITH SKYLINE ...
Queen Bedroom         5505     ADVANCE SAVER|2 QUEEN STANDARD 265 SQUARE FOOT...
Run of the House      34187    ADVANCE SAVER|SPECIALTY ROOM WHEN YOU ARRIVE A...
Single Room           29494    BEST AVAILABLE RATE|SINGLE ROOM- 11-12 SQM- DO...
Standard Room         22860    1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...
Studio Room           30209    BREAKFAST INCLUSIVE - FLEXIBLE|EXECUTIVE STUDI...
Studio Suite          7032     SEMI-FLEX|1 KING BED STUDIO SUITE NONSMOKING F...
Suite                 1228     AAA|OCEAN FRONT 2 BEDROOM SUITE BALCONY-1700SQ...
Superior Room         23028    FLEXIBLE RATE|KING SUPERIOR ROOM 107M2 SPACIOU...
Superior Suite        24890    GBT INCL BREAKFAST|1 BEDROOM SUPERIOR SUITE-QU...
Twin Room             8225     CLUB IC RATE INCLUDES CLUB|INTERCONTINENTAL LO...
Villa                 14331    TRIPADVISOR PLUS|VICE REGAL VILLA 1- KING BED-...
Name: Room Description Expanded, dtype: object

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_35600/120762231.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_descriptions = dataset.groupby('Guest Room Info').apply(

## Basic RegEx type extraction test ##

In [11]:
# Tagging based on manually defined patterns
def extract_key_phrases(texts):
    patterns = {
        'bed_type': r'\b(?:KG|KING|QN|QUEEN|DBL|DOUBLE|TWN|TWIN|SGL|SINGLE)\b',
        'room_type': r'\b(?:STE|SUITE|RM|ROOM|EXEC|EXECUTIVE)\b',
        'amenities': r'\b(?:BALCONY|WIFI|HDTV|WET-BAR)\b',
        'accessibility': r'\b(?:ACCESS|MOB|HEAR)\b',
        'size': r'\b\d+\s*(?:SQ\s*FT|SQFT)\b'
    }
    
    results = []
    for text in texts:
        matches = {}
        for attr_type, pattern in patterns.items():
            matches[attr_type] = re.findall(pattern, text.upper())
        results.append(matches)
    
    return pd.DataFrame(results)

In [12]:
# Test with sample descriptions
sample_texts = [
    'SEMI-FLEX|1 KG EXEC LVL 2-RM STE MOB/HEAR RI SH ACCESS VIS FIREALRM/DOOR/PHN ALRT - WIFI - 55IN HDTV',
    'TRIPADVISOR PLUS RATE|DOUBLE QUEEN SUITE WITH BALCONY - 500 SQ FT - TWO QUEEN BEDS - GRANITE WET-BAR - UPPER FLOOR'
]

extracted_phrases = extract_key_phrases(sample_texts)
print(extracted_phrases)

                 bed_type        room_type           amenities  \
0                    [KG]  [EXEC, RM, STE]        [WIFI, HDTV]
1  [DOUBLE, QUEEN, QUEEN]          [SUITE]  [BALCONY, WET-BAR]

         accessibility         size
0  [MOB, HEAR, ACCESS]           []
1                   []  [500 SQ FT]

In [7]:
# Create regex patterns from our list of attributes
def create_pattern_from_list(attribute_list):
    """Convert list of attributes into regex patterns including common abbreviations"""
    patterns = set()
    
    for attr in attribute_list:
        if pd.isna(attr):
            continue
            
        # Convert to string and uppercase
        attr = str(attr).upper().strip()
        
        # Split on spaces and camelCase
        # First split on spaces
        space_split = attr.split()
        
        # Then handle camelCase within each part
        words = []
        for part in space_split:
            camel_split = re.findall('[A-Z][^A-Z]*', part)
            if camel_split:
                words.extend(camel_split)
            else:
                words.append(part)
        
        # Add full original term (without spaces)
        patterns.add(attr.replace(' ', ''))
        
        # Add space-separated version if multiple words
        if len(space_split) > 1:
            patterns.add(attr)
        
        # Add common abbreviations for multi-word terms
        if len(words) > 1:
            abbrev = ''.join(word[0] for word in words)
            if len(abbrev) > 1:  # Only add if abbreviation is at least 2 chars
                patterns.add(abbrev)
        
        # Add common shortenings (only for words longer than 3 chars)
        for word in words:
            if len(word) > 3:
                patterns.add(word[:3])
        
        # Add the full individual words (if they're longer than 2 chars)
        patterns.update(word for word in words if len(word) > 2)
    
    # Sort patterns by length (longest first) to ensure longer matches take precedence
    patterns = sorted(patterns, key=len, reverse=True)
    
    return r'\b(?:' + '|'.join(patterns) + r')\b'

In [8]:
create_pattern_from_list(room_types_list)

'\\b(?:EXECUTIVE/CLUB SUITE|EXECUTIVE/CLUBSUITE|EXECUTIVE/CLUB ROOM|STANDARD GUEST ROOM|PRESIDENTIAL SUITE|EXECUTIVE/CLUBROOM|LARGE/MASTER SUITE|EXECUTIVECLUBSUITE|EXECUTIVECLUBROOM|STANDARDGUESTROOM|LARGE/MASTERSUITE|FAMILY ROOM/SUITE|PRESIDENTIALSUITE|LARGEMASTERSUITE|RUN OF THE HOUSE|FAMILYROOM/SUITE|TRADITIONAL ROOM|TRADITIONALROOM|ACCESSIBLE ROOM|FAMILYROOMSUITE|ACCESSIBLEROOM|QUADRUPLE ROOM|PRIVILEGE ROOM|SUPERIOR SUITE|SIGNATURE ROOM|PRIVILEGEROOM|SUPERIOR ROOM|SUPERIORSUITE|WELLNESS ROOM|PREMIER SUITE|QUEEN BEDROOM|HERITAGE ROOM|RUNOFTHEHOUSE|QUADRUPLEROOM|SIGNATUREROOM|CLASSIC SUITE|PRESTIGE ROOM|PREMIER ROOM|QUEENBEDROOM|PREMIERSUITE|JUNIOR SUITE|WELLNESSROOM|SUPERIORROOM|DELUXE SUITE|PRESTIGEROOM|TERRACE ROOM|STUDIO SUITE|LUXURY SUITE|KING BEDROOM|HERITAGEROOM|CLASSICSUITE|ECONOMY ROOM|CLASSIC ROOM|COMFORT ROOM|KINGBEDROOM|JUNIORSUITE|LUXURYSUITE|STUDIO ROOM|DELUXESUITE|PREMIERROOM|CLASSICROOM|STUDIOSUITE|ECONOMYROOM|COMFORTROOM|TRIPLE ROOM|LUXURY ROOM|DELUXE ROOM|TERRACEROOM|SINGLE ROOM|CORNER ROOM|DOUBLE ROOM|GUEST ROOM|STUDIOROOM|DOUBLEROOM|TOWER ROOM|DELUXEROOM|CORNERROOM|LUXURYROOM|GRAND ROOM|SINGLEROOM|TRIPLEROOM|URBAN ROOM|URBANROOM|APARTMENT|PENTHOUSE|TWIN ROOM|GUESTROOM|TOWERROOM|GRANDROOM|BUNGALOW|TWINROOM|COTTAGE|CABANA|SUITE|CABIN|VILLA|LOFT)\\b'

In [9]:

def extract_key_phrases(texts, room_types_list, bed_types_list): # amenities_list):
    
    patterns = {
        'bed_type': create_pattern_from_list(bed_types_list),
        'room_type': create_pattern_from_list(room_types_list)#,
        #'amenities': create_pattern_from_list(amenities_list),
        #'accessibility': r'\b(?:ACCESS|MOB|HEAR)\b',
        #'size': r'\b\d+\s*(?:SQ\s*FT|SQFT)\b'
    }
    
    results = []
    for text in texts:
        matches = {}
        for attr_type, pattern in patterns.items():
            matches[attr_type] = re.findall(pattern, text.upper())
        results.append(matches)
    
    return pd.DataFrame(results)

In [10]:
#Test with sample descriptions
sample_texts = [
    'SEMI-FLEX|1 KG EXEC LVL 2-RM STE MOB/HEAR RI SH ACCESS VIS FIREALRM/DOOR/PHN ALRT - WIFI - 55IN HDTV',
    'TRIPADVISOR PLUS RATE|DOUBLE QUEEN SUITE WITH BALCONY - 500 SQ FT - TWO QUEEN BEDS - GRANITE WET-BAR - UPPER FLOOR'
]

extracted_phrases = extract_key_phrases(sample_texts, room_types_list, bed_types_list) #, room_amenities_list)
print(extracted_phrases)

  bed_type room_type
0       []        []
1       []   [SUITE]

In [11]:
# Sample texts with their labels and calculate accuracy
def evaluate_extraction_accuracy(dataset, sample_size=100):
    # Sample from dataset
    sampled_data = dataset.groupby('Guest Room Info').apply(
        lambda x: pd.DataFrame({
            'Room Description': x['Room Description Expanded'].sample(min(3, len(x))),
            'Guest Room Info': x.name
        })
    ).reset_index(drop=True)
    
    # Extract attributes
    extracted_results = extract_key_phrases(
        sampled_data['Room Description Expanded'].tolist(), 
        room_types_list, 
        bed_types_list
    )
    
    # Calculate accuracy
    correct = 0
    total = len(sampled_data)
    
    for i, row in sampled_data.iterrows():
        true_label = row['Guest Room Info']
        predicted_types = extracted_results.iloc[i]['room_type']
        
        # Convert to uppercase for comparison
        if any(true_label.upper() in pred.upper() for pred in predicted_types):
            correct += 1
    
    accuracy = correct / total
    print(f"\nAccuracy: {accuracy:.2%}")
    
    # Print some examples
    print("\nSample Predictions:")
    for i in range(min(5, len(sampled_data))):
        print(f"\nDescription: {sampled_data.iloc[i]['Room Description Expanded']}")
        print(f"True Label: {sampled_data.iloc[i]['Guest Room Info']}")
        print(f"Predicted: {extracted_results.iloc[i]['room_type']}")
    
    return accuracy, sampled_data, extracted_results

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...
...,...,...,...,...
34995,34995,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...,Run of the House,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...
34996,34996,STAY LONGER SAVE|SPECIALTY ROOM WHEN YOU ARRIV...,Run of the House,STAY LONGER SAVE|SPECIALTY ROOM WHEN YOU ARRIV...
34997,34997,CWT|SPECIALTY ROOM WHEN YOU ARRIVE AT THE HOTE...,Run of the House,CWT|SPECIALTY ROOM WHEN YOU ARRIVE AT THE HOTE...
34998,34998,"BOOK NOW, PAY LATER|DELUXE ROOM AN UPGRADE FRO...",Run of the House,"BOOK NOW, PAY LATER|DELUXE ROOM AN UPGRADE FRO..."
34999,34999,BEST FLEXIBLE RATE|SPECIALTY ROOM BED TYPE CAN...,Run of the House,BEST FLEXIBLE RATE|SPECIALTY ROOM BED TYPE CAN...

In [87]:
evaluate_extraction_accuracy(dataset)

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_87030/3298363396.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = dataset.groupby('Guest Room Info').apply(

Accuracy: 57.14%

Sample Predictions:

Description: BEST AVAILABLE RATE FLEXIBLE|1 KING ACCESSIBLE SUITE NSMK WITH FREE WIFI, FREE BUFFET BREAKFAST, SOFA BED, BATHTUB
True Label: Accessible Room
Predicted: ['SUITE']

Description: 2X POINTS|1 KING MOBILITY ACCESSIBLE W/ROLL IN SHOWER COMP WIFI- BED WITH ADJUSTABLE FIRMNESS DIAL
True Label: Accessible Room
Predicted: ['W']

Description: AAA RATE|1 KING ACCESSIBLE SUITE NSMK WITH FREE WIFI, FREE BUFFET BREAKFAST, SOFA BED, BATHTUB
True Label: Accessible Room
Predicted: ['SUITE']

Description: MRATE AVAIL FLEXIBLE RATE - BB|STANDARD APARTMENT WITH TWIN BEDS
True Label: Apartment
Predicted: ['APARTMENT']

Description: GOVERNMENT RATE|EMPLOYEE ID REQUIRED AT CHECK IN 1 BEDROOM APARTMENT, 1 KING BED, CITY DELUXE
True Label: Apartment
Predicted: ['APARTMENT']

(0.5714285714285714,
                                       Room Description  Guest Room Info
 0    BEST AVAILABLE RATE FLEXIBLE|1 KING ACCESSIBLE...  Accessible Room
 1    2X POINTS|1 KING MOBILITY ACCESSIBLE W/ROLL IN...  Accessible Room
 2    AAA RATE|1 KING ACCESSIBLE SUITE NSMK WITH FRE...  Accessible Room
 3    MRATE AVAIL FLEXIBLE RATE - BB|STANDARD APARTM...        Apartment
 4    GOVERNMENT RATE|EMPLOYEE ID REQUIRED AT CHECK ...        Apartment
 ..                                                 ...              ...
 100  AIRPORT STOPOVER BY HOTELREZ|TWIN ROOM NO WIND...        Twin Room
 101  BEST AVAILABLE RATE|TWIN ROOM NON SMOKING FREE...        Twin Room
 102  MEMBR PREPAY NONREF|SEE RATE DETAILS, 1 BEDROO...            Villa
 103  BED AND BREAKFAST|SOUTH CHINA SEA POOL VILLA -...            Villa
 104  PENINSULA PREMIER RATE|VILLA STUDIO-1KING-GARD...            Villa

 [105 rows x 2 columns],
        bed_type    room_type
 0    [SOFA BED]      [SUITE]
 1           [W]          [W]
 2    [SOFA BED]      [SUITE]
 3            []  [APARTMENT]
 4    [KING BED]  [APARTMENT]
 ..          ...          ...
 100          []  [TWIN ROOM]
 101          []  [TWIN ROOM]
 102  [SOFA BED]      [VILLA]
 103          []      [VILLA]
 104          []      [VILLA]

 [105 rows x 2 columns])

SPaCy

In [43]:
import spacy
from collections import defaultdict
from tqdm import tqdm

/Users/karthik1705/Desktop/Projects/Sabre 2025/LLM Attribute Normalization/distiLLM/llm/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

def preprocess_pattern_list(pattern_list):
    """
    Convert camelCase/PascalCase patterns to lowercase and split into individual words
    Example: 'KingBed' -> ['king', 'bed']
    """
    processed = []
    for pattern in pattern_list:
        # Handle NaN values and empty strings
        if pd.isna(pattern) or str(pattern).strip() == '':
            continue
            
        # Convert to string and strip whitespace
        pattern = str(pattern).strip()
        
        # Split camelCase/PascalCase
        words = re.findall('[A-Z][^A-Z]*', pattern)
        
        # Only add non-empty patterns
        if words:  # If words were found by the regex
            processed_pattern = ' '.join(word.lower() for word in words).strip()
            if processed_pattern:  # If the result isn't empty
                processed.append(processed_pattern)
        else:  # If no camelCase/PascalCase found, just lowercase the whole thing
            if pattern:  # If pattern isn't empty
                processed.append(pattern.lower().strip())
    
    # Remove duplicates and empty strings
    return [p for p in list(set(processed)) if p.strip()]

In [59]:
# Function to clean and tokenize text
def clean_text(texts):
    cleaned_texts = []
    for text in texts:
        if pd.isna(text):  # Handle NaN values
            cleaned_texts.append("")
            continue
            
        # Convert to lowercase
        text = text.lower()
        
        # Replace specific compound terms
        compound_terms = {
            'bed room': 'bedroom'
        }
        
        for term, replacement in compound_terms.items():
            text = text.replace(term, replacement)
            
        cleaned_texts.append(text)
    
    return cleaned_texts

In [64]:
# SPaCy - Extract attributes using spaCy
def analyze_with_spacy(texts):
    # Load transformer-based English model
    try:
        nlp = spacy.load("en_core_web_trf")
    except OSError:
        print("Downloading en_core_web_trf model...")
        spacy.cli.download("en_core_web_trf")
        nlp = spacy.load("en_core_web_trf")
    
    # Preprocess the pattern lists
    processed_room_types = [room_type.lower() for room_type in room_types_list]
    processed_bed_types = [bed_type.lower() for bed_type in bed_types_list]
    #processed_room_views = room_view_list
    #processed_amenities = room_amenities_list
    
    # Custom labels for hospitality domain
    room_patterns = [
        {"label": "ROOM_TYPE", "pattern": [{"LOWER": {"IN": processed_room_types}}]},
        {"label": "BED_TYPE", "pattern": [{"LOWER": {"IN": processed_bed_types}}]}#,
        #{"label": "VIEW_TYPE", "pattern": [
        #    {"LOWER": {"IN": processed_room_views}},
        #    {"LOWER": "view", "OP": "?"}
        #]},
        #{"label": "AMENITY", "pattern": [{"LOWER": {"IN": processed_amenities}}]}
    ]
    
    # Add patterns to pipeline
    if "entity_ruler" not in nlp.pipe_names:
        ruler = nlp.add_pipe("entity_ruler", before="ner")
    else:
        ruler = nlp.get_pipe("entity_ruler")
    ruler.add_patterns(room_patterns)
    
    results = defaultdict(list)
    
    # Process each text with batch processing for better performance
    batch_size = 32  # Adjusting a random number based on potential available RAM
    for i in tqdm(range(0, len(texts), batch_size), desc="Processing with spaCy"):
        batch_texts = texts[i:i + batch_size]
        batch_texts = [text if pd.notna(text) else "" for text in batch_texts]
        
        # Process batch
        docs = nlp.pipe(batch_texts)
        
        for doc in docs:
            entities = {
                "text": doc.text,
                "room_types": [],
                "bed_types": [],
                #"view_types": [],
                #"amenities": [],
                "other_entities": []
            }
            
            for ent in doc.ents:
                if ent.label_ == "ROOM_TYPE":
                    entities["room_types"].append(ent.text.lower())
                elif ent.label_ == "BED_TYPE":
                    entities["bed_types"].append(ent.text.lower())
                #elif ent.label_ == "VIEW_TYPE":
                #    entities["view_types"].append(ent.text.lower())
                #elif ent.label_ == "AMENITY":
                #    entities["amenities"].append(ent.text.lower())
                else:
                    entities["other_entities"].append((ent.text.lower(), ent.label_))
            
            for key, value in entities.items():
                results[key].append(value)
    
    return pd.DataFrame(results)

In [56]:
for text in sampled_descriptions:
    print(clean_text(text))

aaa / caa member rate|mobility/hearing accessible deluxe king roll-in shower
flexible rate|deluxe one king bedroom harbour view apartment
lincoln rejuvenation|bungalow king- 520-685 sq.ft. generously sized rooms with furnished private courtyard
magellan 20pct comm. promotion|cabana non-view room - 1 king bed-350 sq.ft. room is near pool and bar
government rate verify rate.|per diem rate is not available on most dates. 1 queen classic averaging 325 sqft with shower and tub, oversized work desk, in-room safe and a nespresso machine.
1 travel leaders select hotels|classic suite -1 king bed - avg 65sqm 699sqf living room - free wifi
regular rate - ro -|comfort room with twin beds, 26 sqm
military family rate|1 king bed cottage 25usd rsrt chg comp wifi- hdtv w/hidef
standard rate 2 queen deluxe|deluxe room w/2 queen beds:
flexible rate|1kng dlx suite mobility/hearing access tub vis firealrm/door/phn alrt
corporate - bed and breakfast|double room double room corp bnb
2x points|2 queen beds executive floor step-out balcny lounge access w/contl brkfst-thomas roth ame
aaa hot deals|aaa caa hot deals, membership card required, executive suite, 1 king, sofa bed
best available rate|king family room comp wifi/mini fridge/pull-out sofa/33 sqm
regular rate|flexible rate, guest room, 1 king
cwt program -honors semi-flex|king junior suite wifi/living area w/sofa/bathtub-walkin shower
you deserve some credit|liberty king bed rm 300 sq ft.
catholic education office darw|1 bedroom queen and sofa townhouse loft style townhouse - courtyard - kitchenette
mrate avail savor, the french|luxury room, 1 king size bed or 2 single size b eds, square or garden view
2x points|1 king tower luxury suite grand river view 615 sq ft - parlor - sofabed - fridge - 2 tvs
daily parking pkg package|includes room accommodations and parking for king bed penthouse suite nonsmoking relax in private in our king bed suite. this spacious room offers a comfortable king
aaa discount|2 doubles premium bay view room nsmk with free wifi, balcony, fridge, hdtv
flexible rate|1 king bed two room premium suite premium wifi-in suite refreshment snack tray
best available rate|presidential suite king 1000sqf93sqm harbor v iew terrace livingdining room
aaa american auto assn|aaa caa rate, membership card required, queen/queen room, guest room, 2 queen
5000 rc bonus includes room|and 5000 rc bonus points per any consecutive club intercontinental room when you arrive we will do our best to meet your rm bd type and smoking preferences. rms
flexible dinner and breakfast|single room - single bed and en-suite bathroom free wifi-flat screen tv-kettle-desk
5000 rc bonus includes room|and 5000 rc bonus points per any consecutive standard room when you arrive at the hotel we will do our best to meet your room type preference this is subject to
experience bus. pack.|pawfect vacation - pet package, studio, 1 king, sofa bed
aaa/aarp rate|studio ste 1k-panoramic view-spacious seating- molton brown bath-nespresso-smart tv-freewifi
aaa|park avenue suite.1150 sqft.free wifi.2 bdrms mstr 1 kg bd.2 dbl bds in 2nd room.living rm
prepaid - level 01|superior room - panoramic view
state government official trvl|1 king bedroom king superior suite robes/slippers - 55 inch hdtv - 1300 sq ft
standard plan.standard|budget room: budget non-smoking twin room 21 sq m.with bathroom and toilet/non smoking. breakfast included airport: 10.923 km, last name: sendai airport  sdj , travel time by public transport: 0 min, iata code: sdj airport: 58.233 km, last name: yamagata airport  gaj , travel time by public transport: 0 min, iata code: sdj airport: 113.39 km, last name: shonai airport  syo yamagata   , travel time by public transport: 0 min city/town center: 0.449 km, last name: sendai, travel time by public transport: 0 min central train station: 0.317 km, last name: sendai, travel time by public transport: 0 min fridge iron   ironing board breakfast restaurant s  1, closed public internet terminal laundry service washing machine for guests store/mini supermarket total number of rooms: 223 reception manned 24 hours a day hairdryer easy access for wheelchairs cable tv fax connection wlan with internet access in rooms
regular rate|flexible rate, 1 bedroom villa, 1 king, sofa bed, island view, balcony

In [60]:
clean_text(sampled_descriptions)

['aaa / caa member rate|mobility/hearing accessible deluxe king roll-in shower',
 'flexible rate|deluxe one king bedroom harbour view apartment',
 'lincoln rejuvenation|bungalow king- 520-685 sq.ft. generously sized rooms with furnished private courtyard',
 'magellan 20pct comm. promotion|cabana non-view room - 1 king bed-350 sq.ft. room is near pool and bar',
 'government rate verify rate.|per diem rate is not available on most dates. 1 queen classic averaging 325 sqft with shower and tub, oversized work desk, in-room safe and a nespresso machine.',
 '1 travel leaders select hotels|classic suite -1 king bed - avg 65sqm 699sqf living room - free wifi',
 'regular rate - ro -|comfort room with twin beds, 26 sqm',
 'military family rate|1 king bed cottage 25usd rsrt chg comp wifi- hdtv w/hidef',
 'standard rate 2 queen deluxe|deluxe room w/2 queen beds:',
 'flexible rate|1kng dlx suite mobility/hearing access tub vis firealrm/door/phn alrt',
 'corporate - bed and breakfast|double room double room corp bnb',
 '2x points|2 queen beds executive floor step-out balcny lounge access w/contl brkfst-thomas roth ame',
 'aaa hot deals|aaa caa hot deals, membership card required, executive suite, 1 king, sofa bed',
 'best available rate|king family room comp wifi/mini fridge/pull-out sofa/33 sqm',
 'regular rate|flexible rate, guest room, 1 king',
 'cwt program -honors semi-flex|king junior suite wifi/living area w/sofa/bathtub-walkin shower',
 'you deserve some credit|liberty king bed rm 300 sq ft.',
 'catholic education office darw|1 bedroom queen and sofa townhouse loft style townhouse - courtyard - kitchenette',
 'mrate avail savor, the french|luxury room, 1 king size bed or 2 single size b eds, square or garden view',
 '2x points|1 king tower luxury suite grand river view 615 sq ft - parlor - sofabed - fridge - 2 tvs',
 'daily parking pkg package|includes room accommodations and parking for king bed penthouse suite nonsmoking relax in private in our king bed suite. this spacious room offers a comfortable king',
 'aaa discount|2 doubles premium bay view room nsmk with free wifi, balcony, fridge, hdtv',
 'flexible rate|1 king bed two room premium suite premium wifi-in suite refreshment snack tray',
 'best available rate|presidential suite king 1000sqf93sqm harbor v iew terrace livingdining room',
 'aaa american auto assn|aaa caa rate, membership card required, queen/queen room, guest room, 2 queen',
 '5000 rc bonus includes room|and 5000 rc bonus points per any consecutive club intercontinental room when you arrive we will do our best to meet your rm bd type and smoking preferences. rms',
 'flexible dinner and breakfast|single room - single bed and en-suite bathroom free wifi-flat screen tv-kettle-desk',
 '5000 rc bonus includes room|and 5000 rc bonus points per any consecutive standard room when you arrive at the hotel we will do our best to meet your room type preference this is subject to',
 'experience bus. pack.|pawfect vacation - pet package, studio, 1 king, sofa bed',
 'aaa/aarp rate|studio ste 1k-panoramic view-spacious seating- molton brown bath-nespresso-smart tv-freewifi',
 'aaa|park avenue suite.1150 sqft.free wifi.2 bdrms mstr 1 kg bd.2 dbl bds in 2nd room.living rm',
 'prepaid - level 01|superior room - panoramic view',
 'state government official trvl|1 king bedroom king superior suite robes/slippers - 55 inch hdtv - 1300 sq ft',
 'standard plan.standard|budget room: budget non-smoking twin room 21 sq m.with bathroom and toilet/non smoking. breakfast included airport: 10.923 km, last name: sendai airport  sdj , travel time by public transport: 0 min, iata code: sdj airport: 58.233 km, last name: yamagata airport  gaj , travel time by public transport: 0 min, iata code: sdj airport: 113.39 km, last name: shonai airport  syo yamagata   , travel time by public transport: 0 min city/town center: 0.449 km, last name: sendai, travel time by public transport: 0 min central train station: 0.317 km, last name: sendai, travel time by public transport: 0 min fridge iron   ironing board breakfast restaurant s  1, closed public internet terminal laundry service washing machine for guests store/mini supermarket total number of rooms: 223 reception manned 24 hours a day hairdryer easy access for wheelchairs cable tv fax connection wlan with internet access in rooms',
 'regular rate|flexible rate, 1 bedroom villa, 1 king, sofa bed, island view, balcony']

In [61]:
sampled_descriptions[5]

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_87030/2322311563.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sampled_descriptions[5]

'1 TRAVEL LEADERS SELECT HOTELS|CLASSIC SUITE -1 KING BED - AVG 65SQM 699SQF LIVING ROOM - FREE WIFI'

In [65]:
print("\nRunning spaCy analysis with transformer model...")
spacy_results = analyze_with_spacy(clean_text(sampled_descriptions))

Running spaCy analysis with transformer model...

Processing with spaCy: 100%|██████████| 2/2 [00:00<00:00,  3.36it/s]

In [66]:
spacy_results

,text,room_types,bed_types,other_entities
0,aaa / caa member rate|mobility/hearing accessi...,[],[],[]
1,flexible rate|deluxe one king bedroom harbour ...,[apartment],[],"[(one, CARDINAL), (harbour view, LOC)]"
2,lincoln rejuvenation|bungalow king- 520-685 sq...,[],[],"[(520-685 sq.ft, QUANTITY)]"
3,magellan 20pct comm. promotion|cabana non-view...,[],[],"[(magellan, PERSON), (1, CARDINAL)]"
4,government rate verify rate.|per diem rate is ...,[],[],"[(1, CARDINAL), (325 sqft, QUANTITY)]"
5,1 travel leaders select hotels|classic suite -...,[suite],[],"[(1, CARDINAL)]"
6,regular rate - ro -|comfort room with twin bed...,[],[],"[(26 sqm, QUANTITY)]"
7,military family rate|1 king bed cottage 25usd ...,[cottage],[],[]
8,standard rate 2 queen deluxe|deluxe room w/2 q...,[],[],"[(2, CARDINAL)]"
9,flexible rate|1kng dlx suite mobility/hearing ...,[suite],[],[]
10,corporate - bed and breakfast|double room doub...,[],[],[]
11,2x points|2 queen beds executive floor step-ou...,[],[],[]
12,"aaa hot deals|aaa caa hot deals, membership ca...",[suite],[],"[(1, CARDINAL)]"
13,best available rate|king family room comp wifi...,[],[],[]
14,"regular rate|flexible rate, guest room, 1 king",[],[],"[(1, CARDINAL)]"
15,cwt program -honors semi-flex|king junior suit...,[suite],[],"[(cwt, ORG)]"
16,you deserve some credit|liberty king bed rm 30...,[],[],"[(300 sq ft, QUANTITY)]"
17,catholic education office darw|1 bedroom queen...,[loft],[],[]
18,"mrate avail savor, the french|luxury room, 1 k...",[],[],"[(1, CARDINAL), (2, CARDINAL)]"
19,2x points|1 king tower luxury suite grand rive...,[suite],[],"[(615 sq ft, QUANTITY), (2, CARDINAL)]"
20,daily parking pkg package|includes room accomm...,"[penthouse, suite, suite]",[],"[(daily, DATE)]"
21,aaa discount|2 doubles premium bay view room n...,[],[],[]
22,flexible rate|1 king bed two room premium suit...,"[suite, suite]",[],"[(two, CARDINAL)]"
23,best available rate|presidential suite king 10...,[suite],[],[]
24,"aaa american auto assn|aaa caa rate, membershi...",[],[],"[(american, NORP), (2, CARDINAL)]"
25,5000 rc bonus includes room|and 5000 rc bonus ...,[],[],"[(5000, CARDINAL), (5000, CARDINAL)]"
26,flexible dinner and breakfast|single room - si...,[suite],[],[]
27,5000 rc bonus includes room|and 5000 rc bonus ...,[],[],"[(5000, CARDINAL), (5000, CARDINAL)]"
28,experience bus. pack.|pawfect vacation - pet p...,[],[],"[(1, CARDINAL)]"
29,aaa/aarp rate|studio ste 1k-panoramic view-spa...,[],[],"[(molton, ORG)]"
30,aaa|park avenue suite.1150 sqft.free wifi.2 bd...,[],[],"[(1 kg, QUANTITY), (2nd, ORDINAL)]"
31,prepaid - level 01|superior room - panoramic view,[],[],[]
32,state government official trvl|1 king bedroom ...,[suite],[],"[(55 inch, QUANTITY), (1300 sq ft, QUANTITY)]"
33,standard plan.standard|budget room: budget non...,[],[],"[(21 sq m.with, QUANTITY), (10.923 km, QUANTIT..."
34,"regular rate|flexible rate, 1 bedroom villa, 1...",[villa],[],"[(1, CARDINAL), (1, CARDINAL)]"

In [ ]:
# Analyze the results
def analyze_entity_frequencies(df):
    print("\nMost common room types:")
    room_types = [item for sublist in df['room_types'] for item in sublist]
    print(pd.Series(room_types).value_counts().head(10))
    
    print("\nMost common bed types:")
    bed_types = [item for sublist in df['bed_types'] for item in sublist]
    print(pd.Series(bed_types).value_counts().head(10))
    
    print("\nMost common view types:")
    view_types = [item for sublist in df['view_types'] for item in sublist]
    print(pd.Series(view_types).value_counts().head(10))
    
    print("\nMost common amenities:")
    amenities = [item for sublist in df['amenities'] for item in sublist]
    print(pd.Series(amenities).value_counts().head(10))
    
    print("\nSample of other entities found:")
    other_entities = [item for sublist in df['other_entities'] for item in sublist]
    print(pd.Series([e[0] for e in other_entities]).value_counts().head(10))


#%%
# Print the processed patterns for verification
print("Processed Room Types:", preprocess_pattern_list(room_types_list))
print("Processed Bed Types:", preprocess_pattern_list(bed_types_list))
print("Processed View Types:", preprocess_pattern_list(room_view_list))
print("Processed Amenities:", preprocess_pattern_list(room_amenities_list))

#%%
# Run analysis on a sample first to verify results
sample_size = 100
sample_texts = dataset_raw['Room Description'].sample(n=sample_size, random_state=42)

print("\nRunning spaCy analysis with transformer model...")
spacy_results = analyze_with_spacy(sample_texts)

#%%
analyze_entity_frequencies(spacy_results)

#%%
# If results look good, process the full dataset
print("\nProcessing full dataset...")
full_results = analyze_with_spacy(dataset_raw['Room Description'])
analyze_entity_frequencies(full_results)

#%%
# Add extracted features back to original dataframe
dataset_new = dataset_raw.copy()
dataset_new['extracted_room_types'] = full_results['room_types']
dataset_new['extracted_bed_types'] = full_results['bed_types']
dataset_new['extracted_view_types'] = full_results['view_types']
dataset_new['extracted_amenities'] = full_results['amenities']

dataset_new.to_excel('Data/dataset_spacy_extraction_v1.xlsx', index=False)

In [ ]:
import spacy
from tqdm import tqdm
from collections import defaultdict

In [67]:
import spacy
from tqdm import tqdm
from collections import defaultdict

def clean_text(texts):
    """Clean and standardize text descriptions"""
    cleaned_texts = []
    for text in texts:
        if pd.isna(text):
            cleaned_texts.append("")
            continue
            
        # Convert to lowercase
        text = text.lower()
        
        # Replace specific compound terms
        compound_terms = {
            'bed room': 'bedroom'
        }
        
        for term, replacement in compound_terms.items():
            text = text.replace(term, replacement)
            
        cleaned_texts.append(text)
    
    return cleaned_texts

def setup_ner_patterns(nlp, attribute_lists):
    """Setup NER patterns for all attribute types"""
    patterns = []
    
    for attr_type, attr_list in attribute_lists.items():
        for attr in attr_list:
            if pd.notna(attr):
                words = re.findall('[A-Z][^A-Z]*', str(attr))
                full_form = ' '.join(words) if words else str(attr)
                
                patterns.append({
                    "label": attr_type.upper(),
                    "pattern": full_form,
                    "id": str(attr)
                })
                
                if ' ' in full_form:
                    patterns.append({
                        "label": attr_type.upper(),
                        "pattern": full_form.split(),
                        "id": str(attr)
                    })
    
    if "entity_ruler" not in nlp.pipe_names:
        ruler = nlp.add_pipe("entity_ruler", before="ner")
    else:
        ruler = nlp.get_pipe("entity_ruler")
    ruler.add_patterns(patterns)
    return nlp

def extract_attributes_ner(texts, attribute_lists):
    """Extract attributes using spaCy NER with custom patterns"""
    try:
        nlp = spacy.load("en_core_web_trf")
    except OSError:
        print("Downloading en_core_web_trf model...")
        spacy.cli.download("en_core_web_trf")
        nlp = spacy.load("en_core_web_trf")
    
    # Clean texts first
    cleaned_texts = clean_text(texts)
    
    # Setup patterns
    nlp = setup_ner_patterns(nlp, {
        'room_type': room_types_list,
        'bed_type': bed_types_list,
        'amenity': room_amenities_list
    })
    
    results = []
    
    # Process in batches
    batch_size = 32
    for i in tqdm(range(0, len(cleaned_texts), batch_size), desc="Processing with NER"):
        batch_texts = cleaned_texts[i:i + batch_size]
        
        docs = nlp.pipe(batch_texts)
        
        for doc in docs:
            entities = {
                "text": doc.text,
                "room_types": [],
                "bed_types": [],
                "amenities": []
            }
            
            for ent in doc.ents:
                if ent.label_ == "ROOM_TYPE":
                    entities["room_types"].append({
                        'text': ent.text,
                        'normalized': ent.ent_id_
                    })
                elif ent.label_ == "BED_TYPE":
                    entities["bed_types"].append({
                        'text': ent.text,
                        'normalized': ent.ent_id_
                    })
                elif ent.label_ == "AMENITY":
                    entities["amenities"].append({
                        'text': ent.text,
                        'normalized': ent.ent_id_
                    })
            
            results.append(entities)
    
    return pd.DataFrame(results)

In [68]:
results = extract_attributes_ner(sampled_descriptions, {
    'room_type': room_types_list,
    'bed_type': bed_types_list,
    'amenity': room_amenities_list
})

print("\nExtracted Attributes:")
print(results)

ValueError: [E154] One of the attributes or values is not supported for token patterns. Please use the option `validate=True` with the Matcher, PhraseMatcher, or EntityRuler for more details.

In [105]:
# NER Spacy with confidence scores and rule-based matches
def extract_attributes_ner(texts, attribute_lists):
    """Extract attributes using spaCy NER with confidence scores"""
    try:
        nlp = spacy.load("en_core_web_trf")
    except OSError:
        print("Downloading en_core_web_trf model...")
        spacy.cli.download("en_core_web_trf")
        nlp = spacy.load("en_core_web_trf")
    
    # Clean texts first
    cleaned_texts = clean_text(texts)
    
    # Setup patterns
    patterns = []
    for attr_type, attr_list in attribute_lists.items():
        for attr in attr_list:
            if pd.notna(attr):
                attr_text = str(attr).lower()
                patterns.append({
                    "label": attr_type.upper(),
                    "pattern": [{"LOWER": attr_text}],
                    "id": str(attr),
                    "source": "rule"  # Mark as rule-based match
                })
    
    if "entity_ruler" not in nlp.pipe_names:
        ruler = nlp.add_pipe("entity_ruler", before="ner")
    else:
        ruler = nlp.get_pipe("entity_ruler")
    ruler.add_patterns(patterns)
    
    results = []
    batch_size = 32
    
    for i in tqdm(range(0, len(cleaned_texts), batch_size), desc="Processing with NER"):
        batch_texts = cleaned_texts[i:i + batch_size]
        docs = nlp.pipe(batch_texts)
        
        for doc in docs:
            entities = {
                "text": doc.text,
                "room_types": [],
                "bed_types": [],
                "amenities": []
            }
            
            # Check for accessibility keywords
            is_accessible = 'access' in doc.text.lower() or 'ada' in doc.text.lower()
            
            for ent in doc.ents:
                # Default confidence for rule-based matches
                score = 0.8 if getattr(ent, 'source', None) == 'rule' else 1.0
                
                # Try to get neural confidence if available
                try:
                    if hasattr(ent, 'tensor') and ent.tensor is not None:
                        score = float(ent.tensor.max())
                except (ValueError, AttributeError):
                    pass
                
                if ent.label_ == "ROOM_TYPE":
                    entities["room_types"].append({
                        'text': ent.text.lower(),
                        'score': score,
                        'source': getattr(ent, 'source', 'neural')
                    })
                elif ent.label_ == "BED_TYPE":
                    entities["bed_types"].append({
                        'text': ent.text.lower(),
                        'score': score,
                        'source': getattr(ent, 'source', 'neural')
                    })
            
            # Add Accessible Room if keywords found
            if is_accessible:
                entities["room_types"].append({
                    'text': 'accessible room',
                    'score': 1.1,
                    'source': 'rule'
                })
            
            # Sort by confidence score
            for key in entities.keys():
                if isinstance(entities[key], list):
                    entities[key] = sorted(entities[key], key=lambda x: x['score'], reverse=True)
            
            results.append(entities)
    
    return pd.DataFrame(results)

In [106]:
# New
results_spacy_ner = extract_attributes_ner(dataset['Room Description'], {
    'room_type': room_types_list,
    'bed_type': bed_types_list,
    'amenity': room_amenities_list
})

print("\nExtracted Attributes:")
print(results_spacy_ner)

Processing with NER: 100%|██████████| 1094/1094 [08:41<00:00,  2.10it/s]

Extracted Attributes:
                                                    text  \
0      flexible rate|2queen hearing accessible studio...
1      2x points package|2queen hearing accessible st...
2      park and stay aaa|2queen hearing accessible st...
3      park and stay aarp|2queen hearing accessible s...
4      park and go|2queen hearing accessible studio s...
...                                                  ...
34995  cwt includes wifi use of|fitness and wellness ...
34996  stay longer save|specialty room when you arriv...
34997  cwt|specialty room when you arrive at the hote...
34998  book now, pay later|deluxe room an upgrade fro...
34999  best flexible rate|specialty room bed type can...

                                              room_types bed_types amenities
0      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
1      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
2      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
3      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
4      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
...                                                  ...       ...       ...
34995                                                 []        []        []
34996                                                 []        []        []
34997                                                 []        []        []
34998                                                 []        []        []
34999                                                 []        []        []

[35000 rows x 4 columns]

In [107]:
print("\nExtracted Attributes:")
print(results_spacy_ner)

Extracted Attributes:
                                                    text  \
0      flexible rate|2queen hearing accessible studio...
1      2x points package|2queen hearing accessible st...
2      park and stay aaa|2queen hearing accessible st...
3      park and stay aarp|2queen hearing accessible s...
4      park and go|2queen hearing accessible studio s...
...                                                  ...
34995  cwt includes wifi use of|fitness and wellness ...
34996  stay longer save|specialty room when you arriv...
34997  cwt|specialty room when you arrive at the hote...
34998  book now, pay later|deluxe room an upgrade fro...
34999  best flexible rate|specialty room bed type can...

                                              room_types bed_types amenities
0      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
1      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
2      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
3      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
4      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
...                                                  ...       ...       ...
34995                                                 []        []        []
34996                                                 []        []        []
34997                                                 []        []        []
34998                                                 []        []        []
34999                                                 []        []        []

[35000 rows x 4 columns]

In [70]:
# Old
results = extract_attributes_ner(sampled_descriptions, {
    'room_type': room_types_list,
    'bed_type': bed_types_list,
    'amenity': room_amenities_list
})

print("\nExtracted Attributes:")
print(results)

Processing with NER: 100%|██████████| 2/2 [00:00<00:00,  2.35it/s]

Extracted Attributes:
                                                 text  \
0   aaa / caa member rate|mobility/hearing accessi...
1   flexible rate|deluxe one king bedroom harbour ...
2   lincoln rejuvenation|bungalow king- 520-685 sq...
3   magellan 20pct comm. promotion|cabana non-view...
4   government rate verify rate.|per diem rate is ...
5   1 travel leaders select hotels|classic suite -...
6   regular rate - ro -|comfort room with twin bed...
7   military family rate|1 king bed cottage 25usd ...
8   standard rate 2 queen deluxe|deluxe room w/2 q...
9   flexible rate|1kng dlx suite mobility/hearing ...
10  corporate - bed and breakfast|double room doub...
11  2x points|2 queen beds executive floor step-ou...
12  aaa hot deals|aaa caa hot deals, membership ca...
13  best available rate|king family room comp wifi...
14     regular rate|flexible rate, guest room, 1 king
15  cwt program -honors semi-flex|king junior suit...
16  you deserve some credit|liberty king bed rm 30...
17  catholic education office darw|1 bedroom queen...
18  mrate avail savor, the french|luxury room, 1 k...
19  2x points|1 king tower luxury suite grand rive...
20  daily parking pkg package|includes room accomm...
21  aaa discount|2 doubles premium bay view room n...
22  flexible rate|1 king bed two room premium suit...
23  best available rate|presidential suite king 10...
24  aaa american auto assn|aaa caa rate, membershi...
25  5000 rc bonus includes room|and 5000 rc bonus ...
26  flexible dinner and breakfast|single room - si...
27  5000 rc bonus includes room|and 5000 rc bonus ...
28  experience bus. pack.|pawfect vacation - pet p...
29  aaa/aarp rate|studio ste 1k-panoramic view-spa...
30  aaa|park avenue suite.1150 sqft.free wifi.2 bd...
31  prepaid - level 01|superior room - panoramic view
32  state government official trvl|1 king bedroom ...
33  standard plan.standard|budget room: budget non...
34  regular rate|flexible rate, 1 bedroom villa, 1...

                                           room_types  \
0                                                  []
1   [{'text': 'king bedroom', 'normalized': 'King ...
2                                                  []
3                                                  []
4                                                  []
5          [{'text': 'suite', 'normalized': 'Suite'}]
6                                                  []
7      [{'text': 'cottage', 'normalized': 'Cottage'}]
8                                                  []
9          [{'text': 'suite', 'normalized': 'Suite'}]
10  [{'text': 'double room', 'normalized': 'Double...
11                                                 []
12         [{'text': 'suite', 'normalized': 'Suite'}]
13                                                 []
14  [{'text': 'guest room', 'normalized': 'Guest R...
15  [{'text': 'junior suite', 'normalized': 'Junio...
16                                                 []
17                                                 []
18                                                 []
19  [{'text': 'luxury suite', 'normalized': 'Luxur...
20  [{'text': 'penthouse', 'normalized': 'Penthous...
21                                                 []
22  [{'text': 'suite', 'normalized': 'Suite'}, {'t...
23         [{'text': 'suite', 'normalized': 'Suite'}]
24  [{'text': 'guest room', 'normalized': 'Guest R...
25                                                 []
26         [{'text': 'suite', 'normalized': 'Suite'}]
27                                                 []
28                                                 []
29                                                 []
30                                                 []
31                                                 []
32  [{'text': 'king bedroom', 'normalized': 'King ...
33  [{'text': 'twin room', 'normalized': 'Twin Roo...
34         [{'text': 'villa', 'normalized': 'Villa'}]

                                            bed_types  \
0                                                  []
1                                                  []
2                                                  []
3                                                  []
4                                                  []
5                                                  []
6                                                  []
7    [{'text': 'king bed', 'normalized': 'King Bed'}]
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12                                                 []
13                                                 []
14                                                 []
15                                                 []
16                                                 []
17                                                 []
18                                                 []
19                                                 []
20                                                 []
21                                                 []
22                                                 []
23                                                 []
24                                                 []
25                                                 []
26  [{'text': 'single bed', 'normalized': 'Single ...
27                                                 []
28                                                 []
29                                                 []
30                                                 []
31                                                 []
32                                                 []
33                                                 []
34                                                 []

                                            amenities
0        [{'text': 'shower', 'normalized': 'Shower'}]
1                                                  []
2                                                  []
3                                                  []
4   [{'text': 'shower', 'normalized': 'Shower'}, {...
5    [{'text': 'king bed', 'normalized': 'King bed'}]
6                                                  []
7                                                  []
8                                                  []
9                                                  []
10                                                 []
11                                                 []
12   [{'text': 'sofa bed', 'normalized': 'Sofa bed'}]
13  [{'text': 'family room', 'normalized': 'Family...
14                                                 []
15  [{'text': 'bathtub', 'normalized': 'Bathtub'},...
16   [{'text': 'king bed', 'normalized': 'King bed'}]
17  [{'text': 'loft', 'normalized': 'Loft'}, {'tex...
18                                                 []
19                                                 []
20  [{'text': 'king bed', 'normalized': 'King bed'...
21     [{'text': 'balcony', 'normalized': 'balcony'}]
22   [{'text': 'king bed', 'normalized': 'King bed'}]
23                                                 []
24                                                 []
25     [{'text': 'smoking', 'normalized': 'Smoking'}]
26  [{'text': 'tv', 'normalized': 'TV'}, {'text': ...
27                                                 []
28   [{'text': 'sofa bed', 'normalized': 'Sofa bed'}]
29   [{'text': 'smart tv', 'normalized': 'Smart TV'}]
30                                                 []
31                                                 []
32   [{'text': 'slippers', 'normalized': 'Slippers'}]
33  [{'text': 'smoking', 'normalized': 'Smoking'},...
34  [{'text': 'sofa bed', 'normalized': 'Sofa bed'...

In [71]:
# Saving the results
results.to_excel('Data/dataset_spacy_extraction_sample_v3.xlsx', index=False)
# %%

In [108]:

def evaluate_ner_accuracy(ner_results, full_data):
    """Evaluate NER accuracy with confidence scores"""
    if len(ner_results) != len(full_data):
        print(f"Warning: Results ({len(ner_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(ner_results), len(full_data))
        ner_results = ner_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct_any = 0
    correct_top = 0
    total = len(full_data)
    
    print("\nNER Extraction Evaluation:")
    print("==========================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info']).lower()
        predictions = ner_results.iloc[i]['room_types']
        
        if not predictions:
            continue
        
        # Check top prediction
        top_pred = predictions[0]['text'].lower()
        top_match = true_label in top_pred or top_pred in true_label
        
        # Check any prediction
        any_match = any(true_label in pred['text'].lower() or pred['text'].lower() in true_label 
                       for pred in predictions)
        
        correct_top += top_match
        correct_any += any_match
        
        if i < 5:
            print(f"\nDescription: {row['Room Description']}")
            print(f"True Label: {true_label}")
            print(f"Top Prediction: {top_pred} (score: {predictions[0]['score']:.3f}, source: {predictions[0]['source']})")
            print("All Predictions:", [(p['text'], f"{p['score']:.3f}", p['source']) for p in predictions])
            print(f"Top Match: {'✓' if top_match else '✗'}")
            print(f"Any Match: {'✓' if any_match else '✗'}")
    
    top_accuracy = correct_top / total
    any_accuracy = correct_any / total
    
    print(f"\nTop Prediction Accuracy: {top_accuracy:.2%}")
    print(f"Any Match Accuracy: {any_accuracy:.2%}")
    
    return {"top_accuracy": top_accuracy, "any_accuracy": any_accuracy}

In [109]:
evaluate_ner_accuracy(results_spacy_ner, dataset)

NER Extraction Evaluation:
==========================

Description: FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100, source: rule)
All Predictions: [('accessible room', '1.100', 'rule'), ('suite', '1.000', 'neural')]
Top Match: ✓
Any Match: ✓

Description: 2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100, source: rule)
All Predictions: [('accessible room', '1.100', 'rule'), ('suite', '1.000', 'neural')]
Top Match: ✓
Any Match: ✓

Description: PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100, source: rule)
All Predictions: [('accessible room', '1.100', 'rule'), ('suite', '1.000', 'neural')]
Top Match: ✓
Any Match: ✓

Description: PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100, source: rule)
All Predictions: [('accessible room', '1.100', 'rule'), ('suite', '1.000', 'neural')]
Top Match: ✓
Any Match: ✓

Description: PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100, source: rule)
All Predictions: [('accessible room', '1.100', 'rule'), ('suite', '1.000', 'neural')]
Top Match: ✓
Any Match: ✓

Top Prediction Accuracy: 36.24%
Any Match Accuracy: 39.12%

{'top_accuracy': 0.36242857142857143, 'any_accuracy': 0.3912285714285714}

In [94]:
# Old
evaluate_ner_accuracy(dataset)

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_87030/4235206249.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = dataset.groupby('Guest Room Info').apply(
Processing with NER: 100%|██████████| 4/4 [00:01<00:00,  2.54it/s]

[]
[]
[]
['apartment']
['apartment']
['apartment']
['bungalow']
['bungalow', 'junior suite']
['suite', 'bungalow']
[]
['cabana']
['suite']
[]
['guest room']
[]
['suite']
[]
['suite']
[]
['comfort room', 'comfort room']
['comfort room']
[]
['cottage', 'suite']
['cottage']
[]
[]
['suite']
['suite']
[]
['deluxe suite']
[]
['double room']
['double room', 'guest room']
[]
[]
[]
['suite', 'corner room']
['suite']
['suite']
['suite']
['suite']
[]
['guest room']
['guest room']
['guest room']
['junior suite']
['suite']
['suite']
[]
['guest room']
[]
[]
[]
[]
['luxury room']
['luxury room']
[]
[]
['suite']
['suite']
['suite']
['suite']
['penthouse', 'suite', 'suite']
[]
[]
[]
['suite']
['suite']
['suite']
['presidential suite']
['suite']
['villa']
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
['suite']
['studio suite']
['studio suite', 'studio suite']
['suite']
['suite']
[]
[]
['superior room']
['superior room']
['suite']
['superior suite']
['superior suite']
[]
[]
[]
['villa']
['villa']
['villa']

Accuracy: 46.67%

Sample Predictions:

Description: FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESS W/ RI SHWR VISUAL FIREALARM/DOOR/PHONE ALERT
True Label: Accessible Room
Predicted: []

Description: AAA RATE-ID REQUIRED|PARK MGM KING - 1 KING BED ACCESSIBLE 406 SQ FT, BEDSIDE OUTLETS, SAFETY BAR
True Label: Accessible Room
Predicted: []

Description: STANDARD RATE 1 KING ADA TUB|1 KING BED  ADA TUB
True Label: Accessible Room
Predicted: []

Description: GLOBAL PROGRAM|1 BEDROOM APARTMENT 1 KING BED
True Label: Apartment
Predicted: [{'text': 'apartment', 'normalized': 'Apartment'}]

Description: BEST AVAILABLE RATE|1 BR APARTMENT - 1 QUEEN BED IN BR  2009 736 SQ FT - PULLOUT BED IN LR - FULL KITCHEN
True Label: Apartment
Predicted: [{'text': 'apartment', 'normalized': 'Apartment'}]

(0.4666666666666667,
                                       Room Description  Guest Room Info
 0    FLEXIBLE RATE|1 KING MOBILITY/HEARING ACCESS W...  Accessible Room
 1    AAA RATE-ID REQUIRED|PARK MGM KING - 1 KING BE...  Accessible Room
 2     STANDARD RATE 1 KING ADA TUB|1 KING BED  ADA TUB  Accessible Room
 3        GLOBAL PROGRAM|1 BEDROOM APARTMENT 1 KING BED        Apartment
 4    BEST AVAILABLE RATE|1 BR APARTMENT - 1 QUEEN B...        Apartment
 ..                                                 ...              ...
 100  BEST AVAILABLE RATE|TWIN ROOM NON SMOKING FREE...        Twin Room
 101  CWT BUSINESS RATES|TWIN ROOM 2 SEALY SINGLE BE...        Twin Room
 102  BEST AVAILABLE RATE BREAKFAST|SHIKUMEN VILLA K...            Villa
 103  ESSENTIAL SERENGETI|TWO BEDROOM VILLA KING-TWI...            Villa
 104  SIGNATURE TRAVEL 2 KG 1 TB OCN|3BDRM ILIKAI VI...            Villa

 [105 rows x 2 columns],
                                                   text  \
 0    flexible rate|1 king mobility/hearing access w...
 1    aaa rate-id required|park mgm king - 1 king be...
 2     standard rate 1 king ada tub|1 king bed  ada tub
 3        global program|1 bedroom apartment 1 king bed
 4    best available rate|1 br apartment - 1 queen b...
 ..                                                 ...
 100  best available rate|twin room non smoking free...
 101  cwt business rates|twin room 2 sealy single be...
 102  best available rate breakfast|shikumen villa k...
 103  essential serengeti|two bedroom villa king-twi...
 104  signature travel 2 kg 1 tb ocn|3bdrm ilikai vi...

                                             room_types  \
 0                                                   []
 1                                                   []
 2                                                   []
 3    [{'text': 'apartment', 'normalized': 'Apartmen...
 4    [{'text': 'apartment', 'normalized': 'Apartmen...
 ..                                                 ...
 100                                                 []
 101                                                 []
 102         [{'text': 'villa', 'normalized': 'Villa'}]
 103         [{'text': 'villa', 'normalized': 'Villa'}]
 104         [{'text': 'villa', 'normalized': 'Villa'}]

                                             bed_types  \
 0                                                  []
 1    [{'text': 'king bed', 'normalized': 'King Bed'}]
 2                                                  []
 3                                                  []
 4                                                  []
 ..                                                ...
 100                                                []
 101                                                []
 102                                                []
 103                                                []
 104                                                []

                                              amenities
 0                                                   []
 1                                                   []
 2     [{'text': 'king bed', 'normalized': 'King bed'}]
 3     [{'text': 'king bed', 'normalized': 'King bed'}]
 4    [{'text': 'queen bed', 'normalized': 'Queen be...
 ..                                                 ...
 100  [{'text': 'smoking', 'normalized': 'Smoking'},...
 101               [{'text': 'tv', 'normalized': 'TV'}]
 102                                                 []
 103                                                 []
 104                                                 []

 [105 rows x 4 columns])