In [3]:
import pandas as pd
import re

In [45]:
# Prep data for attribute extraction
dataset_normalized_attributes = pd.read_excel('../Data/Normalized_product_attribute_name.xlsx', sheet_name = 'Normalized Product Attributes')
dataset_normalized_attributes

,BedType,OTA TYPE = BED,Unnamed: 2,RoomType,OTA TYPE = GRI,Unnamed: 5,Rateplan Incl/Value-adds,OTA TYPE = HAC,Unnamed: 8,Room Amenities,OTA TYPE = RMA,Unnamed: 11,Mealplan,OTA TYPE = MPT,Unnamed: 14,RoomView,OTA TYPE = RVT,Unnamed: 17,Taxes & Fees,OTA TYPE = FTT
0,Double/Full Bed,1.0,NaN,Accessible Room,1.0,NaN,Piano,0,NaN,Adjoining rooms,1.0,NaN,All Inclusive,1.0,NaN,Airport view,1.0,NaN,Bed tax,1.0
1,Futon Bed,2.0,NaN,Suite,3.0,NaN,24-hour front desk,1,NaN,Air conditioning,2.0,NaN,Full Board or American,2.0,NaN,Bay view,2.0,NaN,City hotel fee,2.0
2,King Bed,3.0,NaN,Executive/Club Suite,6.0,NaN,24-hour room service,2,NaN,Alarm clock,3.0,NaN,Buffet Breakfast,4.0,NaN,City view,3.0,NaN,PropertyFee,2.0
3,Murphy Bed,4.0,NaN,Double Room,10.0,NaN,24-hour security,3,NaN,All news channel,4.0,NaN,Continental Breakfast,6.0,NaN,Courtyard view,4.0,NaN,City tax,3.0
4,Queen Bed,5.0,NaN,King Bedroom,11.0,NaN,adjoining rooms,4,NaN,radio,5.0,NaN,Family Plan,9.0,NaN,Golf View,5.0,NaN,Municipal Tax,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,NaN,NaN,NaN,NaN,NaN,NaN,Train station shuttle services,2030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,NaN,NaN,NaN,NaN,NaN,NaN,Electric car charging stations,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,Golf clubs (equipments),2032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380,NaN,NaN,NaN,NaN,NaN,NaN,Beach club,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
381,NaN,NaN,NaN,NaN,NaN,NaN,Theme park shuttle,2034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:

room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()

bed_types = dataset_normalized_attributes['BedType'].dropna().unique()
bed_types_list = bed_types.tolist()

room_amenities = dataset_normalized_attributes['Room Amenities'].dropna().unique()
room_amenities_list = room_amenities.tolist()

In [47]:
room_types_list

['Accessible Room ',
 'Suite',
 'Executive/Club Suite',
 'Double Room ',
 'King Bedroom',
 'Apartment',
 'Queen Bedroom',
 'Penthouse',
 'Studio Suite',
 'Twin Room',
 'Family Room/Suite',
 'Cabin',
 'Cottage',
 'Loft',
 'Guest Room',
 'Bungalow',
 'Villa',
 'Junior Suite',
 'Run of the House',
 'Large/Master Suite',
 'Executive/Club Room',
 'Classic Room',
 'Comfort Room',
 'Deluxe Room',
 'Deluxe Suite',
 'Economy Room',
 'Luxury Suite',
 'Premier Room',
 'Standard Guest Room',
 'Superior Room',
 'Superior Suite',
 'Grand Room',
 'Premier Suite',
 'Luxury Room',
 'Classic Suite',
 'Presidential Suite',
 'Single Room',
 'Triple Room',
 'Quadruple Room',
 'Studio Room',
 'Cabana',
 'Privilege Room',
 'Prestige Room',
 'Corner Room',
 'Signature Room',
 'Traditional Room ',
 'Wellness Room',
 'Terrace Room',
 'Tower Room',
 'Heritage Room',
 'Urban Room']

In [48]:
bed_types_list

['Double/Full Bed',
 'Futon Bed',
 'King Bed',
 'Murphy Bed',
 'Queen Bed',
 'Sofa Bed',
 'Twin/Single Bed',
 'Single Bed',
 'Run of the house',
 'Dorm/Bunk Bed',
 'Water Bed']

In [49]:
room_amenities_list

['Adjoining rooms',
 'Air conditioning',
 'Alarm clock',
 'All news channel',
 'radio',
 'Baby listening device',
 'balcony',
 'Barbeque grills',
 'Bathtub with spray jets',
 'Bathrobe',
 'Bathroom amenities',
 'Bathroom telephone',
 'Bathtub',
 'Bathtub only',
 'Bathtub & shower',
 'Bidet',
 'Bottled water',
 'Cable television',
 'Coffee maker',
 'Color television',
 'Computer',
 'Connecting rooms',
 'electric converters ',
 'Copier',
 'Cordless phone',
 'Cribs',
 'Data port',
 'Desk',
 'Desk with lamp',
 'Dining guide',
 'Direct dial phone number',
 'Dishwasher',
 'Double beds',
 'Dual voltage outlet',
 'Electrical current voltage',
 'Ergonomic chair',
 'Extended phone cord',
 'Fax machine',
 'Fire alarm',
 'Fire alarm with light',
 'Fireplace',
 'Free toll free calls',
 'Free calls',
 'Free credit card access calls',
 'Free local calls',
 'Free movies',
 'Full kitchen',
 'Grab bars in bathroom',
 'Grecian tub',
 'Hairdryer',
 'High speed internet connection',
 'Interactive web TV',
 'International direct dialing',
 'Internet access',
 'Iron',
 'Ironing board',
 'Whirlpool',
 'King bed',
 'Kitchen',
 'Kitchen supplies',
 'Kitchenette',
 'Knock light',
 'Laptop',
 'Large desk',
 'Large work area',
 'Laundry basket',
 'Loft',
 'Microwave',
 'Minibar',
 'Modem',
 'Modem jack',
 'Multi-line phone',
 'Newspaper',
 'Non-smoking',
 'Notepads',
 'Office supplies',
 'Oven',
 'Pay per view movies on TV',
 'Pens',
 'Phone in bathroom',
 'Plates and bowls',
 'Pots and pans',
 'Prayer mats',
 'Printer',
 'Private bathroom',
 'Queen bed',
 'Recliner',
 'Refrigerator',
 'Refrigerator with ice maker',
 'Remote control television',
 'Rollaway bed',
 'Safe',
 'Scanner',
 'Separate closet',
 'Separate modem line available',
 'Shoe polisher',
 'Shower only',
 'Silverware',
 'Sitting area',
 'Smoke detectors',
 'Smoking',
 'Sofa bed',
 'Speaker phone',
 'Stereo',
 'Stove',
 'Tape recorder',
 'Telephone',
 'Telephone for hearing impaired',
 'Telephones with message light',
 'Toaster oven',
 'Trouser press',
 'Turn down service',
 'Twin bed',
 'Vaulted ceilings',
 'VCR movies',
 'VCR player',
 'Video games',
 'Voice mail',
 'Wake-up calls',
 'Water closet',
 'Water purification system',
 'Wet bar',
 'Wireless internet connection',
 'Wireless keyboard',
 'Adaptor available for telephone PC use',
 'Air conditioning individually controlled in room',
 'Bathtub & whirlpool',
 'Telephone with data ports',
 'CD player',
 'Complimentary local calls time limit',
 'Extra person charge for rollaway use',
 'feather pillows',
 'Desk with electrical outlet',
 'ESPN available',
 'Foam pillows',
 'HBO available',
 'High ceilings',
 'Marble bathroom',
 'List of movie channels available',
 'Pets allowed',
 'Oversized bathtub',
 'Shower',
 'Sink in-room',
 'Soundproofed room',
 'Storage space',
 'Tables and chairs',
 'Two-line phone',
 'Walk-in closet',
 'Washer dryer',
 'Weight scale',
 'Welcome gift',
 'Spare electrical outlet available at desk',
 'Non refundable charge for pets',
 'Refundable deposit for pets',
 'Separate tub and shower',
 'Entrance type to guest room',
 'Ceiling fan',
 'CNN available',
 'Electrical adaptors available',
 'Buffet breakfast',
 'Accessible room',
 'Closets in room',
 'DVD player',
 'Mini refrigerator',
 'Separate line billing for multi-line phone',
 'Self-controlled heating/cooling system',
 'Toaster',
 'Analog data port',
 'Collect calls',
 'International calls',
 'Carrier access',
 'Interstate calls',
 'Intrastate calls',
 'Local calls',
 'Long distance calls',
 'Operator assisted calls',
 'Credit card access calls',
 'Calling card calls',
 'Toll free calls',
 'Universal adaptors',
 'Bathtub seat',
 'Canopy',
 'glassware',
 'Entertainment center',
 'Family room',
 'Hypoallergenic bed',
 'Hypoallergenic pillows',
 'Lamp',
 'Meal included - breakfast',
 'Meal included - continental breakfast',
 'Meal included - dinner',
 'Meal included - lunch',
 'Shared bathroom',
 'Textphone',
 'Water bed',
 'Extra adult charge',
 'Extra child charge',
 'Extra child charge for rollaway use',
 'Meal included: full American breakfast',
 'Futon',
 'Murphy bed',
 'Tatami mats',
 'Single bed',
 'Annex room',
 'Free newspaper',
 'Honeymoon suites',
 'Complimentary high speed internet in room',
 'Maid service',
 'PC hook-up in room',
 'Satellite television',
 'VIP rooms',
 'Cell phone recharger',
 'DVR player',
 'iPod docking station',
 'Media center',
 'Plug & play panel',
 'Satellite radio',
 'Video on demand',
 'Exterior corridors',
 'Gulf view',
 'Interior corridors',
 'Mountain view',
 'Ocean view',
 'High speed internet access for fee',
 'High speed wireless',
 'Premium movie channels',
 'Slippers',
 "First nighters' kit",
 'Chair provided with desk',
 'Pillow top mattress',
 'Feather bed',
 'Duvet',
 'Luxury linen type',
 'International channels',
 'Pantry',
 'Dish-cleaning supplies',
 'Double vanity',
 'Lighted makeup mirror',
 'Upgraded bathroom amenities',
 'VCR player available at front desk',
 'Instant hot water',
 'Outdoor space',
 'Hinoki tub',
 'Private pool',
 'High Definition (HD) Flat Panel Television - 32 inches or greater',
 'Room windows open',
 'Bedding type unknown or unspecified',
 'Full bed',
 'Round bed',
 'TV',
 'Child rollaway',
 'DVD player available at front desk',
 'Video game player:',
 'Video game player available at front desk',
 'Dining room seats',
 'Full size mirror',
 'Mobile/cellular phones',
 'Movies',
 'Multiple closets',
 'Plates/glassware',
 'Safe large enough to accommodate a laptop',
 'Bed linen thread count',
 'Blackout curtain',
 'Bluray player',
 'Device with mp3',
 'No adult channels or adult channel lock',
 'Non-allergenic room',
 'Pillow type',
 'Seating area with sofa/chair',
 'Separate toilet area',
 'Web enabled',
 'Widescreen TV',
 'Other data connection',
 'Phoneline billed separately',
 'Separate tub or shower',
 'Roof ventilator',
 "Children's playpen",
 'Plunge pool',
 'DVD movies',
 'Air filtration',
 'Exercise Equipment in Room',
 'Towels Sheets',
 'Electric Kettle',
 'Portable Fan',
 'Washing Machine',
 'Towels Provided',
 'Smart TV',
 'Streaming Services',
 'Highchair',
 'Toilet with electronic bidet',
 'Free tea bags instant coffee',
 'Outdoor Shower',
 'Baby bath',
 'Changing table',
 'Heating/Heated floor',
 'Indoor private mineral hot springs (japanese style onsen)',
 'Freezer',
 'Ice maker',
 'In room childcare',
 'Digital TV serviceWired Internet Access',
 'Wired Internet Access',
 'Pillow Menu',
 'Room Size(Square feet)',
 'Room Size (Square meters)',
 'Cleaning Supplies',
 'Dryer',
 'Tatami (Woven mat) floors',
 'Private spa tub',
 'Cookware, dishware, and utensils']

In [50]:
dataset = pd.read_csv('../Data/Product_Normalization_GRI_Expanded.csv')
dataset.head()

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...

In [51]:
sampled_descriptions = dataset.groupby('Guest Room Info').apply(
    lambda x: x['Room Description Expanded'].sample()
)

print(sampled_descriptions)

Guest Room Info
Accessible Room       833      2X POINTS PACKAGE|1 KING MOBILITY ACCESSIBLE T...
Apartment             29181    GLOBAL PROGRAM|TWO BEDROOM APARTMENT- 1QUEEN 2...
Bungalow              12533    AMEX GBT GHP RATE|OCEAN COASTAL BUNGALOW SUITE...
Cabana                28325    CORPORATE|CABANA - DOUBLE OR TWIN BEDS - SEA V...
Classic Room          15641    BEST AVAILABLE RATE|TOWER 2 DBLB CLASSIC LOOKI...
Classic Suite         24737    ROCCO FORTE KNIGHTS|CLASSIC SUITE-SUPER KING O...
Comfort Room          16909    DISCOUNTED RATE INCL. BB|COMFORT ROOM-21 SQM-D...
Cottage               9214     CHOOSE YOUR ADVENTURE|LAGOON VIEW COTTAGE-1KIN...
Deluxe Room           17314    NO-AMENITY FEE-UP TO 10PCT OFF|KING DELUXE ROO...
Deluxe Suite          18267    BEST AVAILABLE RATE|DELUXE 1BDRM SUITE-1 KING ...
Double Bed            3311     CCS PUBLIC SECTOR GOLD|ACCESSIBLE 1 BED ROLL I...
Executive/Club Room   15128    BED AND BREAKFAST|EXECUTIVE ROOM-KING BED-AC-W...
Executive/Club Suite  1975     BEST AVAILABLE RATE MASTER|EXECUTIVE SUITE -RI...
Family Room/Suite     8407     DREAM AWAY|QUEEN FAMILY ROOM WITH RACECOURSE V...
Guest Room            11508    REGULAR RATE|FLEXIBLE RATE, PREMIUM, GUEST ROO...
Junior Suite          14019    INCL WIFI - AAA CAA - PRESENT|JUNIOR SUITE KIN...
King Bedroom          4514     ADV PURCHASE VIEW KING BED|KING ROOM WITH VIEW...
Loft                  10589    BCD TRAVEL 5TH AVE VIEW SUITE|1 KING:715 SF/49...
Luxury Room           23955                CWT HOTEL PROGRAMME PROMO|LUXURY KING
Luxury Suite          30598    GDS PROMO|LUXURY SUITE 1100 SQ FT PRIVATE BALCONY
Penthouse             5662     STANDARD RATE 4 BEDROOM PENTHOUSE|FOUR BEDROOM...
Premier Room          19818    ROOM RATE|PREMIER ROOM 2 DOUBLE-EAST WING 2-6 ...
Premier Suite         23307    BED AND BREAKFAST|PREMIER SUITE WEST WING-FLOO...
Presidential Suite    26017    BED AND BREAKFAST|PRESIDENTIAL SUITE 232SQM/CO...
Queen Bedroom         5157     ACCENTURE -PREFERRED RATE INC|QUEEN ROOM WITH ...
Run of the House      30920    2021 GETAWAY PACKAGE INCLUDES|2000 IHG REWARDS...
Single Room           26352    FLEXIBLE RATE ROOM ONLY|DOUBLE AND SINGLE ROOM...
Standard Room         20044    ADVANCE SAVER NO REFUNDS|STANDARD 1 QUEEN BED ...
Studio Room           27186                   BED AND BREAKFAST|EXECUTIVE STUDIO
Studio Suite          6543     4000 POINTS PER STAY ENJOY|STANDARD STUDIO SUI...
Suite                 987      SEMIFLEX NON REFUN|PREPAY NON-REFUNDABLE, CHAN...
Superior Room         21518    BB SEMI FLEX|TWIN SUPERIOR ROOM WIFI/ESPRESSO/...
Superior Suite        22765    MARRIOTT SENIOR DISC.|MARRIOTT SENIOR DISCOUNT...
Twin Room             7741     SEMI-FLEX|TWIN ROOM WITH RUNWAY VIEW FREE WI-F...
Villa                 12912            FLEXIBLE RATE|OCEANVIEW VILLA ROOM 1 KING
Name: Room Description Expanded, dtype: object

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_36709/120762231.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_descriptions = dataset.groupby('Guest Room Info').apply(

## Basic RegEx type extraction test ##

In [52]:
# Tagging based on manually defined patterns
def extract_key_phrases(texts):
    patterns = {
        'bed_type': r'\b(?:KG|KING|QN|QUEEN|DBL|DOUBLE|TWN|TWIN|SGL|SINGLE)\b',
        'room_type': r'\b(?:STE|SUITE|RM|ROOM|EXEC|EXECUTIVE)\b',
        'amenities': r'\b(?:BALCONY|WIFI|HDTV|WET-BAR)\b',
        'accessibility': r'\b(?:ACCESS|MOB|HEAR)\b',
        'size': r'\b\d+\s*(?:SQ\s*FT|SQFT)\b'
    }
    
    results = []
    for text in texts:
        matches = {}
        for attr_type, pattern in patterns.items():
            matches[attr_type] = re.findall(pattern, text.upper())
        results.append(matches)
    
    return pd.DataFrame(results)

In [53]:
# Test with sample descriptions
sample_texts = [
    'SEMI-FLEX|1 KG EXEC LVL 2-RM STE MOB/HEAR RI SH ACCESS VIS FIREALRM/DOOR/PHN ALRT - WIFI - 55IN HDTV',
    'TRIPADVISOR PLUS RATE|DOUBLE QUEEN SUITE WITH BALCONY - 500 SQ FT - TWO QUEEN BEDS - GRANITE WET-BAR - UPPER FLOOR'
]

extracted_phrases = extract_key_phrases(sample_texts)
print(extracted_phrases)

                 bed_type        room_type           amenities  \
0                    [KG]  [EXEC, RM, STE]        [WIFI, HDTV]
1  [DOUBLE, QUEEN, QUEEN]          [SUITE]  [BALCONY, WET-BAR]

         accessibility         size
0  [MOB, HEAR, ACCESS]           []
1                   []  [500 SQ FT]

In [54]:
# Create regex patterns from our list of attributes
def create_pattern_from_list(attribute_list):
    """Convert list of attributes into regex patterns including common abbreviations"""
    patterns = set()
    
    for attr in attribute_list:
        if pd.isna(attr):
            continue
            
        # Convert to string and uppercase
        attr = str(attr).upper().strip()
        
        # Split on spaces and camelCase
        # First split on spaces
        space_split = attr.split()
        
        # Then handle camelCase within each part
        words = []
        for part in space_split:
            camel_split = re.findall('[A-Z][^A-Z]*', part)
            if camel_split:
                words.extend(camel_split)
            else:
                words.append(part)
        
        # Add full original term (without spaces)
        patterns.add(attr.replace(' ', ''))
        
        # Add space-separated version if multiple words
        if len(space_split) > 1:
            patterns.add(attr)
        
        # Add common abbreviations for multi-word terms
        if len(words) > 1:
            abbrev = ''.join(word[0] for word in words)
            if len(abbrev) > 1:  # Only add if abbreviation is at least 2 chars
                patterns.add(abbrev)
        
        # Add common shortenings (only for words longer than 3 chars)
        for word in words:
            if len(word) > 3:
                patterns.add(word[:3])
        
        # Add the full individual words (if they're longer than 2 chars)
        patterns.update(word for word in words if len(word) > 2)
    
    # Sort patterns by length (longest first) to ensure longer matches take precedence
    patterns = sorted(patterns, key=len, reverse=True)
    
    return r'\b(?:' + '|'.join(patterns) + r')\b'

In [55]:
create_pattern_from_list(room_types_list)

'\\b(?:EXECUTIVE/CLUB SUITE|EXECUTIVE/CLUBSUITE|EXECUTIVE/CLUB ROOM|STANDARD GUEST ROOM|PRESIDENTIAL SUITE|EXECUTIVE/CLUBROOM|LARGE/MASTER SUITE|EXECUTIVECLUBSUITE|EXECUTIVECLUBROOM|STANDARDGUESTROOM|LARGE/MASTERSUITE|FAMILY ROOM/SUITE|PRESIDENTIALSUITE|LARGEMASTERSUITE|RUN OF THE HOUSE|FAMILYROOM/SUITE|TRADITIONAL ROOM|TRADITIONALROOM|ACCESSIBLE ROOM|FAMILYROOMSUITE|ACCESSIBLEROOM|QUADRUPLE ROOM|PRIVILEGE ROOM|SUPERIOR SUITE|SIGNATURE ROOM|PRIVILEGEROOM|SUPERIOR ROOM|SUPERIORSUITE|WELLNESS ROOM|PREMIER SUITE|QUEEN BEDROOM|HERITAGE ROOM|RUNOFTHEHOUSE|QUADRUPLEROOM|SIGNATUREROOM|CLASSIC SUITE|PRESTIGE ROOM|PREMIER ROOM|QUEENBEDROOM|PREMIERSUITE|JUNIOR SUITE|WELLNESSROOM|SUPERIORROOM|DELUXE SUITE|PRESTIGEROOM|TERRACE ROOM|STUDIO SUITE|LUXURY SUITE|KING BEDROOM|HERITAGEROOM|CLASSICSUITE|ECONOMY ROOM|CLASSIC ROOM|COMFORT ROOM|KINGBEDROOM|JUNIORSUITE|LUXURYSUITE|STUDIO ROOM|DELUXESUITE|PREMIERROOM|CLASSICROOM|STUDIOSUITE|ECONOMYROOM|COMFORTROOM|TRIPLE ROOM|LUXURY ROOM|DELUXE ROOM|TERRACEROOM|SINGLE ROOM|CORNER ROOM|DOUBLE ROOM|GUEST ROOM|STUDIOROOM|DOUBLEROOM|TOWER ROOM|DELUXEROOM|CORNERROOM|LUXURYROOM|GRAND ROOM|SINGLEROOM|TRIPLEROOM|URBAN ROOM|URBANROOM|APARTMENT|PENTHOUSE|TWIN ROOM|GUESTROOM|TOWERROOM|GRANDROOM|BUNGALOW|TWINROOM|COTTAGE|CABANA|SUITE|CABIN|VILLA|LOFT)\\b'

In [56]:

def extract_key_phrases(texts, room_types_list, bed_types_list): # amenities_list):
    
    patterns = {
        'bed_type': create_pattern_from_list(bed_types_list),
        'room_type': create_pattern_from_list(room_types_list)#,
        #'amenities': create_pattern_from_list(amenities_list),
        #'accessibility': r'\b(?:ACCESS|MOB|HEAR)\b',
        #'size': r'\b\d+\s*(?:SQ\s*FT|SQFT)\b'
    }
    
    results = []
    for text in texts:
        matches = {}
        for attr_type, pattern in patterns.items():
            matches[attr_type] = re.findall(pattern, text.upper())
        results.append(matches)
    
    return pd.DataFrame(results)

In [57]:
#Test with sample descriptions
sample_texts = [
    'SEMI-FLEX|1 KG EXEC LVL 2-RM STE MOB/HEAR RI SH ACCESS VIS FIREALRM/DOOR/PHN ALRT - WIFI - 55IN HDTV',
    'TRIPADVISOR PLUS RATE|DOUBLE QUEEN SUITE WITH BALCONY - 500 SQ FT - TWO QUEEN BEDS - GRANITE WET-BAR - UPPER FLOOR'
]

extracted_phrases = extract_key_phrases(sample_texts, room_types_list, bed_types_list) #, room_amenities_list)
print(extracted_phrases)

  bed_type room_type
0       []        []
1       []   [SUITE]

In [58]:
# Sample texts with their labels and calculate accuracy
def evaluate_extraction_accuracy(dataset, sample_size=100):
    # Sample from dataset
    sampled_data = dataset.groupby('Guest Room Info').apply(
        lambda x: pd.DataFrame({
            'Room Description Expanded': x['Room Description Expanded'].sample(min(3, len(x))),
            'Guest Room Info': x.name
        })
    ).reset_index(drop=True)
    
    # Extract attributes
    extracted_results = extract_key_phrases(
        sampled_data['Room Description Expanded'].tolist(), 
        room_types_list, 
        bed_types_list
    )
    
    # Calculate accuracy
    correct = 0
    total = len(sampled_data)
    
    for i, row in sampled_data.iterrows():
        true_label = row['Guest Room Info']
        predicted_types = extracted_results.iloc[i]['room_type']
        
        # Convert to uppercase for comparison
        if any(true_label.upper() in pred.upper() for pred in predicted_types):
            correct += 1
    
    accuracy = correct / total
    print(f"\nAccuracy: {accuracy:.2%}")
    
    # Print some examples
    print("\nSample Predictions:")
    for i in range(min(5, len(sampled_data))):
        print(f"\nDescription: {sampled_data.iloc[i]['Room Description Expanded']}")
        print(f"True Label: {sampled_data.iloc[i]['Guest Room Info']}")
        print(f"Predicted: {extracted_results.iloc[i]['room_type']}")
    
    return accuracy, sampled_data, extracted_results

In [59]:
dataset

,Unnamed: 0,Room Description,Guest Room Info,Room Description Expanded
0,0,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...,Accessible Room,FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1,1,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2,2,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...,Accessible Room,PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3,3,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...,Accessible Room,PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4,4,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...,Accessible Room,PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...
...,...,...,...,...
31232,31232,BEST FLEXIBLE RATE|PREMIUM OCEAN VIEW ROOM WHE...,Run of the House,BEST FLEXIBLE RATE|PREMIUM OCEAN VIEW ROOM WHE...
31233,31233,1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...,Run of the House,1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...
31234,31234,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...,Run of the House,BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...
31235,31235,GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...,Run of the House,GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...
31236,31236,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...,Run of the House,CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...

In [63]:
evaluate_extraction_accuracy(dataset)

Accuracy: 60.95%

Sample Predictions:

Description: PARK AND STAY AARP|1KING HEARING ACCESSIBLE SUITE NONSMOKING VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: Accessible Room
Predicted: ['SUITE']

Description: PREFERRED BED AND BREAKFAST|ACCESSIBLE ROOM- 2 DOUBLE BEDS HARBOR VIEW- ACCESSIBLE ROLL-IN SHWR-GRAB BARS-WIDE AUTOMATIC DOORS
True Label: Accessible Room
Predicted: ['ACCESSIBLE ROOM']

Description: JP MORGAN CHASE -PREFERRED RAT|1KG MOB/HEARING ACC TUB-FITNESS ROOM WITHCHIN UP BAR VIS FIREALRM/DOOR/PHN ALRT-TRX SUSP TRAIN BAR
True Label: Accessible Room
Predicted: []

Description: FLEXIBLE RATE - BB|APARTMENT 1 BEDROOM, HARBOUR VIEW
True Label: Apartment
Predicted: ['APARTMENT']

Description: CORPORATE NET|2 BEDROOM APARTMENT 1 KING 2 SINGLES 1 BUNK DESK TV AIR-CONDITIONED KITCHEN
True Label: Apartment
Predicted: ['APARTMENT']

/var/folders/4s/6q_4fv2n6g94291jrzmhdsch0000gn/T/ipykernel_36709/3365797454.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_data = dataset.groupby('Guest Room Info').apply(

(0.6095238095238096,
                              Room Description Expanded  Guest Room Info
 0    PARK AND STAY AARP|1KING HEARING ACCESSIBLE SU...  Accessible Room
 1    PREFERRED BED AND BREAKFAST|ACCESSIBLE ROOM- 2...  Accessible Room
 2    JP MORGAN CHASE -PREFERRED RAT|1KG MOB/HEARING...  Accessible Room
 3    FLEXIBLE RATE - BB|APARTMENT 1 BEDROOM, HARBOU...        Apartment
 4    CORPORATE NET|2 BEDROOM APARTMENT 1 KING 2 SIN...        Apartment
 ..                                                 ...              ...
 100    WIN CONSORTIA COMP BREAKFAST|STANDARD TWIN ROOM        Twin Room
 101  BEST FLEXIBLE RATE|INDIGO PREMIER TWIN ROOM AT...        Twin Room
 102  2X POINTS|VILLA ONE BEDROOM SUITE-ONE KING BED...            Villa
 103  FLEXIBLE RATE|VILLA TWO BEDROOM SUITE - KITCHE...            Villa
 104  PP EXPERIENCE ANGUILLA|4 BEDROOM BEACH FRONT V...            Villa

 [105 rows x 2 columns],
        bed_type          room_type
 0            []            [SUITE]
 1            []  [ACCESSIBLE ROOM]
 2            []                 []
 3            []        [APARTMENT]
 4            []        [APARTMENT]
 ..          ...                ...
 100          []        [TWIN ROOM]
 101          []        [TWIN ROOM]
 102  [KING BED]     [VILLA, SUITE]
 103          []     [VILLA, SUITE]
 104          []            [VILLA]

 [105 rows x 2 columns])

## Fuzzy Matching ##

In [ ]:
##### FUZZY MATCHING #####
def fuzzy_extract_attributes(descriptions, attribute_lists, threshold=80):
    """
    Extract attributes using fuzzy string matching with improved preprocessing
    """
    # Preprocess attribute lists
    processed_attributes = {}
    for attr_type, attr_list in attribute_lists.items():
        processed_attrs = []
        for attr in attr_list:
            if pd.isna(attr) or str(attr).strip() in ['', '-']:  # Skip empty or dash-only values
                continue
                
            # Handle both camelCase and regular strings
            words = re.findall('[A-Z][^A-Z]*', str(attr))
            if words:
                processed_attrs.append(' '.join(word.lower() for word in words))
            else:
                # Clean and add non-empty strings
                cleaned = str(attr).lower().strip()
                if cleaned and cleaned != '-':
                    processed_attrs.append(cleaned)
                    
        processed_attributes[attr_type] = list(set(processed_attrs))  # Remove duplicates
    
    results = []
    
    # Process each description
    for desc in tqdm(descriptions, desc="Processing descriptions"):
        if pd.isna(desc) or not str(desc).strip():  # Handle empty descriptions
            results.append({k: [] for k in attribute_lists.keys()})
            continue
            
        # Convert description to lowercase and clean
        desc_lower = str(desc).lower().strip()
        
        # Split description into words and word pairs, filtering out empty strings
        words = [w for w in desc_lower.split() if w and w != '-']
        word_pairs = [' '.join(pair) for pair in zip(words[:-1], words[1:])]
        
        # Initialize matches for this description
        matches = {attr_type: [] for attr_type in attribute_lists.keys()}
        
        # Check each attribute type
        for attr_type, attrs in processed_attributes.items():
            if not attrs:  # Skip if no valid attributes for this type
                continue
                
            # Try matching single words and word pairs
            for text in words + word_pairs:
                if not text.strip():  # Skip empty strings
                    continue
                    
                # Get closest matches above threshold
                closest = process.extractBests(
                    text, 
                    attrs,
                    scorer=fuzz.token_sort_ratio,
                    score_cutoff=threshold
                )
                
                # Add matches that meet threshold
                for match, score in closest:
                    if match not in matches[attr_type]:  # Avoid duplicates
                        matches[attr_type].append({
                            'matched_text': match,
                            'original_text': text,
                            'score': score
                        })
        
        results.append(matches)
    
    return pd.DataFrame(results)

#%%
# Test on a sample first
sample_size = 100
sample_texts = dataset_raw['Room Description'].sample(n=sample_size, random_state=42)

print("Running fuzzy matching analysis...")
fuzzy_results = fuzzy_extract_attributes(
    sample_texts,
    {
        'room_types': room_types_list,
        'bed_types': bed_types_list,
        'views': room_view_list,
        'amenities': room_amenities_list
    },
    threshold=80  # Adjust this threshold as needed
)

#%%
# Analyze the results
def analyze_fuzzy_results(df):
    for col in df.columns:
        print(f"\nAnalyzing {col}:")
        # Get all matches with their scores
        all_matches = [match for matches in df[col] if matches for match in matches]
        if all_matches:
            matches_df = pd.DataFrame(all_matches)
            print("\nTop matched terms:")
            print(matches_df['matched_text'].value_counts().head(10))
            print("\nAverage match scores:")
            print(matches_df.groupby('matched_text')['score'].mean().sort_values(ascending=False).head(10))
            print("\nSample of original texts that were matched:")
            print(matches_df.groupby('matched_text')['original_text'].agg(list).head(5))
        else:
            print("No matches found")

analyze_fuzzy_results(fuzzy_results)

#%%
print(fuzzy_results.head())

#%%
dataset_sample.to_excel('Data/sample_fuzzy_extraction_input.xlsx', index=False)
fuzzy_results.to_excel('Data/sample_fuzzy_extraction_output.xlsx', index=False)

# %%
full_fuzzy_results = fuzzy_extract_attributes(
    dataset_raw['Room Description'],
    {
        'room_types': room_types_list,
        'bed_types': bed_types_list,
        'views': room_view_list,
        'amenities': room_amenities_list
    }
)

#%%
'''
# Add results to original dataframe
dataset_new = dataset_raw.copy()
dataset_new['fuzzy_room_types'] = full_fuzzy_results['room_types']
dataset_new['fuzzy_bed_types'] = full_fuzzy_results['bed_types']
dataset_new['fuzzy_views'] = full_fuzzy_results['views']
dataset_new['fuzzy_amenities'] = full_fuzzy_results['amenities']

#%%
dataset_new.to_excel('Data/dataset_fuzzy_extraction_v1.xlsx', index=False)
'''

# %%
def evaluate_fuzzy_accuracy(fuzzy_results, full_data):
    """Evaluate fuzzy matching extraction accuracy against true labels"""
    # Ensure we're using the same number of samples
    if len(fuzzy_results) != len(full_data):
        print(f"Warning: Results ({len(fuzzy_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(fuzzy_results), len(full_data))
        fuzzy_results = fuzzy_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct = 0
    total = len(full_data)
    
    print("\nFuzzy Matching Evaluation:")
    print("==========================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info']).lower()
        # Extract room types from fuzzy matches
        predicted_types = [match['matched_text'].lower() for match in fuzzy_results.iloc[i]['room_types']]
        
        # Check for match
        match = any(true_label in pred or pred in true_label for pred in predicted_types)
        correct += match
        
        # Print first 5 examples
        if i < 5:
            print(f"\nDescription: {row['Room Description']}")
            print(f"True Label: {true_label}")
            print(f"Predicted Types: {predicted_types}")
            print(f"Match: {'✓' if match else '✗'}")
    
    accuracy = correct / total
    print(f"\nOverall Accuracy: {accuracy:.2%}")
    
    return accuracy

#%%
# Run fuzzy matching on full dataset and evaluate
fuzzy_results = fuzzy_extract_attributes(
    dataset_raw['Room Description'],
    {
        'room_types': room_types_list,
        'bed_types': bed_types_list,
        'views': room_view_list
    }
)
accuracy = evaluate_fuzzy_accuracy(fuzzy_results, dataset_raw)

## SPaCy ##

In [64]:
import spacy
from collections import defaultdict
from tqdm import tqdm

In [65]:
def extract_attributes_ner(texts, attribute_lists):
    """Extract attributes using spaCy NER with custom patterns
    
    This function processes room descriptions to identify and extract room types, bed types,
    and amenities using SpaCy's Named Entity Recognition with custom pattern matching.
    
    Args:
        texts: List of room description strings to process
        attribute_lists: Dictionary containing lists of valid attributes for each category
            (room_types, bed_types, amenities)
            
    Returns:
        DataFrame containing extracted entities for each text, with confidence scores
    """
    # Load SpaCy's transformer model - using the larger, more accurate transformer model
    # instead of the smaller statistical model for better accuracy
    try:
        nlp = spacy.load("en_core_web_trf")
    except OSError:
        print("Downloading en_core_web_trf model...")
        spacy.cli.download("en_core_web_trf")
        nlp = spacy.load("en_core_web_trf")
    
    # Clean and standardize texts first (e.g., standardize 'bed room' to 'bedroom')
    cleaned_texts = clean_text(texts)
    
    # Setup custom NER patterns for each attribute type
    nlp = setup_ner_patterns(nlp, {
        'room_type': room_types_list,
        'bed_type': bed_types_list,
        'amenity': room_amenities_list
    })
    
    results = []
    
    # Process texts in batches to improve performance
    # Batch size of 32 is a common choice for transformer models,
    # balancing memory usage and processing speed
    batch_size = 32
    for i in tqdm(range(0, len(cleaned_texts), batch_size), desc="Processing with NER"):
        batch_texts = cleaned_texts[i:i + batch_size]
        
        # Use SpaCy's pipe for efficient batch processing
        docs = nlp.pipe(batch_texts)
        
        for doc in docs:
            entities = {
                "text": doc.text,
                "room_types": [],
                "bed_types": [],
                "amenities": []
            }
            
            # Process each entity found by SpaCy
            for ent in doc.ents:
                # Store both the original text and normalized form
                # This helps track what was actually found vs. the standardized version
                if ent.label_ == "ROOM_TYPE":
                    entities["room_types"].append({
                        'text': ent.text,  # Original text as found
                        'normalized': ent.ent_id_  # Standardized form from our patterns
                    })
                elif ent.label_ == "BED_TYPE":
                    entities["bed_types"].append({
                        'text': ent.text,
                        'normalized': ent.ent_id_
                    })
                elif ent.label_ == "AMENITY":
                    entities["amenities"].append({
                        'text': ent.text,
                        'normalized': ent.ent_id_
                    })
            
            results.append(entities)
    
    return pd.DataFrame(results)

def evaluate_spacy_accuracy(spacy_results, full_data):
    """Evaluate the accuracy of SpaCy NER extraction against true labels
    
    This function compares the extracted room types against the actual room types
    in the dataset, calculating both top prediction accuracy (exact matches)
    and any-match accuracy (partial matches).
    
    Args:
        spacy_results: DataFrame containing NER extraction results
        full_data: Original DataFrame with true labels
        
    Returns:
        tuple: (top_prediction_accuracy, any_match_accuracy)
    """
    # Ensure we're evaluating on the same number of samples
    if len(spacy_results) != len(full_data):
        print(f"Warning: Results ({len(spacy_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(spacy_results), len(full_data))
        spacy_results = spacy_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct_any = 0  # Counter for any correct prediction
    correct_top = 0  # Counter for correct top prediction
    total = len(full_data)
    
    print("\nSpaCy Extraction Evaluation:")
    print("===========================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        # Convert to lowercase for case-insensitive comparison
        true_label = str(row['Guest Room Info']).lower()
        predictions = spacy_results.iloc[i]['room_types']
        
        # Skip if no predictions were made
        if not predictions:
            continue
            
        # Check if the top prediction matches
        # Using substring matching to handle partial matches
        # e.g., "luxury suite" should match "suite"
        top_pred = predictions[0][0].lower()
        top_match = true_label in top_pred or top_pred in true_label
        
        # Check if any prediction matches
        # This is more lenient than top prediction matching
        any_match = any(true_label in pred[0].lower() or pred[0].lower() in true_label 
                       for pred in predictions)
        
        correct_top += top_match
        correct_any += any_match
        
        # Print detailed results for the first 5 examples
        # This helps in understanding how the model is performing
        if i < 5:
            print(f"\nDescription: {row['Room Description']}")
            print(f"True Label: {true_label}")
            print(f"Top Prediction: {top_pred} (score: {predictions[0][1]:.3f})")
            print(f"All Predictions: {[(p[0], f'{p[1]:.3f}') for p in predictions]}")
            print(f"Top Match: {'✓' if top_match else '✗'}")
            print(f"Any Match: {'✓' if any_match else '✗'}")
    
    # Calculate final accuracy metrics
    top_accuracy = correct_top / total
    any_accuracy = correct_any / total
    
    print(f"\nTop Prediction Accuracy: {top_accuracy:.2%}")
    print(f"Any Match Accuracy: {any_accuracy:.2%}")
    
    return top_accuracy, any_accuracy

In [66]:
def evaluate_ner_accuracy(spacy_results, full_data):
    """Evaluate the accuracy of SpaCy NER extraction against true labels
    
    This function compares the extracted room types against the actual room types
    using three different matching criteria:
    1. Exact match: 'Luxury Suite' == 'Luxury Suite'
    2. Top substring match: 'Luxury Suite' contains/within 'Suite'
    3. Any substring match: Any prediction contains/within true label
    
    Args:
        spacy_results: DataFrame containing NER extraction results
        full_data: Original DataFrame with true labels
        
    Returns:
        tuple: (exact_accuracy, top_substring_accuracy, any_substring_accuracy)
    """
    # Ensure we're evaluating on the same number of samples
    if len(spacy_results) != len(full_data):
        print(f"Warning: Results ({len(spacy_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(spacy_results), len(full_data))
        spacy_results = spacy_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct_exact = 0     # Counter for exact matches
    correct_top_sub = 0   # Counter for top prediction substring matches
    correct_any_sub = 0   # Counter for any prediction substring matches
    total = len(full_data)
    
    print("\nSpaCy Extraction Evaluation:")
    print("===========================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info']).lower().strip()
        predictions = spacy_results.iloc[i]['room_types']
        
        if not predictions:  # If no predictions were made
            continue
            
        # Get top prediction - handle the new dictionary format
        top_pred = predictions[0]['text'].lower().strip() if predictions else ""
        
        # 1. Check exact match (strict equality)
        exact_match = (true_label == top_pred)
        
        # 2. Check top prediction substring match
        top_sub_match = (true_label in top_pred or top_pred in true_label)
        
        # 3. Check any prediction substring match
        any_sub_match = any(true_label in pred['text'].lower().strip() or 
                          pred['text'].lower().strip() in true_label 
                          for pred in predictions)
        
        correct_exact += exact_match
        correct_top_sub += top_sub_match
        correct_any_sub += any_sub_match
        
        # Print detailed results for the first 5 examples
        if i < 5:
            print(f"\nDescription: {row['Room Description']}")
            print(f"True Label: {true_label}")
            print(f"Top Prediction: {top_pred} (score: {predictions[0]['score']:.3f})")
            # Fixed the nested f-string issue
            pred_info = [(p['text'], "{:.3f}".format(p['score'])) for p in predictions]
            print(f"All Predictions: {pred_info}")
            print(f"Exact Match: {'✓' if exact_match else '✗'}")
            print(f"Top Substring Match: {'✓' if top_sub_match else '✗'}")
            print(f"Any Substring Match: {'✓' if any_sub_match else '✗'}")
    
    # Calculate all accuracy metrics
    exact_accuracy = correct_exact / total
    top_sub_accuracy = correct_top_sub / total
    any_sub_accuracy = correct_any_sub / total
    
    print("\nAccuracy Metrics:")
    print(f"Exact Match Accuracy: {exact_accuracy:.2%}") # Matching exactly
    print(f"Top Substring Match Accuracy: {top_sub_accuracy:.2%}") # Either the top prediction contains the true label or vice versa
    print(f"Any Substring Match Accuracy: {any_sub_accuracy:.2%}") # ANY of the model's predictions (not just the top one) has a substring match with the true label
    
    return exact_accuracy, top_sub_accuracy, any_sub_accuracy

In [67]:
results_spacy_ner = extract_attributes_ner(dataset['Room Description Expanded'], {
    'room_type': room_types_list,
    'bed_type': bed_types_list,
    'amenity': room_amenities_list
})

print("\nExtracted Attributes:")
print(results_spacy_ner)

Processing with NER: 100%|██████████| 977/977 [11:29<00:00,  1.42it/s]

Extracted Attributes:
                                                    text  \
0      FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO...
1      2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE ST...
2      PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE ST...
3      PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE S...
4      PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO S...
...                                                  ...
31232  BEST FLEXIBLE RATE|PREMIUM OCEAN VIEW ROOM WHE...
31233  1000 BONUS POINTS NT INCLUDES|ROOM AND 1000 RE...
31234  BEST FLEXIBLE RATE|HOLIDAY INN EXPRESS ROOM WH...
31235  GREATRATE DISCOUNTED STAYS. 2|RUN OF HOUSE STA...
31236  CWT INCLUDES WIFI USE OF|FITNESS AND WELLNESS ...

                                              room_types bed_types amenities
0      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
1      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
2      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
3      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
4      [{'text': 'accessible room', 'score': 1.1, 'so...        []        []
...                                                  ...       ...       ...
31232                                                 []        []        []
31233                                                 []        []        []
31234                                                 []        []        []
31235                                                 []        []        []
31236                                                 []        []        []

[31237 rows x 4 columns]

In [ ]:
evaluate_ner_accuracy(results_spacy_ner, dataset)

SpaCy Extraction Evaluation:
===========================

Description: FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100)
All Predictions: [('accessible room', '1.100'), ('suite', '1.000')]
Exact Match: ✓
Top Substring Match: ✓
Any Substring Match: ✓

Description: 2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100)
All Predictions: [('accessible room', '1.100'), ('suite', '1.000')]
Exact Match: ✓
Top Substring Match: ✓
Any Substring Match: ✓

Description: PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100)
All Predictions: [('accessible room', '1.100'), ('suite', '1.000')]
Exact Match: ✓
Top Substring Match: ✓
Any Substring Match: ✓

Description: PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100)
All Predictions: [('accessible room', '1.100'), ('suite', '1.000')]
Exact Match: ✓
Top Substring Match: ✓
Any Substring Match: ✓

Description: PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True Label: accessible room
Top Prediction: accessible room (score: 1.100)
All Predictions: [('accessible room', '1.100'), ('suite', '1.000')]
Exact Match: ✓
Top Substring Match: ✓
Any Substring Match: ✓

Accuracy Metrics:
Exact Match Accuracy: 17.32%
Top Substring Match Accuracy: 37.79%
Any Substring Match Accuracy: 41.05%

(0.17319204789192305, 0.3778852002433012, 0.41047475749911966)

## BERT ##

In [78]:
from sentence_transformers import SentenceTransformer, util
import torch

In [79]:
def preprocess_pattern_list(pattern_list):
    """
    Preprocess a list of patterns for attribute matching.
    
    This function:
    1. Handles various text formats (camelCase, space-separated, etc.)
    2. Standardizes text (lowercase, strip whitespace)
    3. Removes duplicates and invalid entries
    
    Args:
        pattern_list: List of attribute patterns to process
        
    Returns:
        list: Cleaned and standardized patterns
    """
    processed = []
    for pattern in pattern_list:
        # Skip invalid entries
        if pd.isna(pattern) or str(pattern).strip() == '':
            continue
            
        # Convert to string and strip whitespace
        pattern = str(pattern).strip()
        
        # Handle different formats:
        # 1. CamelCase/PascalCase splitting
        camel_words = re.findall('[A-Z][^A-Z]*', pattern)
        if camel_words:
            # Join camelCase words with space
            processed_pattern = ' '.join(word.lower() for word in camel_words)
            processed.append(processed_pattern)
            # Also add the original form without spaces
            processed.append(''.join(word.lower() for word in camel_words))
        else:
            # 2. Space-separated words
            words = pattern.lower().split()
            if words:
                # Add both space-separated and joined forms
                processed.append(' '.join(words))
                processed.append(''.join(words))
            else:
                # 3. Single word
                processed.append(pattern.lower())
    
    # Remove duplicates and empty strings, then sort by length (longest first)
    return sorted(list(set(p for p in processed if p.strip())), 
                 key=len, reverse=True)

In [88]:
def extract_with_bert_modified(texts, attribute_lists):
    """Extract room types using BERT embeddings with improved matching"""

    model = SentenceTransformer('all-MiniLM-L6-v2')
    
    # Preprocess room types while preserving case
    room_types = [rt.strip() for rt in room_types_list if pd.notna(rt)]
    
    # Create embeddings for room types
    room_type_embeddings = model.encode(room_types, convert_to_tensor=True)
    
    results = []
    batch_size = 32
    
    # Convert texts to list if it's a Series
    texts = texts.tolist() if isinstance(texts, pd.Series) else texts
    
    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i + batch_size]
        batch_texts = [str(text) if pd.notna(text) else "" for text in batch_texts]
        text_embeddings = model.encode(batch_texts, convert_to_tensor=True)
        
        for idx, (text_embedding, text) in enumerate(zip(text_embeddings, batch_texts)):
            matches = {}
            
            # Check for accessibility keywords
            text_upper = text.upper()
            is_accessible = 'ACCESS' in text_upper or 'ADA' in text_upper
            
            # Calculate similarities
            if len(text_embedding.shape) == 1:
                text_embedding = text_embedding.unsqueeze(0)
            
            similarities = util.cos_sim(text_embedding, room_type_embeddings)[0]
            
            # Use a lower base threshold
            base_threshold = 0.2
            max_sim = torch.max(similarities).item()
            
            if max_sim < base_threshold:
                matches['room_types'] = []
            else:
                # Use a more lenient relative threshold
                relative_threshold = max_sim * 0.6
                matched_indices = torch.where(similarities > relative_threshold)[0]
                
                matches['room_types'] = [
                    (room_types[i], similarities[i].item())
                    for i in matched_indices.tolist()
                ]
                
                # Sort by similarity score
                matches['room_types'].sort(key=lambda x: x[1], reverse=True)
                
                # Keep only top 3 matches
                matches['room_types'] = matches['room_types'][:3]
            
            # If accessible and no matches found, add Accessible Room
            if is_accessible and not matches['room_types']:
                matches['room_types'] = [('Accessible Room', 1.0)]
            elif is_accessible:
                # Add Accessible Room with high confidence if not already present
                if not any('Accessible Room' in rt[0] for rt in matches['room_types']):
                    matches['room_types'].insert(0, ('Accessible Room', 1.0))
            
            results.append(matches)
    
    return pd.DataFrame(results)

In [84]:
def extract_with_bert_modified(texts, room_types_list):
    """
    Extract room types using BERT embeddings with improved confidence scoring.
    
    Args:
        texts: List of room descriptions
        room_types_list: List of possible room types
        
    Returns:
        pd.DataFrame: Results with matched room types and confidence scores
    """
    # Load the model
    model = SentenceTransformer('all-MiniLM-L6-v2')
    
    # Preprocess room types
    room_types = preprocess_pattern_list(room_types_list)
    
    # Pre-compute room type embeddings
    room_type_embeddings = model.encode(room_types, convert_to_tensor=True)
    
    results = []
    batch_size = 32
    
    # Convert texts to list if it's a Series
    texts = texts.tolist() if isinstance(texts, pd.Series) else texts
    
    for i in tqdm(range(0, len(texts), batch_size), desc="Processing with BERT"):
        batch_texts = texts[i:i + batch_size]
        batch_texts = [str(text) if pd.notna(text) else "" for text in batch_texts]
        text_embeddings = model.encode(batch_texts, convert_to_tensor=True)
        
        for idx, (text_embedding, text) in enumerate(zip(text_embeddings, batch_texts)):
            matches = {
                'text': text,
                'room_types': []
            }
            
            # Check for accessibility keywords
            text_upper = text.upper()
            is_accessible = 'ACCESS' in text_upper or 'ADA' in text_upper
            
            # Ensure proper dimensionality
            if len(text_embedding.shape) == 1:
                text_embedding = text_embedding.unsqueeze(0)
            
            # Calculate similarities
            similarities = util.cos_sim(text_embedding, room_type_embeddings)[0]
            
            # Dynamic thresholding
            max_sim = torch.max(similarities).item()
            if max_sim >= 0.3:  # Minimum threshold
                # Use relative threshold (80% of max similarity)
                threshold = max_sim * 0.8
                matched_indices = torch.where(similarities >= threshold)[0]
                
                # Add matches with scores
                matches['room_types'].extend([
                    {
                        'text': room_types[i],
                        'score': similarities[i].item(),
                        'source': 'bert'
                    }
                    for i in matched_indices.tolist()
                ])
            
            # Add accessibility if detected
            if is_accessible:
                matches['room_types'].append({
                    'text': 'accessible room',
                    'score': 1.0,
                    'source': 'rule'
                })
            
            # Sort by confidence score
            matches['room_types'] = sorted(matches['room_types'], 
                                         key=lambda x: x['score'], 
                                         reverse=True)
            
            results.append(matches)
    
    return pd.DataFrame(results)

In [92]:
def evaluate_bert_accuracy(bert_results, full_data):
    """Evaluate BERT extraction accuracy against true labels"""
    if len(bert_results) != len(full_data):
        print(f"Warning: Results ({len(bert_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(bert_results), len(full_data))
        bert_results = bert_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    exact_match = 0
    top_substring = 0
    any_match = 0
    total = len(full_data)
    
    # Track per-category accuracy
    category_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
    
    print("\nBERT Room Type Extraction Evaluation:")
    print("====================================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info'])
        predictions = bert_results.iloc[i]['room_types']
        
        # Update category total
        category_stats[true_label]['total'] += 1
        
        if not predictions:  # No predictions made
            if i < 5:
                print(f"\nExample {i+1}:")
                print(f"Text: {row['Room Description']}")
                print(f"True: {true_label}")
                print(f"Pred: No prediction")
            continue
        
        # Predictions are already tuples of (text, score)
        sorted_preds = sorted(predictions, key=lambda x: x[1], reverse=True)  # Sort by score (index 1)
        top_pred = sorted_preds[0][0].strip()  # Get text (index 0)
        
        # Check exact match
        exact_match_found = any(pred[0].strip() == true_label for pred in sorted_preds)
        if exact_match_found:
            exact_match += 1
            category_stats[true_label]['correct'] += 1
        
        # Check top prediction substring match
        if true_label.lower() in top_pred.lower() or top_pred.lower() in true_label.lower():
            top_substring += 1
        
        # Check any prediction substring match
        if any(true_label.lower() in pred[0].lower() or pred[0].lower() in true_label.lower() 
               for pred in sorted_preds):
            any_match += 1
        
        # Print first 5 examples
        if i < 5:
            print(f"\nExample {i+1}:")
            print(f"Text: {row['Room Description']}")
            print(f"True: {true_label}")
            print(f"Predictions: {[(pred[0], f'{pred[1]:.3f}') for pred in sorted_preds]}")
    
    # Calculate metrics
    exact_match_acc = exact_match / total
    top_substring_acc = top_substring / total
    any_match_acc = any_match / total
    
    print(f"\nAccuracy Metrics:")
    print(f"Exact Match Accuracy: {exact_match_acc:.2%}")
    print(f"Top Substring Match Accuracy: {top_substring_acc:.2%}")
    print(f"Any Substring Match Accuracy: {any_match_acc:.2%}")
    
    print("\nPer-Category Accuracy:")
    for category, stats in category_stats.items():
        if stats['total'] > 0:
            accuracy = stats['correct'] / stats['total']
            print(f"{category}: {accuracy:.2%} ({stats['correct']}/{stats['total']})")
    
    return {
        'exact_match': exact_match_acc,
        'top_substring': top_substring_acc,
        'any_match': any_match_acc,
        'per_category': category_stats
    }

In [90]:
bert_results = extract_with_bert_modified(dataset['Room Description'], {
    'room_types': room_types_list
})

100%|██████████| 977/977 [03:39<00:00,  4.45it/s]

In [93]:
evaluate_bert_accuracy(bert_results, dataset)

BERT Room Type Extraction Evaluation:
====================================

Example 1:
Text: FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.310'), ('Studio Suite', '0.267'), ('Single Room', '0.239')]

Example 2:
Text: 2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '1.000'), ('Signature Room', '0.327'), ('Studio Suite', '0.304'), ('Suite', '0.290')]

Example 3:
Text: PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.366'), ('Family Room/Suite', '0.359'), ('Urban Room', '0.340')]

Example 4:
Text: PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.372'), ('Family Room/Suite', '0.355'), ('Signature Room', '0.338')]

Example 5:
Text: PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Family Room/Suite', '0.361'), ('Accessible Room', '0.353'), ('Studio Suite', '0.341')]

Accuracy Metrics:
Exact Match Accuracy: 49.99%
Top Substring Match Accuracy: 30.27%
Any Substring Match Accuracy: 52.66%

Per-Category Accuracy:
Accessible Room: 98.13% (944/962)
Suite: 3.85% (38/987)
Executive/Club Suite: 50.70% (436/860)
Double Bed: 0.00% (0/815)
King Bedroom: 79.70% (734/921)
Queen Bedroom: 81.30% (661/813)
Penthouse: 85.95% (838/975)
Studio Suite: 20.72% (179/864)
Twin Room: 61.52% (454/738)
Family Room/Suite: 58.45% (564/965)
Cottage: 79.70% (797/1000)
Loft: 64.38% (620/963)
Guest Room: 56.20% (390/694)
Bungalow: 94.27% (922/978)
Villa: 56.63% (525/927)
Junior Suite: 43.38% (400/922)
Executive/Club Room: 43.63% (428/981)
Classic Room: 8.27% (75/907)
Comfort Room: 55.67% (501/900)
Deluxe Room: 65.24% (623/955)
Deluxe Suite: 37.63% (359/954)
Premier Room: 33.26% (292/878)
Standard Room: 0.00% (0/919)
Superior Room: 25.93% (250/964)
Superior Suite: 33.37% (317/950)
Premier Suite: 4.87% (32/657)
Luxury Room: 84.66% (811/958)
Classic Suite: 18.68% (158/846)
Presidential Suite: 82.82% (786/949)
Single Room: 80.91% (763/943)
Studio Room: 16.97% (103/607)
Cabana: 20.43% (201/984)
Apartment: 66.42% (637/959)
Luxury Suite: 80.61% (765/949)
Run of the House: 1.85% (11/593)

{'exact_match': 0.49985594007106954,
 'top_substring': 0.3026859173416141,
 'any_match': 0.5265550468995102,
 'per_category': defaultdict(<function __main__.evaluate_bert_accuracy.<locals>.<lambda>()>,
             {'Accessible Room': {'correct': 944, 'total': 962},
              'Suite': {'correct': 38, 'total': 987},
              'Executive/Club Suite': {'correct': 436, 'total': 860},
              'Double Bed': {'correct': 0, 'total': 815},
              'King Bedroom': {'correct': 734, 'total': 921},
              'Queen Bedroom': {'correct': 661, 'total': 813},
              'Penthouse': {'correct': 838, 'total': 975},
              'Studio Suite': {'correct': 179, 'total': 864},
              'Twin Room': {'correct': 454, 'total': 738},
              'Family Room/Suite': {'correct': 564, 'total': 965},
              'Cottage': {'correct': 797, 'total': 1000},
              'Loft': {'correct': 620, 'total': 963},
              'Guest Room': {'correct': 390, 'total': 694},
              'Bungalow': {'correct': 922, 'total': 978},
              'Villa': {'correct': 525, 'total': 927},
              'Junior Suite': {'correct': 400, 'total': 922},
              'Executive/Club Room': {'correct': 428, 'total': 981},
              'Classic Room': {'correct': 75, 'total': 907},
              'Comfort Room': {'correct': 501, 'total': 900},
              'Deluxe Room': {'correct': 623, 'total': 955},
              'Deluxe Suite': {'correct': 359, 'total': 954},
              'Premier Room': {'correct': 292, 'total': 878},
              'Standard Room': {'correct': 0, 'total': 919},
              'Superior Room': {'correct': 250, 'total': 964},
              'Superior Suite': {'correct': 317, 'total': 950},
              'Premier Suite': {'correct': 32, 'total': 657},
              'Luxury Room': {'correct': 811, 'total': 958},
              'Classic Suite': {'correct': 158, 'total': 846},
              'Presidential Suite': {'correct': 786, 'total': 949},
              'Single Room': {'correct': 763, 'total': 943},
              'Studio Room': {'correct': 103, 'total': 607},
              'Cabana': {'correct': 201, 'total': 984},
              'Apartment': {'correct': 637, 'total': 959},
              'Luxury Suite': {'correct': 765, 'total': 949},
              'Run of the House': {'correct': 11, 'total': 593}})}

In [94]:
def evaluate_bert_accuracy(bert_results, full_data):
    """Evaluate BERT extraction accuracy against true labels"""
    if len(bert_results) != len(full_data):
        print(f"Warning: Results ({len(bert_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(bert_results), len(full_data))
        bert_results = bert_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    exact_match = 0
    top_substring = 0
    any_match = 0
    total = len(full_data)
    
    # Track per-category accuracy
    category_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
    
    print("\nBERT Room Type Extraction Evaluation:")
    print("====================================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info'])
        predictions = bert_results.iloc[i]['room_types']
        
        # Update category total
        category_stats[true_label]['total'] += 1
        
        if not predictions:  # No predictions made
            if i < 5:
                print(f"\nExample {i+1}:")
                print(f"Text: {row['Room Description']}")
                print(f"True: {true_label}")
                print(f"Pred: No prediction")
            continue
        
        # Predictions are already tuples of (text, score)
        sorted_preds = sorted(predictions, key=lambda x: x[1], reverse=True)  # Sort by score
        top_pred = sorted_preds[0][0].strip()  # Get text of top prediction
        
        # Normalize strings for comparison
        true_label_norm = true_label.lower().strip()
        
        # Check matches
        is_exact_match = False
        is_top_substring = False
        is_any_substring = False
        
        for pred_text, score in sorted_preds:
            pred_text_norm = pred_text.lower().strip()
            
            # Check exact match
            if pred_text_norm == true_label_norm:
                is_exact_match = True
                category_stats[true_label]['correct'] += 1
                break  # Found exact match, no need to check other predictions
            
            # Check substring match for top prediction
            if pred_text == top_pred and (true_label_norm in pred_text_norm or pred_text_norm in true_label_norm):
                is_top_substring = True
            
            # Check substring match for any prediction
            if true_label_norm in pred_text_norm or pred_text_norm in true_label_norm:
                is_any_substring = True
        
        # Update counters
        if is_exact_match:
            exact_match += 1
        if is_top_substring:
            top_substring += 1
        if is_any_substring:
            any_match += 1
        
        # Print first 5 examples
        if i < 5:
            print(f"\nExample {i+1}:")
            print(f"Text: {row['Room Description']}")
            print(f"True: {true_label}")
            print(f"Predictions: {[(pred[0], f'{pred[1]:.3f}') for pred in sorted_preds]}")
            print(f"Exact Match: {is_exact_match}")
            print(f"Top Substring Match: {is_top_substring}")
            print(f"Any Substring Match: {is_any_substring}")
    
    # Calculate metrics
    exact_match_acc = exact_match / total
    top_substring_acc = top_substring / total
    any_match_acc = any_match / total
    
    print(f"\nAccuracy Metrics:")
    print(f"Exact Match Accuracy: {exact_match_acc:.2%}")
    print(f"Top Substring Match Accuracy: {top_substring_acc:.2%}")
    print(f"Any Substring Match Accuracy: {any_match_acc:.2%}")
    
    print("\nPer-Category Accuracy:")
    for category, stats in sorted(category_stats.items(), 
                                key=lambda x: x[1]['correct']/x[1]['total'] if x[1]['total'] > 0 else 0, 
                                reverse=True):
        if stats['total'] > 0:
            accuracy = stats['correct'] / stats['total']
            print(f"{category}: {accuracy:.2%} ({stats['correct']}/{stats['total']})")
    
    return {
        'exact_match': exact_match_acc,
        'top_substring': top_substring_acc,
        'any_match': any_match_acc,
        'per_category': category_stats
    }

In [95]:
evaluate_bert_accuracy(bert_results, dataset)

BERT Room Type Extraction Evaluation:
====================================

Example 1:
Text: FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.310'), ('Studio Suite', '0.267'), ('Single Room', '0.239')]
Exact Match: True
Top Substring Match: False
Any Substring Match: False

Example 2:
Text: 2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '1.000'), ('Signature Room', '0.327'), ('Studio Suite', '0.304'), ('Suite', '0.290')]
Exact Match: True
Top Substring Match: False
Any Substring Match: False

Example 3:
Text: PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.366'), ('Family Room/Suite', '0.359'), ('Urban Room', '0.340')]
Exact Match: True
Top Substring Match: False
Any Substring Match: False

Example 4:
Text: PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.372'), ('Family Room/Suite', '0.355'), ('Signature Room', '0.338')]
Exact Match: True
Top Substring Match: False
Any Substring Match: False

Example 5:
Text: PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Family Room/Suite', '0.361'), ('Accessible Room', '0.353'), ('Studio Suite', '0.341')]
Exact Match: True
Top Substring Match: False
Any Substring Match: False

Accuracy Metrics:
Exact Match Accuracy: 49.99%
Top Substring Match Accuracy: 2.17%
Any Substring Match Accuracy: 3.62%

Per-Category Accuracy:
Accessible Room: 98.13% (944/962)
Bungalow: 94.27% (922/978)
Penthouse: 85.95% (838/975)
Luxury Room: 84.66% (811/958)
Presidential Suite: 82.82% (786/949)
Queen Bedroom: 81.30% (661/813)
Single Room: 80.91% (763/943)
Luxury Suite: 80.61% (765/949)
Cottage: 79.70% (797/1000)
King Bedroom: 79.70% (734/921)
Apartment: 66.42% (637/959)
Deluxe Room: 65.24% (623/955)
Loft: 64.38% (620/963)
Twin Room: 61.52% (454/738)
Family Room/Suite: 58.45% (564/965)
Villa: 56.63% (525/927)
Guest Room: 56.20% (390/694)
Comfort Room: 55.67% (501/900)
Executive/Club Suite: 50.70% (436/860)
Executive/Club Room: 43.63% (428/981)
Junior Suite: 43.38% (400/922)
Deluxe Suite: 37.63% (359/954)
Superior Suite: 33.37% (317/950)
Premier Room: 33.26% (292/878)
Superior Room: 25.93% (250/964)
Studio Suite: 20.72% (179/864)
Cabana: 20.43% (201/984)
Classic Suite: 18.68% (158/846)
Studio Room: 16.97% (103/607)
Classic Room: 8.27% (75/907)
Premier Suite: 4.87% (32/657)
Suite: 3.85% (38/987)
Run of the House: 1.85% (11/593)
Double Bed: 0.00% (0/815)
Standard Room: 0.00% (0/919)

{'exact_match': 0.49985594007106954,
 'top_substring': 0.02170502929218555,
 'any_match': 0.03620706213784935,
 'per_category': defaultdict(<function __main__.evaluate_bert_accuracy.<locals>.<lambda>()>,
             {'Accessible Room': {'correct': 944, 'total': 962},
              'Suite': {'correct': 38, 'total': 987},
              'Executive/Club Suite': {'correct': 436, 'total': 860},
              'Double Bed': {'correct': 0, 'total': 815},
              'King Bedroom': {'correct': 734, 'total': 921},
              'Queen Bedroom': {'correct': 661, 'total': 813},
              'Penthouse': {'correct': 838, 'total': 975},
              'Studio Suite': {'correct': 179, 'total': 864},
              'Twin Room': {'correct': 454, 'total': 738},
              'Family Room/Suite': {'correct': 564, 'total': 965},
              'Cottage': {'correct': 797, 'total': 1000},
              'Loft': {'correct': 620, 'total': 963},
              'Guest Room': {'correct': 390, 'total': 694},
              'Bungalow': {'correct': 922, 'total': 978},
              'Villa': {'correct': 525, 'total': 927},
              'Junior Suite': {'correct': 400, 'total': 922},
              'Executive/Club Room': {'correct': 428, 'total': 981},
              'Classic Room': {'correct': 75, 'total': 907},
              'Comfort Room': {'correct': 501, 'total': 900},
              'Deluxe Room': {'correct': 623, 'total': 955},
              'Deluxe Suite': {'correct': 359, 'total': 954},
              'Premier Room': {'correct': 292, 'total': 878},
              'Standard Room': {'correct': 0, 'total': 919},
              'Superior Room': {'correct': 250, 'total': 964},
              'Superior Suite': {'correct': 317, 'total': 950},
              'Premier Suite': {'correct': 32, 'total': 657},
              'Luxury Room': {'correct': 811, 'total': 958},
              'Classic Suite': {'correct': 158, 'total': 846},
              'Presidential Suite': {'correct': 786, 'total': 949},
              'Single Room': {'correct': 763, 'total': 943},
              'Studio Room': {'correct': 103, 'total': 607},
              'Cabana': {'correct': 201, 'total': 984},
              'Apartment': {'correct': 637, 'total': 959},
              'Luxury Suite': {'correct': 765, 'total': 949},
              'Run of the House': {'correct': 11, 'total': 593}})}

In [96]:
def evaluate_bert_accuracy(bert_results, full_data):
    """Evaluate BERT extraction accuracy against true labels"""
    if len(bert_results) != len(full_data):
        print(f"Warning: Results ({len(bert_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(bert_results), len(full_data))
        bert_results = bert_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct = 0
    total = len(full_data)
    
    # Track per-category accuracy
    category_stats = defaultdict(lambda: {'correct': 0, 'total': 0})
    
    print("\nBERT Room Type Extraction Evaluation:")
    print("====================================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info'])
        predictions = bert_results.iloc[i]['room_types']
        
        # Update category total
        category_stats[true_label]['total'] += 1
        
        if not predictions:  # No predictions made
            if i < 5:
                print(f"\nExample {i+1}:")
                print(f"Text: {row['Room Description']}")
                print(f"True: {true_label}")
                print(f"Pred: No prediction")
            continue
        
        # Sort predictions by confidence score
        sorted_preds = sorted(predictions, key=lambda x: x[1], reverse=True)
        
        # Check for exact match with top prediction
        top_pred = sorted_preds[0][0].strip()
        match = (top_pred == true_label)
        
        if match:
            correct += 1
            category_stats[true_label]['correct'] += 1
        
        # Print first 5 examples
        if i < 5:
            print(f"\nExample {i+1}:")
            print(f"Text: {row['Room Description']}")
            print(f"True: {true_label}")
            print(f"Predictions: {[(pred[0], f'{pred[1]:.3f}') for pred in sorted_preds]}")
            print(f"Match: {'✓' if match else '✗'}")
    
    accuracy = correct / total # Accuracy considering exact matches for BERT's top predictions
    
    print(f"\nOverall Accuracy: {accuracy:.2%}")
    
    print("\nPer-Category Accuracy:")
    for category, stats in sorted(category_stats.items(), 
                                key=lambda x: x[1]['correct']/x[1]['total'] if x[1]['total'] > 0 else 0, 
                                reverse=True):
        if stats['total'] > 0:
            cat_accuracy = stats['correct'] / stats['total']
            print(f"{category}: {cat_accuracy:.2%} ({stats['correct']}/{stats['total']})")
    
    return {
        'accuracy': accuracy,
        'per_category': category_stats
    }

In [97]:
evaluate_bert_accuracy(bert_results, dataset)

BERT Room Type Extraction Evaluation:
====================================

Example 1:
Text: FLEXIBLE RATE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.310'), ('Studio Suite', '0.267'), ('Single Room', '0.239')]
Match: ✓

Example 2:
Text: 2X POINTS PACKAGE|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '1.000'), ('Signature Room', '0.327'), ('Studio Suite', '0.304'), ('Suite', '0.290')]
Match: ✓

Example 3:
Text: PARK AND STAY AAA|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.366'), ('Family Room/Suite', '0.359'), ('Urban Room', '0.340')]
Match: ✓

Example 4:
Text: PARK AND STAY AARP|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Accessible Room', '0.372'), ('Family Room/Suite', '0.355'), ('Signature Room', '0.338')]
Match: ✓

Example 5:
Text: PARK AND GO|2QUEEN HEARING ACCESSIBLE STUDIO SUITE NOSMOK VISUAL FIRE ALARM/DOOR/PHONE ALERT
True: Accessible Room
Predictions: [('Family Room/Suite', '0.361'), ('Accessible Room', '0.353'), ('Studio Suite', '0.341')]
Match: ✗

Overall Accuracy: 28.10%

Per-Category Accuracy:
Accessible Room: 75.88% (730/962)
Bungalow: 68.10% (666/978)
Presidential Suite: 60.91% (578/949)
King Bedroom: 60.04% (553/921)
Queen Bedroom: 57.20% (465/813)
Penthouse: 56.31% (549/975)
Cottage: 52.60% (526/1000)
Luxury Suite: 49.63% (471/949)
Single Room: 48.99% (462/943)
Luxury Room: 40.92% (392/958)
Loft: 40.71% (392/963)
Twin Room: 36.31% (268/738)
Apartment: 33.47% (321/959)
Villa: 33.44% (310/927)
Family Room/Suite: 32.85% (317/965)
Executive/Club Suite: 30.00% (258/860)
Comfort Room: 24.00% (216/900)
Junior Suite: 19.20% (177/922)
Superior Suite: 18.74% (178/950)
Deluxe Room: 18.53% (177/955)
Deluxe Suite: 14.05% (134/954)
Guest Room: 12.82% (89/694)
Executive/Club Room: 10.40% (102/981)
Cabana: 9.86% (97/984)
Studio Suite: 8.45% (73/864)
Premier Room: 8.31% (73/878)
Classic Suite: 6.86% (58/846)
Studio Room: 6.26% (38/607)
Superior Room: 6.22% (60/964)
Classic Room: 1.98% (18/907)
Run of the House: 1.85% (11/593)
Premier Suite: 1.37% (9/657)
Suite: 0.91% (9/987)
Double Bed: 0.00% (0/815)
Standard Room: 0.00% (0/919)

{'accuracy': 0.28098088804942856,
 'per_category': defaultdict(<function __main__.evaluate_bert_accuracy_v3.<locals>.<lambda>()>,
             {'Accessible Room': {'correct': 730, 'total': 962},
              'Suite': {'correct': 9, 'total': 987},
              'Executive/Club Suite': {'correct': 258, 'total': 860},
              'Double Bed': {'correct': 0, 'total': 815},
              'King Bedroom': {'correct': 553, 'total': 921},
              'Queen Bedroom': {'correct': 465, 'total': 813},
              'Penthouse': {'correct': 549, 'total': 975},
              'Studio Suite': {'correct': 73, 'total': 864},
              'Twin Room': {'correct': 268, 'total': 738},
              'Family Room/Suite': {'correct': 317, 'total': 965},
              'Cottage': {'correct': 526, 'total': 1000},
              'Loft': {'correct': 392, 'total': 963},
              'Guest Room': {'correct': 89, 'total': 694},
              'Bungalow': {'correct': 666, 'total': 978},
              'Villa': {'correct': 310, 'total': 927},
              'Junior Suite': {'correct': 177, 'total': 922},
              'Executive/Club Room': {'correct': 102, 'total': 981},
              'Classic Room': {'correct': 18, 'total': 907},
              'Comfort Room': {'correct': 216, 'total': 900},
              'Deluxe Room': {'correct': 177, 'total': 955},
              'Deluxe Suite': {'correct': 134, 'total': 954},
              'Premier Room': {'correct': 73, 'total': 878},
              'Standard Room': {'correct': 0, 'total': 919},
              'Superior Room': {'correct': 60, 'total': 964},
              'Superior Suite': {'correct': 178, 'total': 950},
              'Premier Suite': {'correct': 9, 'total': 657},
              'Luxury Room': {'correct': 392, 'total': 958},
              'Classic Suite': {'correct': 58, 'total': 846},
              'Presidential Suite': {'correct': 578, 'total': 949},
              'Single Room': {'correct': 462, 'total': 943},
              'Studio Room': {'correct': 38, 'total': 607},
              'Cabana': {'correct': 97, 'total': 984},
              'Apartment': {'correct': 321, 'total': 959},
              'Luxury Suite': {'correct': 471, 'total': 949},
              'Run of the House': {'correct': 11, 'total': 593}})}

## Fuzzy Matching ##

In [ ]:
def fuzzy_extract_attributes(descriptions, attribute_lists, threshold=80):
    """
    Extract attributes using fuzzy string matching with improved preprocessing
    """
    # Preprocess attribute lists
    processed_attributes = {}
    for attr_type, attr_list in attribute_lists.items():
        processed_attrs = []
        for attr in attr_list:
            if pd.isna(attr) or str(attr).strip() in ['', '-']:  # Skip empty or dash-only values
                continue
                
            # Handle both camelCase and regular strings
            words = re.findall('[A-Z][^A-Z]*', str(attr))
            if words:
                processed_attrs.append(' '.join(word.lower() for word in words))
            else:
                # Clean and add non-empty strings
                cleaned = str(attr).lower().strip()
                if cleaned and cleaned != '-':
                    processed_attrs.append(cleaned)
                    
        processed_attributes[attr_type] = list(set(processed_attrs))  # Remove duplicates
    
    results = []
    
    # Process each description
    for desc in tqdm(descriptions, desc="Processing descriptions"):
        if pd.isna(desc) or not str(desc).strip():  # Handle empty descriptions
            results.append({k: [] for k in attribute_lists.keys()})
            continue
            
        # Convert description to lowercase and clean
        desc_lower = str(desc).lower().strip()
        
        # Split description into words and word pairs, filtering out empty strings
        words = [w for w in desc_lower.split() if w and w != '-']
        word_pairs = [' '.join(pair) for pair in zip(words[:-1], words[1:])]
        
        # Initialize matches for this description
        matches = {attr_type: [] for attr_type in attribute_lists.keys()}
        
        # Check each attribute type
        for attr_type, attrs in processed_attributes.items():
            if not attrs:  # Skip if no valid attributes for this type
                continue
                
            # Try matching single words and word pairs
            for text in words + word_pairs:
                if not text.strip():  # Skip empty strings
                    continue
                    
                # Get closest matches above threshold
                closest = process.extractBests(
                    text, 
                    attrs,
                    scorer=fuzz.token_sort_ratio,
                    score_cutoff=threshold
                )
                
                # Add matches that meet threshold
                for match, score in closest:
                    if match not in matches[attr_type]:  # Avoid duplicates
                        matches[attr_type].append({
                            'matched_text': match,
                            'original_text': text,
                            'score': score
                        })
        
        results.append(matches)
    
    return pd.DataFrame(results)

In [ ]:

#%%
# Analyze the results
def analyze_fuzzy_results(df):
    for col in df.columns:
        print(f"\nAnalyzing {col}:")
        # Get all matches with their scores
        all_matches = [match for matches in df[col] if matches for match in matches]
        if all_matches:
            matches_df = pd.DataFrame(all_matches)
            print("\nTop matched terms:")
            print(matches_df['matched_text'].value_counts().head(10))
            print("\nAverage match scores:")
            print(matches_df.groupby('matched_text')['score'].mean().sort_values(ascending=False).head(10))
            print("\nSample of original texts that were matched:")
            print(matches_df.groupby('matched_text')['original_text'].agg(list).head(5))
        else:
            print("No matches found")

analyze_fuzzy_results(fuzzy_results)

#%%
print(fuzzy_results.head())

#%%
dataset_sample.to_excel('Data/sample_fuzzy_extraction_input.xlsx', index=False)
fuzzy_results.to_excel('Data/sample_fuzzy_extraction_output.xlsx', index=False)

# %%
full_fuzzy_results = fuzzy_extract_attributes(
    dataset_raw['Room Description'],
    {
        'room_types': room_types_list,
        'bed_types': bed_types_list,
        'views': room_view_list,
        'amenities': room_amenities_list
    }
)

#%%
'''
# Add results to original dataframe
dataset_new = dataset_raw.copy()
dataset_new['fuzzy_room_types'] = full_fuzzy_results['room_types']
dataset_new['fuzzy_bed_types'] = full_fuzzy_results['bed_types']
dataset_new['fuzzy_views'] = full_fuzzy_results['views']
dataset_new['fuzzy_amenities'] = full_fuzzy_results['amenities']

#%%
dataset_new.to_excel('Data/dataset_fuzzy_extraction_v1.xlsx', index=False)
'''

In [ ]:
def evaluate_fuzzy_accuracy(fuzzy_results, full_data):
    """Evaluate fuzzy matching extraction accuracy against true labels"""
    # Ensure we're using the same number of samples
    if len(fuzzy_results) != len(full_data):
        print(f"Warning: Results ({len(fuzzy_results)}) and samples ({len(full_data)}) length mismatch")
        n_samples = min(len(fuzzy_results), len(full_data))
        fuzzy_results = fuzzy_results.iloc[:n_samples]
        full_data = full_data.iloc[:n_samples]
    
    correct = 0
    total = len(full_data)
    
    print("\nFuzzy Matching Evaluation:")
    print("==========================")
    
    for i, (_, row) in enumerate(full_data.iterrows()):
        true_label = str(row['Guest Room Info']).lower()
        # Extract room types from fuzzy matches
        predicted_types = [match['matched_text'].lower() for match in fuzzy_results.iloc[i]['room_types']]
        
        # Check for match
        match = any(true_label in pred or pred in true_label for pred in predicted_types)
        correct += match
        
        # Print first 5 examples
        if i < 5:
            print(f"\nDescription: {row['Room Description']}")
            print(f"True Label: {true_label}")
            print(f"Predicted Types: {predicted_types}")
            print(f"Match: {'✓' if match else '✗'}")
    
    accuracy = correct / total
    print(f"\nOverall Accuracy: {accuracy:.2%}")
    
    return accuracy

In [ ]:
# Run fuzzy matching on full dataset and evaluate
fuzzy_results = fuzzy_extract_attributes(
    dataset_raw['Room Description'],
    {
        'room_types': room_types_list,
        'bed_types': bed_types_list,
        'views': room_view_list
    }
)
accuracy = evaluate_fuzzy_accuracy(fuzzy_results, dataset_raw)

In [ ]:
# %%
# Text Analysis and Clusterization using Embeddings

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# For generating text embeddings
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.semi_supervised import LabelPropagation
from umap import UMAP

# For clustering
from sklearn.cluster import KMeans

# For visualization (dimensionality reduction)
from sklearn.manifold import TSNE

# %%
# ----------------------------
# 1. Sample Data Preparation
# ----------------------------
# Replace this sample data with your actual dataset
data = {
    "description": dataset_raw['Room Description'],
    "current_label": dataset_raw['Guest Room Info']
}

# Create a DataFrame
df = pd.DataFrame(data)

# ----------------------------------
# 2. Generate Embeddings for the Text
# ----------------------------------
# Load a pre-trained sentence transformer model
# You can choose another model if needed (e.g., 'all-MiniLM-L6-v2', 'paraphrase-MiniLM-L6-v2', etc.)
model = SentenceTransformer('all-MiniLM-L6-v2')

# Compute embeddings for each room description
embeddings = model.encode(df['description'].tolist(), convert_to_numpy=True)

# ----------------------------
# 3. Clustering the Embeddings
# ----------------------------
# Define the number of clusters (adjust as needed)
num_clusters = 35

# Use KMeans clustering on the embeddings
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
clusters = kmeans.fit_predict(embeddings)

# Add the cluster labels to the DataFrame
df['cluster'] = clusters

# ----------------------------
# 4. Visualize the Clusters using t-SNE
# ----------------------------
# Reduce embeddings to 2 dimensions using t-SNE for visualization
tsne = TSNE(n_components=2, random_state=42)
embeddings_2d = tsne.fit_transform(embeddings)

# Add t-SNE coordinates to the DataFrame
df['tsne_x'] = embeddings_2d[:, 0]
df['tsne_y'] = embeddings_2d[:, 1]

#%%
# Plot the clusters
plt.figure(figsize=(10, 8))
sns.scatterplot(x='tsne_x', y='tsne_y', hue='cluster', data=df, palette='tab10', s=100, alpha=0.8)
# Optionally, annotate the points with the room description (or part of it)
#for i, row in df.iterrows():
#    plt.text(row['tsne_x'] + 0.2, row['tsne_y'] + 0.2, row['description'], fontsize=9)

plt.title("t-SNE Visualization of Room Description Clusters")
plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2")
plt.legend(title="Cluster")
plt.show()

# ----------------------------
# 5. Review the Cluster Assignments
# ----------------------------
# Print the DataFrame with room descriptions, current labels, and assigned cluster
print(df[['description', 'current_label', 'cluster']])

# %%
df.to_csv('minilm_kmeans_clustered.csv', index=False)

#%%
df.groupby(['cluster', 'current_label']).size().reset_index(name='count')

In [ ]:
#%% ##### TOPIC MODELING #####
# Topic Modeling Prep
dataset_normalized_attributes = pd.read_excel('Data/Normalized_product_attribute_name.xlsx', sheet_name = 'Normalized Product Attributes')
dataset_normalized_attributes

room_types = dataset_normalized_attributes['RoomType'].dropna().unique()
room_types_list = room_types.tolist()

# %%

# Collating the Normalized Product Attribute data to be excluded through custom stop words
bed_types = dataset_normalized_attributes['BedType'].dropna().unique()
bed_types_list = bed_types.tolist()

rate_plan_inclusives_raw = dataset_normalized_attributes['Rateplan Incl/Value-adds'].dropna().unique()
rate_plan_inclusives = rate_plan_inclusives_raw.tolist()

room_amenities_raw = dataset_normalized_attributes['Room Amenities'].dropna().unique()
room_amenities_list = room_amenities_raw.tolist()

meal_plan_raw = dataset_normalized_attributes['Mealplan'].dropna().unique()
meal_plan_list = meal_plan_raw.tolist()

room_view_raw = dataset_normalized_attributes['RoomView'].dropna().unique()
room_view_list = room_view_raw.tolist()

taxes_fees_raw = dataset_normalized_attributes['Taxes & Fees'].dropna().unique()
taxes_fees_list = taxes_fees_raw.tolist()



#%%
#Topic modeling
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from bertopic import BERTopic
import plotly.express as px

#%%
# Clean and preprocess text (reusing your existing tokenize_text function)
def preprocess_for_topic_modeling(text):
    if pd.isna(text):
        return ""
    words = tokenize_text(text)
    # Remove very common words that might not be in standard stop words
    custom_stops = {'a', 'an', 'the', 'in', 'on', 'at', 'with', 'and', 'or', 'to', 'for'}
    words = [w for w in words if w not in custom_stops]
    return ' '.join(words)


#%%
# Preprocess all descriptions
processed_texts = dataset_raw['Room Description'].apply(preprocess_for_topic_modeling)

# 1. LDA Approach
# --------------
def run_lda_analysis(texts, n_topics=35):
    # Create document-term matrix
    vectorizer = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
    doc_term_matrix = vectorizer.fit_transform(texts)
    
    # Train LDA model
    lda = LatentDirichletAllocation(
        n_components=n_topics,
        random_state=42,
        max_iter=20
    )
    lda_output = lda.fit_transform(doc_term_matrix)
    
    # Print top words for each topic
    feature_names = vectorizer.get_feature_names_out()
    for topic_idx, topic in enumerate(lda.components_):
        top_words = [feature_names[i] for i in topic.argsort()[:-10:-1]]
        print(f"Topic {topic_idx + 1}: {', '.join(top_words)}")
    
    return lda_output, lda, vectorizer

# 2. BERTopic Approach
# -------------------
def run_bertopic_analysis(texts, n_topics=35):
    topic_model = BERTopic(nr_topics=n_topics)
    topics, probs = topic_model.fit_transform(texts)
    
    # Get topic info
    topic_info = topic_model.get_topic_info()
    
    # Print topics
    for topic in topic_model.get_topics():
        if topic != -1:  # -1 is reserved for outliers
            print(f"Topic {topic}: {topic_model.get_topic(topic)}")
    
    return topics, probs, topic_model

#%%
# Run both analyses
print("Running LDA Analysis...")
lda_output, lda_model, vectorizer = run_lda_analysis(processed_texts)

print("\nRunning BERTopic Analysis...")
topics, probs, bertopic_model = run_bertopic_analysis(processed_texts)

#%%
# Visualization for LDA
# --------------------
def visualize_topics_distribution(lda_output):
    # Get the dominant topic for each document
    dominant_topics = np.argmax(lda_output, axis=1)
    topic_counts = pd.Series(dominant_topics).value_counts().sort_index()
    
    # Create visualization
    fig = px.bar(
        x=topic_counts.index + 1,  # Add 1 to make topics 1-based
        y=topic_counts.values,
        labels={'x': 'Topic Number', 'y': 'Number of Documents'},
        title='Distribution of Dominant Topics Across Documents'
    )
    fig.show()

# Visualization for BERTopic
# -------------------------
def visualize_bertopic_results(topic_model):
    # Topic visualization
    topic_model.visualize_topics()
    
    # Topic hierarchy
    topic_model.visualize_hierarchy()
    
    # Topic similarity
    topic_model.visualize_heatmap()

#%%
# Run visualizations
print("\nVisualizing LDA Results...")
visualize_topics_distribution(lda_output)

print("\nVisualizing BERTopic Results...")
visualize_bertopic_results(bertopic_model)

# Add topics to original dataframe
dataset_raw['LDA_Topic'] = np.argmax(lda_output, axis=1)
dataset_raw['BERTopic'] = topics

#%%
lda_output

#%%
bertopic_model.visualize_topics()

#%%
# Topic hierarchy
bertopic_model.visualize_hierarchy()

#%%
# Topic similarity
bertopic_model.visualize_heatmap()

#%% ##### TF-IDF Topic Modeling #####
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF  # Non-negative Matrix Factorization - works well with TF-IDF
from sklearn.decomposition import LatentDirichletAllocation
import numpy as np
import pandas as pd

#%%
def run_tfidf_topic_modeling(texts, n_topics=35, top_n_words=10):
    # Create TF-IDF matrix
    tfidf_vectorizer = TfidfVectorizer(
        max_df=0.95,         # Ignore terms that appear in >95% of docs
        min_df=2,           # Ignore terms that appear in <2 docs
        stop_words='english',
        ngram_range=(1, 2)  # Consider both unigrams and bigrams
    )
    tfidf_matrix = tfidf_vectorizer.fit_transform(texts)
    
    # 1. Using NMF (works better with TF-IDF)
    print("Running NMF with TF-IDF...")
    nmf_model = NMF(n_components=n_topics, random_state=42)
    nmf_output = nmf_model.fit_transform(tfidf_matrix)
    
    # 2. Using LDA with TF-IDF (less common but possible)
    print("\nRunning LDA with TF-IDF...")
    lda_model = LatentDirichletAllocation(
        n_components=n_topics,
        random_state=42
    )
    lda_output = lda_model.fit_transform(tfidf_matrix)
    
    # Get feature names (words)
    feature_names = tfidf_vectorizer.get_feature_names_out()

    return {
        'features': feature_names,
        'vectorizer': tfidf_vectorizer,
        'nmf_model': nmf_model,
        'nmf_output': nmf_output,
        'lda_model': lda_model,
        'lda_output': lda_output
    }

#%%
# Run the analysis
processed_texts = dataset_raw['Room Description'].apply(preprocess_for_topic_modeling)
results = run_tfidf_topic_modeling(processed_texts, n_topics=35)

#%%
# Print top words for each topic from NMF
print("\nNMF Topics:")
for topic_idx, topic in enumerate(results['nmf_model'].components_):
    top_words_idx = topic.argsort()[:-10-1:-1]
    feature_names = results['features']
    top_words = [feature_names[i] for i in top_words_idx]
    print(f"Topic {topic_idx + 1}: {', '.join(top_words)}")

#%%
# Print top words for each topic from LDA
print("\nLDA Topics:")
for topic_idx, topic in enumerate(lda_model.components_):
    top_words_idx = topic.argsort()[:-10-1:-1]
    feature_names = results['features']
    top_words = [feature_names[i] for i in top_words_idx]
    print(f"Topic {topic_idx + 1}: {', '.join(top_words)}")
    


#%%
# Add topic assignments to the original dataframe
dataset_raw['NMF_Topic'] = np.argmax(results['nmf_output'], axis=1)
dataset_raw['TFIDF_LDA_Topic'] = np.argmax(results['lda_output'], axis=1)

#%%
# Visualize topic distribution
import plotly.express as px

def plot_topic_distribution(topic_assignments, title):
    topic_counts = pd.Series(topic_assignments).value_counts().sort_index()
    fig = px.bar(
        x=topic_counts.index + 1,
        y=topic_counts.values,
        labels={'x': 'Topic Number', 'y': 'Number of Documents'},
        title=title
    )
    fig.show()

# Plot distributions
plot_topic_distribution(dataset_raw['NMF_Topic'], 'Distribution of NMF Topics')
plot_topic_distribution(dataset_raw['TFIDF_LDA_Topic'], 'Distribution of TF-IDF LDA Topics')